#include <QtTest>
#include <QSet>
#include <QFile>
#include <QTcpServer>
#include <QTcpSocket>
#include <QTemporaryDir>
#include <QDateTime>
#include <memory>
#include "Vouchers.hpp"
#include "Vault.hpp"
class VoucherTests:public QObject{Q_OBJECT
private slots:
 void generation(){auto batch=Vouchers::generateBatch({{"quantity",5000},{"usernameLength",8},{"passwordLength",10},{"passwordMode","RANDOM"},{"profile","default"},{"mode","HOTSPOT"},{"durationValue",2},{"durationUnit","HOURS"},{"limitBytesTotal","104857600"}});auto cards=batch["vouchers"].toArray();QCOMPARE(cards.size(),5000);QSet<QString> names;for(auto c:cards){auto o=c.toObject();names.insert(o["username"].toString());QCOMPARE(o["password"].toString().size(),10);QCOMPARE(o["limitUptime"].toString(),QString("2h"));QCOMPARE(o["limitBytesTotal"].toInteger(),qint64(104857600));}QCOMPARE(names.size(),5000);QVERIFY_EXCEPTION_THROWN(Vouchers::generateBatch({{"quantity",5001},{"mode","OFFLINE"}}),std::runtime_error);QVERIFY_EXCEPTION_THROWN(Vouchers::generateBatch({{"quantity",1},{"profile",""},{"mode","HOTSPOT"}}),std::runtime_error);}
 void scriptEscapes(){auto batch=Vouchers::generateBatch({{"quantity",1},{"profile","x\"; /system reboot"},{"mode","HOTSPOT"},{"prefix","$"}});auto script=Vouchers::script(batch);QVERIFY(script.contains("profile=\"x\\\"; /system reboot\""));QVERIFY(script.contains("name=\"\\$"));QVERIFY(!script.contains('\r'));auto offline=Vouchers::generateBatch({{"quantity",1},{"mode","OFFLINE"}});QVERIFY(Vouchers::script(offline).isEmpty());}
 void loginQrNeverIncludesSeparatePassword(){QJsonObject voucher{{"mode","HOTSPOT"},{"username","alice"},{"password","separate-secret"},{"profile","basic"},{"branding",QJsonObject{{"portalLoginUrl","http://192.168.88.1/login"}}}};auto payload=Vouchers::qrPayload(voucher);QVERIFY(payload.contains("#u=alice&same=0"));QVERIFY(!payload.contains("separate-secret"));QVERIFY(!QUrl(payload).hasQuery());voucher["branding"]=QJsonObject{{"portalLoginUrl","https://example.com/login?password=x"}};QVERIFY_EXCEPTION_THROWN(Vouchers::qrPayload(voucher),std::runtime_error);}
 void exportedExpiry(){auto expiry=QDateTime::currentMSecsSinceEpoch()+3600000;auto batch=Vouchers::generateBatch({{"quantity",1},{"mode","HOTSPOT"},{"profile","basic"},{"absoluteExpiryEpochMs",expiry}});auto script=Vouchers::script(batch);QVERIFY(script.contains("/system scheduler add"));QVERIFY(script.contains("interval=0s"));QVERIFY(script.contains("disable [find where name="));QVERIFY(script.contains("/ip hotspot active remove"));auto card=batch["vouchers"].toArray().first().toObject();QVERIFY(card.contains("limitBytesTotal"));}
 void qrOutput(){auto batch=Vouchers::generateBatch({{"quantity",1},{"mode","OFFLINE"}});auto card=batch["vouchers"].toArray().first().toObject();auto payload=Vouchers::qrPayload(card);QVERIFY(payload.contains("NOT activated"));auto image=Vouchers::qr(payload);QVERIFY(!image.isNull());QVERIFY(image.save("voucher-qr-test.png"));QFile file("voucher-qr-test.txt");QVERIFY(file.open(QIODevice::WriteOnly));file.write(payload.toUtf8());}
#ifdef Q_OS_WIN
 void finiteVoucherVerifiedBeforeEnable(){QTcpServer server;QVERIFY(server.listen(QHostAddress::LocalHost));QJsonObject user,scheduler;bool verifiedExpiry=false,prematureEnable=false;int adds=0;connect(&server,&QTcpServer::newConnection,this,[&]{auto peer=server.nextPendingConnection();auto buffer=std::make_shared<QByteArray>();connect(peer,&QTcpSocket::readyRead,this,[&,peer,buffer]{*buffer+=peer->readAll();QStringList words;while(RouterCodec::takeSentence(*buffer,words)==1){auto command=words.takeFirst();QJsonObject attrs;for(auto word:words)if(word.startsWith('=')){int pos=word.indexOf('=',1);if(pos>0)attrs[word.mid(1,pos-1)]=word.mid(pos+1);}QJsonArray rows;if(command=="/ip/hotspot/user/add"){adds++;user=attrs;user[".id"]="*A";}else if(command=="/ip/hotspot/user/print"){if(!user.isEmpty())rows.append(user);}else if(command=="/system/clock/print")rows.append(QJsonObject{{"date",QDate::currentDate().toString("yyyy-MM-dd")},{"time",QTime::currentTime().toString("HH:mm:ss")}});else if(command=="/system/scheduler/add"){scheduler=attrs;scheduler[".id"]="*S";scheduler["disabled"]="no";}else if(command=="/system/scheduler/print"){rows.append(scheduler);verifiedExpiry=!scheduler.isEmpty();}else if(command=="/ip/hotspot/user/enable"){prematureEnable=!verifiedExpiry;user["disabled"]="no";}else if(command=="/system/identity/print")rows.append(QJsonObject{{"name","Mock"}});QByteArray output;for(auto row:rows){QStringList sentence{"!re"};auto object=row.toObject();for(auto key:object.keys())sentence.append("="+key+"="+object[key].toString());output+=RouterCodec::sentence(sentence);}peer->write(output+RouterCodec::sentence({"!done"}));}});});RouterClient client;client.configure("127.0.0.1",server.serverPort(),"admin","pw","API");bool connected=false;client.read("system/identity",[&](RouterReply result){connected=result.ok();});QTRY_VERIFY_WITH_TIMEOUT(connected,5000);QTemporaryDir folder;Vouchers vouchers(&client,nullptr,folder.path());vouchers.generate({{"quantity",1},{"mode","HOTSPOT"},{"profile","basic"},{"absoluteExpiryEpochMs",QDateTime::currentMSecsSinceEpoch()+3600000}});QCOMPARE(vouchers.cards().size(),1);vouchers.activate();QTRY_VERIFY_WITH_TIMEOUT(!vouchers.busy(),5000);QVERIFY2(vouchers.cards()[0].toMap()["provisionState"]=="CREATED",qPrintable(vouchers.cards()[0].toMap()["provisionMessage"].toString()));QCOMPARE(adds,1);QVERIFY(!prematureEnable);QVERIFY(verifiedExpiry);QCOMPARE(user["disabled"].toString(),QString("no"));QVERIFY(vouchers.previewCard(0).startsWith("data:image/png;base64,"));}
 void portableBackup(){QFile file(":/tests/backup-vector.hex");QVERIFY(file.open(QIODevice::ReadOnly));auto fixture=QByteArray::fromHex(file.readAll());auto clear=Vault::decrypt(fixture,QString::fromUtf8("Arabic-كلمة-123"));QCOMPARE(clear,QByteArray("{\"format\":\"FG-MTM-vouchers\",\"schema\":1,\"batches\":[]}"));auto cipher=Vault::encrypt(clear,"long-password-123");QCOMPARE(Vault::decrypt(cipher,"long-password-123"),clear);QVERIFY_EXCEPTION_THROWN(Vault::decrypt(cipher,"wrong-password-123"),std::runtime_error);cipher[40]=char(cipher[40]^1);QVERIFY_EXCEPTION_THROWN(Vault::decrypt(cipher,"long-password-123"),std::runtime_error);QCOMPARE(Vault::unprotect(Vault::protect(clear)),clear);}
#endif
};
QTEST_MAIN(VoucherTests)
#include "test_vouchers.moc"
