#include <QtTest>
#include <QTcpServer>
#include <QTcpSocket>
#include "RouterClient.hpp"
class RouterTests:public QObject{Q_OBJECT
private slots:
 void framing(){for(quint32 n:{0u,127u,128u,16383u,16384u,2097151u,2097152u}){QByteArray b=RouterCodec::length(n)+QByteArray(n,'a')+QByteArray(1,'\0');QStringList words;QCOMPARE(RouterCodec::takeSentence(b,words),1);QVERIFY(b.isEmpty());if(n)QCOMPARE(words.first().size(),qsizetype(n));}QByteArray partial=RouterCodec::sentence({"!re","=name=مستخدم"});auto saved=partial;partial.chop(1);QStringList words;QCOMPARE(RouterCodec::takeSentence(partial,words),0);QCOMPARE(partial,saved.left(saved.size()-1));partial.append('\0');QCOMPARE(RouterCodec::takeSentence(partial,words),1);QCOMPARE(words[1],QString("=name=مستخدم"));QByteArray invalid(1,char(0xff));QCOMPARE(RouterCodec::takeSentence(invalid,words),-1);}
 void parser(){auto c=RouterCodec::parse("/ip hotspot user set *A comment=\"hello world\" disabled=no");QVERIFY(c.valid());QCOMPARE(c.menu,QString("ip/hotspot/user"));QCOMPARE(c.selector,QString("*A"));QCOMPARE(c.attributes["comment"].toString(),QString("hello world"));QVERIFY(!RouterCodec::parse("/ip hotspot user remove [find]").valid());QVERIFY(!RouterCodec::parse("/ip hotspot user add name=x; /system reboot").valid());QVERIFY(!RouterCodec::parse("/ip dns set servers=\"broken").valid());QCOMPARE(RouterCodec::parse("/interface disable ether1").risk,QString("DANGEROUS"));QCOMPARE(RouterCodec::parse("/ip/hotspot/user print").risk,QString("READ"));}
 void lostMutationNotRepeated(){QTcpServer server;QVERIFY(server.listen(QHostAddress::LocalHost));int mutations=0,logins=0;QByteArray buffer;connect(&server,&QTcpServer::newConnection,this,[&]{auto peer=server.nextPendingConnection();connect(peer,&QTcpSocket::readyRead,this,[&,peer]{buffer+=peer->readAll();QStringList words;while(RouterCodec::takeSentence(buffer,words)==1){if(words.first()=="/login"){logins++;peer->write(RouterCodec::sentence({"!done"}));}else if(words.first()=="/ip/hotspot/user/add"){mutations++;peer->disconnectFromHost();}}});});RouterClient client;client.configure("127.0.0.1",server.serverPort(),"admin","pw","API");bool done=false;RouterReply result;client.execute("ip/hotspot/user","add",{{"name","test"}},[&](RouterReply r){result=r;done=true;});QTRY_VERIFY_WITH_TIMEOUT(done,5000);QVERIFY(!result.ok());QVERIFY(result.uncertain);QCOMPARE(mutations,1);QCOMPARE(logins,1);QVERIFY(!client.busy());}
 void apiRowsAndTrap(){QTcpServer server;QVERIFY(server.listen(QHostAddress::LocalHost));QByteArray buffer;connect(&server,&QTcpServer::newConnection,this,[&]{auto peer=server.nextPendingConnection();connect(peer,&QTcpSocket::readyRead,this,[&,peer]{buffer+=peer->readAll();QStringList words;while(RouterCodec::takeSentence(buffer,words)==1){if(words.first()=="/login")peer->write(RouterCodec::sentence({"!done"}));else if(words.first().endsWith("/print"))peer->write(RouterCodec::sentence({"!re","=.id=*1","=name=ether1"})+RouterCodec::sentence({"!done"}));else peer->write(RouterCodec::sentence({"!trap","=message=not permitted"})+RouterCodec::sentence({"!done"}));}});});RouterClient client;client.configure("127.0.0.1",server.serverPort(),"admin","pw","API");bool done=false;RouterReply result;client.read("interface",[&](RouterReply r){result=r;done=true;});QTRY_VERIFY_WITH_TIMEOUT(done,5000);QVERIFY(result.ok());QCOMPARE(result.rows.first().toObject()["name"].toString(),QString("ether1"));done=false;client.execute("interface","disable",{{".id","*1"}},[&](RouterReply r){result=r;done=true;});QTRY_VERIFY_WITH_TIMEOUT(done,5000);QVERIFY(!result.ok());QVERIFY(!result.uncertain);QCOMPARE(result.error,QString("not permitted"));}
};
QTEST_GUILESS_MAIN(RouterTests)
#include "test_router.moc"
