#include <QtTest>
#include "RouterTools.hpp"
class ToolTests:public QObject{Q_OBJECT
 QJsonObject fixture(){return {{"interface",QJsonArray{QJsonObject{{"name","ether1"},{"type","ether"},{"running","yes"}},QJsonObject{{"name","ether2"},{"type","ether"},{"running","yes"}},QJsonObject{{"name","ether3"},{"type","ether"},{"running","no"}}}},{"ip/route",QJsonArray{QJsonObject{{"dst-address","0.0.0.0/0"},{"active","yes"},{"immediate-gw","192.168.1.1%ether1"}}}},{"ip/dns",QJsonArray{QJsonObject{{"servers",""},{"allow-remote-requests","no"}}}}};}
private slots:
 void hotspotPreservesWan(){auto f=fixture();QJsonObject request{{"interface","ether2"},{"gateway","192.168.10.1/24"},{"network","192.168.10.0/24"},{"pool","192.168.10.10-192.168.10.250"},{"dnsName","wifi.local"}};auto plan=RouterTools::hotspotPlan(f,request,"192.168.1.2");QVERIFY(plan["changes"].toArray().size()>5);for(auto v:plan["changes"].toArray()){auto step=v.toObject();auto attrs=step["attributes"].toObject();QVERIFY(attrs["interface"]!="ether1");if(step["menu"]=="ip/dns")QVERIFY(!attrs.contains("allow-remote-requests"));}request["interface"]="ether1";QVERIFY_EXCEPTION_THROWN(RouterTools::hotspotPlan(f,request,"192.168.1.2"),std::runtime_error);request["interface"]="ether2";request["pool"]="192.168.10.1-192.168.10.200";QVERIFY_EXCEPTION_THROWN(RouterTools::hotspotPlan(f,request,"192.168.1.2"),std::runtime_error);}
 void overlapRejected(){auto f=fixture();f["ip/address"]=QJsonArray{QJsonObject{{"interface","ether3"},{"address","192.168.10.1/24"}}};QVERIFY_EXCEPTION_THROWN(RouterTools::hotspotPlan(f,{{"interface","ether2"},{"gateway","192.168.10.1/24"},{"network","192.168.10.0/24"},{"pool","192.168.10.10-192.168.10.250"}},"192.168.1.2"),std::runtime_error);}
 void portsExcludeWanAndOccupied(){auto f=fixture();f["ip/dhcp-client"]=QJsonArray{QJsonObject{{"interface","ether1"}}};auto plan=RouterTools::portsPlan(f,"ether2","ether1","192.168.1.2");for(auto value:plan["changes"].toArray()){auto step=value.toObject();QVERIFY(step["attributes"].toObject()["interface"]!="ether1");}f["ip/firewall/filter"]=QJsonArray{QJsonObject{{"in-interface","ether2"}}};QVERIFY_EXCEPTION_THROWN(RouterTools::portsPlan(f,"ether2","ether1","192.168.1.2"),std::runtime_error);}
 void dnsPrivateOnly(){QVERIFY(RouterTools::privateSubnet("10.0.0.0/8"));QVERIFY(RouterTools::privateSubnet("172.16.0.0/12"));QVERIFY(RouterTools::privateSubnet("192.168.10.0/24"));QVERIFY(RouterTools::privateSubnet("100.64.0.0/10"));QVERIFY(!RouterTools::privateSubnet("8.8.8.0/24"));QVERIFY(!RouterTools::privateSubnet("192.168.10.1/24"));auto f=fixture();f["ip/dhcp-server/network"]=QJsonArray{QJsonObject{{".id","*1"},{"address","192.168.10.0/24"},{"dns-server","192.168.10.1"}}};auto plan=RouterTools::dnsPlan(f,{"*1"},"FAMILY");for(auto v:plan["changes"].toArray())QVERIFY(!v.toObject()["attributes"].toObject().contains("allow-remote-requests"));f["ip/dhcp-server/network"]=QJsonArray{QJsonObject{{".id","*1"},{"address","8.8.8.0/24"}}};QVERIFY_EXCEPTION_THROWN(RouterTools::dnsPlan(f,{"*1"},"FAMILY"),std::runtime_error);}
 void portalEscapes(){auto assets=RouterTools::renderPortal({{"networkName","<script>alert(1)</script>"},{"color","#159DFF"},{"website","javascript:alert(1)"}});QVERIFY(!assets["login.html"].toString().contains("<script>alert(1)</script>"));QVERIFY(assets["login.html"].toString().contains("&lt;script&gt;"));QVERIFY(!assets["login.html"].toString().contains("javascript:alert"));QVERIFY_EXCEPTION_THROWN(RouterTools::renderPortal({{"color","red;display:none"}}),std::runtime_error);}
};
QTEST_MAIN(ToolTests)
#include "test_tools.moc"
