#include <QtTest>
#include <QTemporaryDir>
#include "Business.hpp"
#include "BusinessCsv.hpp"
#include <QFile>
#include <QDate>
class BusinessTests:public QObject{Q_OBJECT
private slots:
 void moneyExact(){QCOMPARE(Business::money("٠١٢٫٣٤"),qint64(1234));QCOMPARE(Business::money("9999999999.99"),qint64(999999999999LL));QVERIFY_EXCEPTION_THROWN(Business::money("10000000000.00"),std::runtime_error);QVERIFY_EXCEPTION_THROWN(Business::money("1.001"),std::runtime_error);QVERIFY_EXCEPTION_THROWN(Business::money("0"),std::runtime_error);QVERIFY_EXCEPTION_THROWN(Business::money("-5"),std::runtime_error);}
 void renewalAtomicAndReplayed(){Business b(":memory:");QVERIFY(!b.perform("subscriber",{{"id","sub"},{"name","Customer"},{"service","HOTSPOT"},{"currency","EGP"}}).isEmpty());QVERIFY(!b.perform("plan",{{"id","plan"},{"name","30 days"},{"service","HOTSPOT"},{"currency","EGP"},{"price","10.00"},{"days",30}}).isEmpty());QJsonObject fields{{"id","invoice1"},{"subscriber_id","sub"},{"plan_id","plan"},{"paid","5.25"},{"method","INSTAPAY"},{"reference","ref-001"}};QVERIFY(!b.perform("renew",fields).isEmpty());QVERIFY(!b.perform("renew",fields).isEmpty());b.browse("invoices");QCOMPARE(b.rows().size(),1);b.browse("ledger");QCOMPARE(b.rows().size(),2);fields["paid"]="6.00";QVERIFY(b.perform("renew",fields).isEmpty());b.browse("ledger");QCOMPARE(b.rows().size(),2);QVERIFY(b.perform("reverse",{{"target_id","invoice1:c"},{"reason","must void invoice"}}).isEmpty());QVERIFY(!b.perform("void_invoice",{{"id","void1"},{"target_id","invoice1"},{"reason","Cancelled"}}).isEmpty());QVERIFY(!b.perform("void_invoice",{{"id","void1"},{"target_id","invoice1"},{"reason","Cancelled"}}).isEmpty());b.browse("ledger");qint64 balance=0;for(auto r:b.rows())balance+=r.toMap()["amount_minor"].toString().toLongLong();QCOMPARE(balance,qint64(0));QCOMPARE(b.rows().size(),4);}
 void walletCannotOverdraw(){Business b(":memory:");QVERIFY(!b.perform("team",{{"id","dealer"},{"name","Reseller"},{"role","RESELLER"},{"currency","EGP"},{"commission_bps",500}}).isEmpty());QVERIFY(!b.perform("wallet",{{"id","deposit"},{"member_id","dealer"},{"kind","DEPOSIT"},{"amount","25.50"},{"note","Fund"}}).isEmpty());QVERIFY(b.perform("wallet",{{"id","overdraft"},{"member_id","dealer"},{"kind","WITHDRAWAL"},{"amount","25.51"},{"note","No"}}).isEmpty());b.browse("reseller_entries");QCOMPARE(b.rows().size(),1);QVERIFY(!b.perform("wallet",{{"id","withdraw"},{"member_id","dealer"},{"kind","WITHDRAWAL"},{"amount","5.50"},{"note","Withdraw"}}).isEmpty());b.browse("reseller_entries");QCOMPARE(b.rows().size(),2);}
 void salesAndReplicaConflict(){Business a(":memory:");auto id=a.perform("subscriber",{{"id","sub"},{"name","Customer"},{"service","OTHER"},{"currency","EGP"}});QVERIFY(!id.isEmpty());QJsonArray lines{QJsonObject{{"name","Router"},{"quantity",2},{"unitPrice","10.25"}}};QVERIFY(!a.perform("sale",{{"id","sale"},{"subscriber_id","sub"},{"lines",lines},{"paid","20.50"},{"method","CASH"}}).isEmpty());auto remote=a.snapshot();auto bad=remote;for(int i=0;i<bad.size();i++){auto r=bad[i].toObject();if(r["table"]=="sales"){auto body=r["body"].toObject();body["amount_minor"]=3000;r["body"]=body;bad[i]=r;}}QVERIFY_EXCEPTION_THROWN(a.combine(bad,"https://server"),std::runtime_error);a.browse("sales");QCOMPARE(a.rows().first().toMap()["amount_minor"].toString(),QString("2050"));QVERIFY(!a.perform("void_sale",{{"id","void"},{"target_id","sale"},{"reason","Return"}}).isEmpty());a.browse("ledger");qint64 balance=0;for(auto r:a.rows())balance+=r.toMap()["amount_minor"].toString().toLongLong();QCOMPARE(balance,qint64(0));}
 void csvStrictAndQuoted(){auto rows=BusinessCsv::parse("name,phone,service,account,currency\r\n\"A, B\",,HOTSPOT,user,EGP\r\n");QCOMPARE(rows.size(),2);QCOMPARE(rows[1][0],QString("A, B"));QVERIFY_EXCEPTION_THROWN(BusinessCsv::parse("\"unclosed"),std::runtime_error);QVERIFY_EXCEPTION_THROWN(BusinessCsv::parse("\"a\"tail"),std::runtime_error);QCOMPARE(BusinessCsv::stableId("hello"),QString("5d41402a-bc4b-3a76-b971-9d911017c592"));QVERIFY(BusinessCsv::line({"=1","-123"},{1}).startsWith("\"'=1\",\"-123\""));}
 void importRevalidatedAndReplayed(){Business b(":memory:");QTemporaryDir d;auto path=d.path()+"/subs.csv";QFile f(path);QVERIFY(f.open(QIODevice::WriteOnly));f.write("name,phone,service,account,currency\r\nA,,HOTSPOT,user,EGP\r\nB,,PPPOE,ppp,USD\r\n");f.close();b.previewImport(QUrl::fromLocalFile(path));QCOMPARE(b.importRows().size(),2);b.importSubscribers();b.browse("subscribers");QCOMPARE(b.rows().size(),2);b.previewImport(QUrl::fromLocalFile(path));QCOMPARE(b.importRows().size(),0);QVERIFY(b.status().contains("EXISTING_ACCOUNT"));}
 void importConflictIsAtomic(){Business b(":memory:");QTemporaryDir d;auto path=d.path()+"/subs.csv";QFile f(path);QVERIFY(f.open(QIODevice::WriteOnly));f.write("name,phone,service,account,currency\nA,,HOTSPOT,user,EGP\nB,,PPPOE,ppp,USD\n");f.close();b.previewImport(QUrl::fromLocalFile(path));QCOMPARE(b.importRows().size(),2);QVERIFY(!b.perform("subscriber",{{"id","other"},{"name","Existing"},{"service","PPPOE"},{"account","ppp"},{"currency","USD"}}).isEmpty());b.importSubscribers();b.browse("subscribers");QCOMPARE(b.rows().size(),1);}
 void reportsCountReversals(){Business b(":memory:");b.perform("subscriber",{{"id","sub"},{"name","Customer"},{"service","OTHER"},{"currency","EGP"}});b.perform("charge",{{"id","charge"},{"subscriber_id","sub"},{"amount","12.34"},{"note","Charge"}});b.perform("payment",{{"id","payment"},{"subscriber_id","sub"},{"amount","2.34"},{"method","CASH"},{"reference","R1"}});b.perform("reverse",{{"id","reverse"},{"target_id","payment"},{"reason","Refund"}});auto day=QDate::currentDate().toString("yyyy-MM-dd");b.report(day,day);QCOMPARE(b.reports().size(),6);auto row=b.reports()[0].toMap();QCOMPARE(row["charges_minor"].toString(),QString("1234"));QCOMPARE(row["payments_minor"].toString(),QString("0"));QCOMPARE(row["balance_minor"].toString(),QString("1234"));}
#ifdef Q_OS_WIN
 void resellerSeesOnlyOwnWallet(){Business b(":memory:");b.enroll("owner-password-123");b.perform("team",{{"id","own"},{"name","Own"},{"role","RESELLER"},{"currency","EGP"}});b.perform("team",{{"id","other"},{"name","Other"},{"role","RESELLER"},{"currency","EGP"}});b.perform("wallet",{{"member_id","own"},{"kind","DEPOSIT"},{"amount","12.34"},{"note","Fund"}});b.perform("create_account",{{"username","dealer"},{"member_id","own"},{"password","dealer-password-123"}});b.lock();b.login("dealer","dealer-password-123");QCOMPARE(b.role(),QString("RESELLER"));QCOMPARE(b.resellerWallet()["balance_minor"].toString(),QString("1234"));QVERIFY(b.resellerWallet("other").isEmpty());QVERIFY(!b.allowed("TEAM"));QVERIFY(!b.allowed("WALLET"));}
 void rolesEnforced(){Business b(":memory:");b.enroll("owner-password-123");QCOMPARE(b.role(),QString("OWNER"));auto m=b.perform("team",{{"id","cashier"},{"name","Cashier"},{"role","CASHIER"},{"currency","EGP"}});QVERIFY(!m.isEmpty());QVERIFY(!b.perform("create_account",{{"username","cashier"},{"member_id","cashier"},{"password","cashier-password-123"}}).isEmpty());b.lock();QVERIFY(!b.allowed("POST"));b.login("cashier","cashier-password-123");QCOMPARE(b.role(),QString("CASHIER"));QVERIFY(b.allowed("POST"));QVERIFY(!b.allowed("AUTH"));QVERIFY(b.perform("expense",{{"amount","5"},{"currency","EGP"},{"category","Test"},{"note","Rejected"}}).isEmpty());b.login("owner","owner-password-123");QVERIFY(!b.perform("team_disable",{{"target_id","cashier"}}).isEmpty());b.login("cashier","cashier-password-123");QVERIFY(!b.allowed("POST"));}
#endif
};
QTEST_MAIN(BusinessTests)
#include "test_business.moc"
