#include "ApReport.hpp"
#include <QSaveFile>
#include <QXmlStreamWriter>
#include <QTextDocument>
#include <QPdfWriter>
#include <QDateTime>
#include <QJsonObject>
#include <QSet>
#include <QBuffer>
namespace {
void u16(QByteArray& b,quint16 v){b.append(char(v));b.append(char(v>>8));}
void u32(QByteArray& b,quint32 v){u16(b,v&65535);u16(b,v>>16);}
quint32 crc(const QByteArray& b){quint32 c=0xffffffff;for(unsigned char v:b){c^=v;for(int k=0;k<8;k++)c=(c>>1)^(0xedb88320U & (0U-(c&1)));}return c^0xffffffff;}
QByteArray zip(const QMap<QString,QByteArray>& files){QByteArray data,central;for(auto it=files.begin();it!=files.end();++it){auto name=it.key().toUtf8(),body=it.value();quint32 offset=data.size(),sum=crc(body);u32(data,0x04034b50);u16(data,20);u16(data,0);u16(data,0);u16(data,0);u16(data,0x21);u32(data,sum);u32(data,body.size());u32(data,body.size());u16(data,name.size());u16(data,0);data+=name;data+=body;u32(central,0x02014b50);u16(central,20);u16(central,20);u16(central,0);u16(central,0);u16(central,0);u16(central,0x21);u32(central,sum);u32(central,body.size());u32(central,body.size());u16(central,name.size());u16(central,0);u16(central,0);u16(central,0);u16(central,0);u32(central,0);u32(central,offset);central+=name;}auto offset=data.size();data+=central;u32(data,0x06054b50);u16(data,0);u16(data,0);u16(data,files.size());u16(data,files.size());u32(data,central.size());u32(data,offset);u16(data,0);return data;}
QString col(int n){QString result;do{result.prepend(QChar('A'+n%26));n=n/26-1;}while(n>=0);return result;}
QByteArray sheet(QJsonArray rows){QSet<QString> set;for(auto v:rows)for(auto k:v.toObject().keys())set.insert(k);auto columns=set.values();columns.sort();QByteArray out;QXmlStreamWriter w(&out);w.writeStartDocument();w.writeStartElement("worksheet");w.writeDefaultNamespace("http://schemas.openxmlformats.org/spreadsheetml/2006/main");w.writeStartElement("sheetViews");w.writeStartElement("sheetView");w.writeAttribute("workbookViewId","0");w.writeStartElement("pane");w.writeAttribute("ySplit","1");w.writeAttribute("topLeftCell","A2");w.writeAttribute("state","frozen");w.writeEndElement();w.writeEndElement();w.writeEndElement();w.writeStartElement("sheetData");for(int r=0;r<=rows.size();r++){w.writeStartElement("row");w.writeAttribute("r",QString::number(r+1));for(int c=0;c<columns.size();c++){w.writeStartElement("c");w.writeAttribute("r",col(c)+QString::number(r+1));w.writeAttribute("t","inlineStr");w.writeAttribute("s",r==0?"1":"0");w.writeStartElement("is");w.writeTextElement("t",r==0?columns[c]:rows[r-1].toObject()[columns[c]].toVariant().toString());w.writeEndElement();w.writeEndElement();}w.writeEndElement();}w.writeEndElement();if(!columns.isEmpty()){w.writeStartElement("autoFilter");w.writeAttribute("ref","A1:"+col(columns.size()-1)+QString::number(rows.size()+1));w.writeEndElement();}w.writeEndElement();w.writeEndDocument();return out;}
}
bool ApReport::xlsx(QString path,const QJsonArray& summary,const QJsonArray& observations){
 auto note=[](QString reason){return QJsonArray{QJsonObject{{"availability","N/A"},{"reason",reason}}};};QJsonArray devices,sessions;for(auto v:observations){if(v.toObject()["kind"]=="device")devices.append(v);if(v.toObject()["kind"]=="session")sessions.append(v);}
 const QStringList names{"Summary","Access Points","Sessions","Cards","Sales","Traffic","Peak Hours"};QList<QJsonArray> sheets{summary,devices,sessions,note("No verified voucher usage correlation"),note("No verified sales attribution"),sessions,note("Polling observations are not a complete usage history")};QMap<QString,QByteArray> files;
 QString types="<?xml version=\"1.0\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/>";
 QString workbook="<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets>",rels="<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">";
 for(int i=0;i<names.size();i++){QString num=QString::number(i+1);files["xl/worksheets/sheet"+num+".xml"]=sheet(sheets[i]);types+="<Override PartName=\"/xl/worksheets/sheet"+num+".xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>";workbook+="<sheet name=\""+names[i]+"\" sheetId=\""+num+"\" r:id=\"rId"+num+"\"/>";rels+="<Relationship Id=\"rId"+num+"\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet"+num+".xml\"/>";}
 files["[Content_Types].xml"]=(types+"</Types>").toUtf8();files["xl/workbook.xml"]=(workbook+"</sheets></workbook>").toUtf8();files["xl/_rels/workbook.xml.rels"]=(rels+"<Relationship Id=\"styles\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>").toUtf8();files["_rels/.rels"]="<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>";
 files["xl/styles.xml"]="<?xml version=\"1.0\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Calibri\"/></font><font><b/><color rgb=\"FFFFFFFF\"/><sz val=\"11\"/><name val=\"Calibri\"/></font></fonts><fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF12344A\"/><bgColor indexed=\"64\"/></patternFill></fill></fills><borders count=\"1\"><border/></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"2\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"1\" fillId=\"2\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\"/></cellXfs></styleSheet>";
 QSaveFile f(path);auto data=zip(files);return f.open(QIODevice::WriteOnly)&&f.write(data)==data.size()&&f.commit();
}
bool ApReport::pdf(QString path,const QJsonArray& summary,QString period){QSaveFile file(path);if(!file.open(QIODevice::WriteOnly))return false;{QPdfWriter writer(&file);writer.setPageSize(QPageSize(QPageSize::A4));writer.setTitle("FG MTM — Access Point Observations");writer.setCreator("FG Machines");QTextDocument doc;QString html="<h1>FG MTM · FG Machines</h1><h2>Access Point Observations / تقرير نقاط الوصول</h2><p>"+period.toHtmlEscaped()+"</p><p>Generated: "+QDateTime::currentDateTime().toString(Qt::ISODate)+"</p><p>Sampled local observations. Client attribution is inferred. Not a complete session or sales ledger.</p><table border='1' cellspacing='0' cellpadding='6'><tr><th>Shop / AP</th><th>MAC</th><th>Observed clients</th><th>Accounts</th></tr>";for(auto v:summary){auto r=v.toObject();html+="<tr><td>"+(r["shop"].toString().isEmpty()?r["name"].toString():r["shop"].toString()).toHtmlEscaped()+"</td><td>"+r["mac"].toString().toHtmlEscaped()+"</td><td>"+r["observedClients"].toVariant().toString()+"</td><td>"+r["observedAccounts"].toVariant().toString()+"</td></tr>";}doc.setHtml(html+"</table><p>Cards / sales / period traffic: N/A — no verified attribution.</p>");doc.print(&writer);}return file.commit();}
