#include "Business.hpp"
#include "Vault.hpp"
#include "Protocol.hpp"
#include <QSqlQuery>
#include <QSqlRecord>
#include <QSqlError>
#include <QFile>
#include <QSaveFile>
#include <QStandardPaths>
#include <QDir>
#include <QUuid>
#include <QDateTime>
#include <QRegularExpression>
#include <QJsonDocument>
#include <QRandomGenerator>
#include <QCryptographicHash>
#include <QTextDocument>
#include <QPdfWriter>
#include <QPainter>
#include <QPageSize>
#include <stdexcept>
#include <algorithm>
#include <QMap>
#include <QTimer>
namespace {
void check(bool ok,QString error){if(!ok)throw std::runtime_error(error.toStdString());}
QString str(QJsonObject o,QString k,QString fallback={}){return o[k].toString(fallback);}
QString clean(QString text,int max,bool required=false){text=text.trimmed();check(text.size()<=max&&(!required||!text.isEmpty()),"INVALID_TEXT");for(auto c:text)check(c=='\n'||!c.isNull()&&c.category()!=QChar::Other_Control,"INVALID_TEXT");return text;}
QString uuid(){return QUuid::createUuid().toString(QUuid::WithoutBraces);}
QByteArray salt(){QByteArray b(16,'\0');for(int i=0;i<16;i++)b[i]=char(QRandomGenerator::system()->bounded(256));return b;}
QJsonObject row(QSqlQuery &q){QJsonObject o;auto r=q.record();for(int i=0;i<r.count();i++){auto v=q.value(i);o[r.fieldName(i)]=v.isNull()?QJsonValue::Null:QJsonValue::fromVariant(v);}return o;}
QByteArray canonical(QJsonObject object){return QJsonDocument(object).toJson(QJsonDocument::Compact);}
QSet<QString> audited(){return {"subscribers","ledger","plans","invoices","invoice_voids","expenses","import_batches","router_bindings","network_jobs","sales","sale_voids","team_members","reseller_entries"};}
void saveFile(QString path,QByteArray bytes){QSaveFile f(path);check(f.open(QIODevice::WriteOnly)&&f.write(bytes)==bytes.size()&&f.commit(),"FILE_WRITE_FAILED");}
}
Business::Business(QString file,QObject*p):QObject(p){connection=uuid();db=QSqlDatabase::addDatabase("QSQLITE",connection);if(file.isEmpty()){auto dir=QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation);QDir().mkpath(dir);file=dir+"/business.db";}db.setDatabaseName(file);check(db.open(),db.lastError().text());sql("PRAGMA foreign_keys=ON");sql("PRAGMA busy_timeout=5000");sql("PRAGMA journal_mode=WAL");auto version=sql("PRAGMA user_version");version.next();if(version.value(0).toInt()==0){check(db.transaction(),"TRANSACTION_FAILED");try{QFile f(":/resources/business-schema.json");check(f.open(QIODevice::ReadOnly),"SCHEMA_MISSING");auto schema=QJsonDocument::fromJson(f.readAll()).object()["statements"].toArray();for(auto statement:schema)sql(statement.toString());organization=uuid();branch=uuid();sql("INSERT INTO audit_installation VALUES(1,?)",{uuid()});sql("INSERT INTO organizations VALUES(?,?)",{organization,"Local business"});sql("INSERT INTO branches VALUES(?,?,?)",{branch,organization,"Main branch"});sql("INSERT INTO settings VALUES(1,?,?)",{organization,branch});sql("PRAGMA user_version=7");check(db.commit(),"TRANSACTION_FAILED");}catch(...){db.rollback();throw;}}else check(version.value(0).toInt()==7,"DATABASE_VERSION_UNSUPPORTED");setScope();clock.start();auto timer=new QTimer(this);timer->setInterval(1000);connect(timer,&QTimer::timeout,this,[this]{if(!principal.isEmpty()&&session().isEmpty())lock();});timer->start();}
Business::~Business(){db.close();db=QSqlDatabase();QSqlDatabase::removeDatabase(connection);}
QSqlQuery Business::sql(QString text,QVariantList args)const{QSqlQuery q(db);check(q.prepare(text),q.lastError().text());for(auto a:args)q.addBindValue(a);check(q.exec(),q.lastError().text());return q;}
void Business::setScope(){auto q=sql("SELECT organization_id,branch_id FROM settings WHERE id=1");check(q.next(),"SCOPE_MISSING");organization=q.value(0).toString();branch=q.value(1).toString();}
bool Business::enrolled()const{auto q=sql("SELECT 1 FROM local_accounts WHERE owner=1");return q.next();}
QJsonObject Business::session()const{if(principal.isEmpty()||clock.elapsed()>=expiry)return {};auto q=sql("SELECT a.id,a.username,a.revision,a.member_id,a.organization_id,a.branch_id,CASE WHEN a.owner=1 THEN 'OWNER' ELSE m.role END AS role FROM local_accounts a LEFT JOIN team_members m ON m.id=a.member_id WHERE a.id=? AND (a.owner=1 OR m.active=1)",{str(principal,"id")});if(!q.next())return {};auto current=row(q);return current==principal?current:QJsonObject{};}
QString Business::role()const{return enrolled()?str(session(),"role"):"OWNER";}
QSet<QString> Business::permissions(QString r){QSet<QString> all{"READ","CUSTOMER","POST","REVERSE","CONFIGURE","IMPORT","EXPORT","TEAM","WALLET","ROUTER","VOUCHERS","BRANCHES","AUTH"};if(r=="OWNER")return all;if(r=="ADMIN"){all.remove("AUTH");return all;}if(r=="MANAGER"){for(auto p:{"AUTH","BRANCHES","VOUCHERS"})all.remove(p);return all;}if(r=="TECHNICIAN")return {"READ","CUSTOMER","IMPORT","ROUTER"};if(r=="CASHIER")return {"READ","CUSTOMER","POST"};if(r=="READ_ONLY")return {"READ"};return {};}
bool Business::allowed(QString permission)const{try{guard(permission);return true;}catch(...){return false;}}
void Business::guard(QString permission)const{if(!enrolled())return;auto p=session();check(!p.isEmpty(),"LOGIN_REQUIRED");check(permissions(str(p,"role")).contains(permission)&&str(p,"organization_id")==organization&&(QStringList{"OWNER","ADMIN"}.contains(str(p,"role"))||str(p,"branch_id")==branch),"ACCESS_DENIED");}
qint64 Business::money(QString input){input=input.trimmed();QString s;for(auto c:input){ushort u=c.unicode();if(u>=0x660&&u<=0x669)s+=QChar(ushort('0'+u-0x660));else if(u>=0x6f0&&u<=0x6f9)s+=QChar(ushort('0'+u-0x6f0));else if(u==0x66b)s+='.';else s+=c;}check(QRegularExpression("^[0-9]+(\\.[0-9]{1,2})?$").match(s).hasMatch(),"INVALID_AMOUNT");auto parts=s.split('.');bool ok;auto whole=parts[0].toLongLong(&ok);check(ok&&whole<=9999999999LL,"INVALID_AMOUNT");auto fraction=parts.size()>1?parts[1].leftJustified(2,'0').toInt():0;auto amount=whole*100+fraction;check(amount>=1&&amount<=999999999999LL,"INVALID_AMOUNT");return amount;}
QStringList Business::tables()const{return {"organizations","branches","subscribers","plans","ledger","invoices","invoice_voids","expenses","import_batches","payment_details","router_bindings","network_jobs","sales","sale_voids","team_members","reseller_entries","audit"};}
QJsonObject Business::one(QString table,QString id)const{check(tables().contains(table)||QStringList{"local_accounts","network_results"}.contains(table),"INVALID_TABLE");auto q=sql("SELECT * FROM "+table+" WHERE id=?",{id});return q.next()?row(q):QJsonObject{};}
QJsonObject Business::scoped(QString table,QString id)const{auto body=one(table,id);check(!body.isEmpty()&&str(body,"organization_id")==organization&&str(body,"branch_id")==branch,"SCOPE_MISMATCH");return body;}
QJsonObject Business::base(QString id)const{check(!id.isEmpty()&&id.size()<=80,"INVALID_ID");return {{"id",id},{"organization_id",organization},{"branch_id",branch},{"created_at",QDateTime::currentMSecsSinceEpoch()}};}
void Business::insert(QString table,QJsonObject body,bool replay){auto id=str(body,"id");if(replay&&!id.isEmpty()){auto old=one(table,id);if(!old.isEmpty()){for(auto k:body.keys())if(k!="created_at")check(old[k]==body[k],"IDEMPOTENCY_CONFLICT");return;}}QStringList keys=body.keys(),marks;QVariantList values;for(auto k:keys){check(QRegularExpression("^[a-z_]+$").match(k).hasMatch(),"INVALID_COLUMN");marks.append("?");auto v=body[k];values.append(v.isNull()?QVariant():v.toVariant());}sql("INSERT INTO "+table+" ("+keys.join(',')+") VALUES ("+marks.join(',')+")",values);}
void Business::posting(QString id,QString sub,QString kind,qint64 amount,QString note,QString method,QString reference,QString reversed){check(amount!=0&&amount>=-999999999999LL&&amount<=999999999999LL,"INVALID_AMOUNT");auto customer=scoped("subscribers",sub);auto b=base(id);b["subscriber_id"]=sub;b["kind"]=kind;b["amount_minor"]=amount;b["currency"]=customer["currency"];b["note"]=clean(note,500,true);b["reversal_of"]=reversed.isEmpty()?QJsonValue::Null:QJsonValue(reversed);insert("ledger",b);if(kind=="PAYMENT"){check(QStringList{"CASH","VODAFONE_CASH","INSTAPAY","BANK","OTHER"}.contains(method),"INVALID_PAYMENT_METHOD");auto q=sql("SELECT method,reference FROM payment_details WHERE ledger_id=?",{id});auto ref=clean(reference,120);if(q.next())check(q.value(0).toString()==method&&q.value(1).toString()==ref,"IDEMPOTENCY_CONFLICT");else sql("INSERT INTO payment_details VALUES(?,?,?)",{id,method,ref});}}
void Business::reversal(QString id,QString target,QString reason){auto old=scoped("ledger",target);check(old["reversal_of"].isNull(),"INVALID_REVERSAL");posting(id,str(old,"subscriber_id"),"REVERSAL",-old["amount_minor"].toInteger(),reason,"CASH","",target);}
QString Business::perform(QString op,QJsonObject fields){try{check(db.transaction(),"TRANSACTION_FAILED");auto id=apply(op,fields);check(db.commit(),"TRANSACTION_FAILED");message="تم حفظ العملية • Operation saved";emit changed();return id;}catch(const std::exception&e){db.rollback();message=e.what();emit changed();return {};}}
QString Business::apply(QString op,QJsonObject f){auto id=str(f,"id",uuid());auto sub=str(f,"subscriber_id");auto method=str(f,"method","CASH"),reference=str(f,"reference");sql("UPDATE audit_context SET actor=? WHERE id=1",{str(session(),"id","local-app")});
 if(op=="subscriber"){guard("CUSTOMER");auto b=base(id);for(auto k:{"name","phone","service","account","currency"})b[k]=clean(str(f,k),QString(k)=="name"?120:QString(k)=="phone"?40:120,QString(k)=="name");insert("subscribers",b);}
 else if(op=="plan"){guard("CONFIGURE");auto b=base(id);for(auto k:{"name","service","currency"})b[k]=clean(str(f,k),120,true);b["price_minor"]=money(str(f,"price"));b["days"]=f["days"].toInt();insert("plans",b);}
 else if(op=="charge"||op=="payment"){guard("POST");posting(id,sub,op=="charge"?"CHARGE":"PAYMENT",(op=="charge"?1:-1)*money(str(f,"amount")),str(f,"note"),method,reference);}
 else if(op=="reverse"){guard("REVERSE");reversal(id,str(f,"target_id"),clean(str(f,"reason"),500,true));}
 else if(op=="renew"){guard("POST");auto customer=scoped("subscribers",sub),plan=scoped("plans",str(f,"plan_id"));check(customer["currency"]==plan["currency"]&&customer["service"]==plan["service"],"PLAN_MISMATCH");auto paid=str(f,"paid","0")=="0"?0:money(str(f,"paid"));check(paid<=plan["price_minor"].toInteger(),"INVALID_AMOUNT");auto old=one("invoices",id);if(!old.isEmpty()){check(old["subscriber_id"]==sub&&old["plan_id"]==plan["id"]&&old["paid_minor"].toInteger()==paid,"IDEMPOTENCY_CONFLICT");if(paid)posting(id+":p",sub,"PAYMENT",-paid,"Invoice receipt / تحصيل فاتورة: "+id,method,reference);return id;}qint64 today=QDate(1970,1,1).daysTo(QDate::currentDate());auto q=sql("SELECT MAX(ends_day) FROM invoices i WHERE organization_id=? AND branch_id=? AND subscriber_id=? AND NOT EXISTS(SELECT 1 FROM invoice_voids v WHERE v.invoice_id=i.id)",{organization,branch,sub});q.next();auto start=std::max(today,q.value(0).toLongLong()),end=start+plan["days"].toInt();posting(id+":c",sub,"CHARGE",plan["price_minor"].toInteger(),"Subscription / اشتراك: "+str(plan,"name"));if(paid)posting(id+":p",sub,"PAYMENT",-paid,"Invoice receipt / تحصيل فاتورة: "+id,method,reference);auto b=base(id);b["subscriber_id"]=sub;b["plan_id"]=plan["id"];b["customer_name"]=customer["name"];b["plan_name"]=plan["name"];b["amount_minor"]=plan["price_minor"];b["currency"]=plan["currency"];b["days"]=plan["days"];b["starts_day"]=start;b["ends_day"]=end;b["paid_minor"]=paid;b["charge_id"]=id+":c";b["payment_id"]=paid?QJsonValue(id+":p"):QJsonValue::Null;insert("invoices",b);}
 else if(op=="sale"){guard("POST");auto customer=scoped("subscribers",sub);auto lines=f["lines"].toArray();check(lines.size()>=1&&lines.size()<=30,"INVALID_LINES");qint64 total=0;QJsonArray normalized;for(auto v:lines){auto line=v.toObject();int qty=line["quantity"].toInt();auto unit=money(str(line,"unitPrice"));check(qty>=1&&qty<=10000&&unit<=999999999999LL/qty,"INVALID_AMOUNT");auto amount=unit*qty;check(total<=999999999999LL-amount,"INVALID_AMOUNT");total+=amount;normalized.append(QJsonObject{{"name",clean(str(line,"name"),120,true)},{"quantity",qty},{"unitMinor",unit}});}auto paid=str(f,"paid","0")=="0"?0:money(str(f,"paid"));check(paid<=total,"INVALID_AMOUNT");auto json=QString::fromUtf8(QJsonDocument(normalized).toJson(QJsonDocument::Compact));auto b=base(id);b["subscriber_id"]=sub;b["customer"]=customer["name"];b["items_json"]=json;b["amount_minor"]=total;b["currency"]=customer["currency"];b["paid_minor"]=paid;b["charge_id"]=id+":c";b["payment_id"]=paid?QJsonValue(id+":p"):QJsonValue::Null;posting(id+":c",sub,"CHARGE",total,"Sale / بيع: "+id);if(paid)posting(id+":p",sub,"PAYMENT",-paid,"Sale receipt / تحصيل بيع: "+id,method,reference);insert("sales",b);}
 else if(op=="void_invoice"||op=="void_sale"){guard("REVERSE");auto target=str(f,"target_id"),reason=clean(str(f,"reason"),500,true);bool invoice=op=="void_invoice";auto old=scoped(invoice?"invoices":"sales",target);auto prior=one(invoice?"invoice_voids":"sale_voids",id);if(!prior.isEmpty()){check(prior[invoice?"invoice_id":"sale_id"]==target&&prior["reason"]==reason,"IDEMPOTENCY_CONFLICT");return id;}if(invoice){auto network=sql("SELECT (SELECT state FROM network_results WHERE job_id=j.id ORDER BY sequence DESC LIMIT 1) FROM network_jobs j WHERE invoice_id=?",{target});if(network.next())check(network.value(0).toString()=="SUSPENDED","NETWORK_INVOICE_LOCKED");auto last=sql("SELECT MAX(ends_day) FROM invoices i WHERE subscriber_id=? AND NOT EXISTS(SELECT 1 FROM invoice_voids v WHERE v.invoice_id=i.id)",{str(old,"subscriber_id")});last.next();check(last.value(0).toLongLong()==old["ends_day"].toInteger(),"CANCEL_LATEST_FIRST");}auto b=base(id);b[invoice?"invoice_id":"sale_id"]=target;b["reason"]=reason;insert(invoice?"invoice_voids":"sale_voids",b);reversal(id+":c",str(old,"charge_id"),reason);if(!old["payment_id"].isNull())reversal(id+":p",str(old,"payment_id"),reason);}
 else if(op=="expense"){guard("CONFIGURE");auto b=base(id);b["category"]=clean(str(f,"category"),80,true);b["amount_minor"]=money(str(f,"amount"));b["currency"]=str(f,"currency");b["note"]=clean(str(f,"note"),500,true);b["reversal_of"]=QJsonValue::Null;insert("expenses",b);}
 else if(op=="reverse_expense"){guard("REVERSE");auto target=str(f,"target_id");auto old=scoped("expenses",target);check(old["reversal_of"].isNull(),"INVALID_REVERSAL");auto b=base(id);b["category"]=old["category"];b["currency"]=old["currency"];b["amount_minor"]=-old["amount_minor"].toInteger();b["note"]=clean(str(f,"reason"),500,true);b["reversal_of"]=target;insert("expenses",b);}
 else if(op=="team"){guard("TEAM");auto b=base(id);b["name"]=clean(str(f,"name"),120,true);b["phone"]=clean(str(f,"phone"),40);b["role"]=str(f,"role");b["currency"]=str(f,"currency","EGP");b["commission_bps"]=f["commission_bps"].toInt();b["active"]=1;insert("team_members",b);}
 else if(op=="team_enable"||op=="team_disable"){guard("TEAM");auto target=str(f,"target_id");scoped("team_members",target);sql("UPDATE team_members SET active=? WHERE id=?",{op=="team_enable"?1:0,target});}
 else if(op=="wallet"){guard("WALLET");auto member=scoped("team_members",str(f,"member_id"));auto kind=str(f,"kind"),sale=str(f,"sale_id"),reversed=str(f,"reversal_of");qint64 amount=0;if(kind=="COMMISSION"){auto transaction=scoped("sales",sale);check(transaction["currency"]==member["currency"],"CURRENCY_MISMATCH");amount=transaction["paid_minor"].toInteger()*member["commission_bps"].toInteger()/10000;}else if(kind=="REVERSAL"){auto old=scoped("reseller_entries",reversed);check(old["member_id"]==member["id"]&&old["kind"]!="REVERSAL","INVALID_REVERSAL");amount=-old["amount_minor"].toInteger();}else{check(kind=="DEPOSIT"||kind=="WITHDRAWAL","INVALID_KIND");amount=money(str(f,"amount"))*(kind=="WITHDRAWAL"?-1:1);}auto b=base(id);b["member_id"]=member["id"];b["kind"]=kind;b["amount_minor"]=amount;b["note"]=clean(str(f,"note"),500,true);b["sale_id"]=sale.isEmpty()?QJsonValue::Null:QJsonValue(sale);b["reversal_of"]=reversed.isEmpty()?QJsonValue::Null:QJsonValue(reversed);insert("reseller_entries",b);auto balance=sql("SELECT SUM(amount_minor) FROM reseller_entries WHERE member_id=?",{str(member,"id")});balance.next();check(balance.value(0).toLongLong()<=999999999999LL,"INVALID_AMOUNT");}
 else if(op=="branch"){guard("BRANCHES");auto name=clean(str(f,"name"),120,true);auto old=one("branches",id);if(!old.isEmpty())check(old["name"]==name&&old["organization_id"]==organization,"IDEMPOTENCY_CONFLICT");else sql("INSERT INTO branches VALUES(?,?,?)",{id,organization,name});}
 else if(op=="select_branch"){auto target=str(f,"target_id");auto old=one("branches",target);check(old["organization_id"]==organization&&(QStringList{"OWNER","ADMIN"}.contains(role())||target==str(session(),"branch_id")),"ACCESS_DENIED");guard("READ");sql("UPDATE settings SET branch_id=? WHERE id=1",{target});branch=target;}
 else if(op=="create_account"||op=="reset_password"){guard("AUTH");check(enrolled(),"OWNER_NOT_CONFIGURED");auto pw=str(f,"password");check(pw.size()>=12&&pw.size()<=128,"PASSWORD_LENGTH");auto s=salt(),verifier=Vault::derive(pw,s);if(op=="create_account"){auto member=scoped("team_members",str(f,"member_id"));check(member["active"].toInt()==1,"INACTIVE_MEMBER");auto name=str(f,"username").trimmed().toLower();check(QRegularExpression("^[a-z0-9._-]{3,40}$").match(name).hasMatch(),"INVALID_USERNAME");sql("INSERT INTO local_accounts(id,username,organization_id,branch_id,member_id,owner,salt,verifier) VALUES(?,?,?,?,?,0,?,?)",{id,name,organization,branch,str(member,"id"),QString::fromLatin1(s.toBase64()),QString::fromLatin1(verifier.toBase64())});}else{auto target=str(f,"target_id");scoped("local_accounts",target);sql("UPDATE local_accounts SET salt=?,verifier=?,revision=revision+1 WHERE id=?",{QString::fromLatin1(s.toBase64()),QString::fromLatin1(verifier.toBase64()),target});}verifier.fill('\0');audit(id,op,str(session(),"id"));}
 else throw std::runtime_error("UNKNOWN_OPERATION");return id;
}
void Business::audit(QString id,QString action,QString actor){sql("INSERT INTO audit(organization_id,branch_id,entity,entity_id,action,actor,created_at) VALUES(?,?,'local_accounts',?,?,?,?)",{organization,branch,id,action,actor,QDateTime::currentMSecsSinceEpoch()});}
void Business::enroll(QString password){try{check(!enrolled(),"OWNER_EXISTS");check(password.size()>=12&&password.size()<=128,"PASSWORD_LENGTH");auto s=salt(),v=Vault::derive(password,s);auto id=uuid();check(db.transaction(),"TRANSACTION_FAILED");sql("INSERT INTO local_accounts(id,username,organization_id,branch_id,member_id,owner,salt,verifier) VALUES(?,'owner',?,?,NULL,1,?,?)",{id,organization,branch,QString::fromLatin1(s.toBase64()),QString::fromLatin1(v.toBase64())});v.fill('\0');audit(id,"OWNER_SETUP",id);check(db.commit(),"TRANSACTION_FAILED");login("owner",password);}catch(const std::exception&e){db.rollback();message=e.what();emit changed();}}
void Business::login(QString name,QString password){try{principal={};check(enrolled(),"OWNER_NOT_CONFIGURED");auto throttle=sql("SELECT failures,until_ms FROM login_throttle WHERE id=1");throttle.next();check(QDateTime::currentMSecsSinceEpoch()>=throttle.value(1).toLongLong(),"LOGIN_THROTTLED");auto q=sql("SELECT a.id,a.username,a.revision,a.member_id,a.organization_id,a.branch_id,CASE WHEN a.owner=1 THEN 'OWNER' ELSE m.role END AS role,a.salt,a.verifier FROM local_accounts a LEFT JOIN team_members m ON m.id=a.member_id WHERE a.username=? AND (a.owner=1 OR m.active=1)",{name.trimmed().toLower()});auto user=q.next()?row(q):QJsonObject{};auto s=user.isEmpty()?QByteArray(16,'\0'):QByteArray::fromBase64(str(user,"salt").toLatin1());auto expected=user.isEmpty()?QByteArray(32,'\0'):QByteArray::fromBase64(str(user,"verifier").toLatin1());auto computed=Vault::derive(password.left(128),s);unsigned diff=unsigned(computed.size()^expected.size());for(int i=0;i<std::min(computed.size(),expected.size());i++)diff|=quint8(computed[i])^quint8(expected[i]);computed.fill('\0');expected.fill('\0');if(diff||user.isEmpty()||password.size()>128){int failures=throttle.value(1).toLongLong()>0?1:throttle.value(0).toInt()+1;sql("UPDATE login_throttle SET failures=?,until_ms=? WHERE id=1",{failures,failures>=5?QDateTime::currentMSecsSinceEpoch()+30000:0});throw std::runtime_error("INVALID_LOGIN");}sql("UPDATE login_throttle SET failures=0,until_ms=0 WHERE id=1");user.remove("salt");user.remove("verifier");principal=user;expiry=clock.elapsed()+900000;branch=str(user,"branch_id");sql("UPDATE settings SET branch_id=? WHERE id=1",{branch});audit(str(user,"id"),"LOGIN",str(user,"id"));message="تم الدخول المحلي • Local login successful";}catch(const std::exception&e){message=e.what();}emit changed();}
void Business::lock(){principal={};view.clear();message="قُفلت مساحة الأعمال • Business workspace locked";emit changed();}
void Business::browse(QString table,QString query,int page){try{guard("READ");check(tables().contains(table)&&page>=0,"INVALID_TABLE");if(table=="team_members"||table=="reseller_entries")guard("TEAM");QString condition=table=="organizations"?"id=?":table=="branches"?"organization_id=?":"organization_id=? AND branch_id=?";QVariantList args=table=="organizations"||table=="branches"?QVariantList{organization}:QVariantList{organization,branch};QString source=table;if(table=="payment_details"){source="payment_details p JOIN ledger l ON l.id=p.ledger_id";condition="l.organization_id=? AND l.branch_id=?";}auto q=sql("SELECT "+QString(table=="payment_details"?"p.*":"*")+" FROM "+source+" WHERE "+condition+QString(table=="payment_details"?" ORDER BY p.rowid DESC":" ORDER BY rowid DESC"),args);view.clear();int matched=0;while(q.next()){auto o=row(q);if(!QString::fromUtf8(canonical(o)).contains(query,Qt::CaseInsensitive))continue;if(matched>=page*50&&matched<(page+1)*50){QVariantMap display;for(auto k:o.keys())display[k]=Protocol::jsonText(o[k]);view.append(display);}matched++;}message=QString("%1 نتيجة • %1 results").arg(matched);}catch(const std::exception&e){view.clear();message=e.what();}emit changed();}
QString Business::device()const{auto q=sql("SELECT device FROM audit_installation WHERE id=1");q.next();return q.value(0).toString();}
QJsonArray Business::snapshot(){guard("BRANCHES");QJsonArray result;for(auto table:tables()){QString text;QVariantList args;if(table=="organizations"){text="SELECT * FROM organizations WHERE id=?";args={organization};}else if(table=="branches"){text="SELECT * FROM branches WHERE id=? AND organization_id=?";args={branch,organization};}else if(table=="payment_details"){text="SELECT p.* FROM payment_details p JOIN ledger l ON l.id=p.ledger_id WHERE l.organization_id=? AND l.branch_id=?";args={organization,branch};}else{text="SELECT * FROM "+table+" WHERE organization_id=? AND branch_id=? ORDER BY rowid";args={organization,branch};}auto q=sql(text,args);while(q.next()){auto body=row(q);auto sequence=body["sequence"].toInteger();body.remove("sequence");QString id=table=="payment_details"?str(body,"ledger_id"):str(body,"id");if(table=="audit"){auto known=sql("SELECT external_id FROM cloud_audit_ids WHERE sequence=?",{sequence});if(known.next())id=known.value(0).toString();else{id="audit-"+device()+"-"+QString::number(sequence);sql("INSERT INTO cloud_audit_ids VALUES(?,?)",{sequence,id});}auto d=sql("SELECT device,before_value,after_value FROM audit_details WHERE sequence=?",{sequence});body["detail"]=d.next()?QJsonValue(row(d)):QJsonValue::Null;}result.append(QJsonObject{{"table",table},{"id",id},{"body",body}});}}check(result.size()<=50000&&QJsonDocument(result).toJson(QJsonDocument::Compact).size()<=20*1024*1024,"CLOUD_LIMIT");return result;}
QJsonArray Business::combine(QJsonArray remote,QString origin){guard("BRANCHES");QMap<QString,QJsonObject> merged;auto index=[&](QJsonArray rows,bool own){check(rows.size()<=50000,"CLOUD_LIMIT");QSet<QString> keys;for(auto v:rows){auto r=v.toObject();check(r.keys()==QStringList{"body","id","table"}&&tables().contains(str(r,"table"))&&!str(r,"id").isEmpty()&&str(r,"id").size()<=120&&r["body"].isObject(),"CLOUD_INVALID_RECORD");auto key=str(r,"table")+":"+str(r,"id");check(!keys.contains(key),"CLOUD_DUPLICATE");keys.insert(key);if(own&&merged.contains(key)&&merged[key]!=r){check(r["table"]=="team_members","CLOUD_RECORD_CONFLICT");auto a=r["body"].toObject(),b=merged[key]["body"].toObject();auto aa=a,bb=b;aa.remove("active");bb.remove("active");check(aa==bb,"CLOUD_TEAM_CONFLICT");auto q=sql("SELECT body FROM cloud_baseline WHERE origin=? AND organization_id=? AND branch_id=? AND record_key=?",{origin,organization,branch,key});check(q.next(),"CLOUD_TEAM_CONFLICT");auto old=QJsonDocument::fromJson(q.value(0).toByteArray()).object()["body"].toObject()["active"];check(a["active"]==old||b["active"]==old,"CLOUD_TEAM_CONFLICT");if(b["active"]==old)merged[key]=r;}else merged[key]=r;}};index(remote,false);index(snapshot(),true);QJsonArray result;for(auto r:merged)result.append(r);return result;}
void Business::join(QString tenant,QString requestedBranch,QJsonArray remote){guard("BRANCHES");check(!enrolled(),"CLOUD_JOIN_BEFORE_ENROLLMENT");for(auto table:tables())if(!QStringList{"organizations","branches","audit","payment_details"}.contains(table)){auto q=sql("SELECT COUNT(*) FROM "+table);q.next();check(q.value(0).toInt()==0,"CLOUD_JOIN_NEEDS_EMPTY_STORE");}auto count=sql("SELECT COUNT(*) FROM branches");count.next();check(count.value(0).toInt()==1,"CLOUD_JOIN_NEEDS_EMPTY_STORE");QJsonObject org,br;for(auto v:remote){auto r=v.toObject();if(r["table"]=="organizations"&&r["id"]==tenant)org=r["body"].toObject();if(r["table"]=="branches"&&r["id"]==requestedBranch)br=r["body"].toObject();}check(org["id"]==tenant&&br["id"]==requestedBranch&&br["organization_id"]==tenant,"CLOUD_SCOPE_MISSING");check(db.transaction(),"TRANSACTION_FAILED");try{sql("DELETE FROM settings");sql("DELETE FROM branches");sql("DELETE FROM organizations");insert("organizations",org,false);insert("branches",br,false);sql("INSERT INTO settings VALUES(1,?,?)",{tenant,requestedBranch});check(db.commit(),"TRANSACTION_FAILED");setScope();emit changed();}catch(...){db.rollback();throw;}}
void Business::validateReplica(){auto foreign=sql("PRAGMA foreign_key_check");check(!foreign.next(),"CLOUD_REFERENCE_CONFLICT");auto wallets=sql("SELECT member_id,SUM(amount_minor) FROM reseller_entries GROUP BY member_id");while(wallets.next())check(wallets.value(1).toLongLong()>=0&&wallets.value(1).toLongLong()<=999999999999LL,"CLOUD_WALLET_CONFLICT");for(auto table:{"invoices","sales"}){bool inv=QString(table)=="invoices";QString voids=inv?"invoice_voids":"sale_voids",key=inv?"invoice_id":"sale_id";auto q=sql("SELECT 1 FROM "+QString(table)+" i WHERE (EXISTS(SELECT 1 FROM "+voids+" v WHERE v."+key+"=i.id) AND (NOT EXISTS(SELECT 1 FROM ledger r WHERE r.reversal_of=i.charge_id) OR (i.payment_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM ledger r WHERE r.reversal_of=i.payment_id)))) OR (NOT EXISTS(SELECT 1 FROM "+voids+" v WHERE v."+key+"=i.id) AND EXISTS(SELECT 1 FROM ledger r WHERE r.reversal_of=i.charge_id OR r.reversal_of=i.payment_id)) LIMIT 1");check(!q.next(),"CLOUD_PARTIAL_VOID");}auto sales=sql("SELECT items_json,amount_minor FROM sales");while(sales.next()){auto lines=QJsonDocument::fromJson(sales.value(0).toByteArray()).array();check(lines.size()>=1&&lines.size()<=30,"CLOUD_SALE_CONFLICT");qint64 total=0;for(auto v:lines){auto l=v.toObject();clean(str(l,"name"),120,true);auto qty=l["quantity"].toInteger(),unit=l["unitMinor"].toInteger();check(qty>=1&&qty<=10000&&unit>=1&&unit<=999999999999LL/qty,"CLOUD_SALE_CONFLICT");check(total<=999999999999LL-unit*qty,"CLOUD_SALE_CONFLICT");total+=unit*qty;}check(total==sales.value(1).toLongLong(),"CLOUD_SALE_CONFLICT");}auto commissions=sql("SELECT 1 FROM reseller_entries e JOIN team_members m ON m.id=e.member_id LEFT JOIN sales s ON s.id=e.sale_id WHERE m.role!='RESELLER' OR (e.kind='COMMISSION' AND (s.id IS NULL OR s.organization_id!=e.organization_id OR s.branch_id!=e.branch_id OR s.currency!=m.currency OR e.amount_minor!=(s.paid_minor*m.commission_bps)/10000 OR (EXISTS(SELECT 1 FROM sale_voids v WHERE v.sale_id=s.id) AND NOT EXISTS(SELECT 1 FROM reseller_entries r WHERE r.reversal_of=e.id)))) LIMIT 1");check(!commissions.next(),"CLOUD_COMMISSION_CONFLICT");}
void Business::merge(QJsonArray incoming,bool preview){guard("BRANCHES");check(incoming.size()<=50000,"CLOUD_LIMIT");auto own=snapshot();QMap<QString,QJsonObject> local,records;for(auto v:own){auto o=v.toObject();local[str(o,"table")+":"+str(o,"id")]=o;}for(auto v:incoming){auto o=v.toObject();auto table=str(o,"table"),id=str(o,"id"),key=table+":"+id;check(tables().contains(table)&&!id.isEmpty()&&id.size()<=120&&!records.contains(key)&&o["body"].isObject(),"CLOUD_INVALID_RECORD");auto b=o["body"].toObject();if(b.contains("organization_id"))check(b["organization_id"]==organization,"CLOUD_SCOPE_MISMATCH");if(b.contains("branch_id"))check(b["branch_id"]==branch,"CLOUD_SCOPE_MISMATCH");if(table=="organizations")check(b["id"]==organization,"CLOUD_SCOPE_MISMATCH");if(table=="branches")check(b["id"]==branch,"CLOUD_SCOPE_MISMATCH");QStringList columns;auto q=sql("PRAGMA table_info("+table+")");while(q.next())if(q.value(1)!="sequence")columns.append(q.value(1).toString());if(table=="audit")columns.append("detail");columns.sort();check(columns==b.keys(),"CLOUD_INVALID_FIELDS");records[key]=o;}
 for(auto it=local.begin();it!=local.end();++it){check(records.contains(it.key()),"CLOUD_RECORD_MISSING");if(records[it.key()]!=it.value()){check(it.value()["table"]=="team_members","CLOUD_RECORD_CONFLICT");auto a=it.value()["body"].toObject(),b=records[it.key()]["body"].toObject();a.remove("active");b.remove("active");check(a==b,"CLOUD_TEAM_CONFLICT");}}
 check(db.transaction(),"TRANSACTION_FAILED");try{
  QMap<QString,QString> triggers;auto tq=sql("SELECT name,sql FROM sqlite_master WHERE type='trigger'");while(tq.next()){auto name=tq.value(0).toString();if(name.startsWith("audit_")&&name!="audit_details_no_update"&&name!="audit_details_no_delete"||QStringList{"reseller_member","reseller_nonnegative","reseller_commission_valid","sale_commission_guard"}.contains(name))triggers[name]=tq.value(1).toString();}for(auto name:triggers.keys())sql("DROP TRIGGER "+name);
  auto add=[&](QString table,std::function<bool(QJsonObject)> select=[](QJsonObject){return true;}){QList<QJsonObject> rows;for(auto r:records)if(r["table"]==table&&select(r["body"].toObject()))rows.append(r);std::sort(rows.begin(),rows.end(),[](auto a,auto b){auto x=a["body"].toObject()["created_at"].toInteger(),y=b["body"].toObject()["created_at"].toInteger();return x==y?str(a,"id")<str(b,"id"):x<y;});for(auto r:rows){auto key=table+":"+str(r,"id");auto b=r["body"].toObject();if(local.contains(key)){if(table=="team_members"&&local[key]!=r)sql("UPDATE team_members SET active=? WHERE id=?",{b["active"].toInt(),str(b,"id")});continue;}if(table=="audit"){auto detail=b["detail"];b.remove("detail");insert("audit",b,false);auto last=sql("SELECT last_insert_rowid()");last.next();auto seq=last.value(0).toLongLong();sql("INSERT INTO cloud_audit_ids VALUES(?,?)",{seq,str(r,"id")});if(detail.isObject()){auto d=detail.toObject();d["sequence"]=seq;insert("audit_details",d,false);}}else{insert(table,b,false);if(table=="network_jobs")sql("INSERT INTO network_results(job_id,state,created_at) VALUES(?,'REVIEW',?)",{str(b,"id"),QDateTime::currentMSecsSinceEpoch()});}}};
  for(auto t:{"organizations","branches","subscribers","plans","team_members"})add(t);
  auto original=[](QJsonObject b){return b["reversal_of"].isNull();};auto reversed=[](QJsonObject b){return !b["reversal_of"].isNull();};add("ledger",original);for(auto t:{"invoices","sales","payment_details","router_bindings","network_jobs","import_batches"})add(t);add("reseller_entries",[](QJsonObject b){return b["reversal_of"].isNull()&&b["amount_minor"].toInteger()>0;});add("reseller_entries",[](QJsonObject b){return b["reversal_of"].isNull()&&b["amount_minor"].toInteger()<0;});add("reseller_entries",reversed);add("invoice_voids");add("sale_voids");add("ledger",reversed);add("expenses",original);add("expenses",reversed);add("audit");validateReplica();for(auto trigger:triggers)sql(trigger);if(preview)db.rollback();else{check(db.commit(),"TRANSACTION_FAILED");message="تم دمج بيانات الأعمال • Business records merged";emit changed();}
 }catch(...){db.rollback();throw;}}
void Business::exportCsv(QUrl path){try{guard("EXPORT");QStringList columns,lines;for(auto row:view)for(auto k:row.toMap().keys())if(!columns.contains(k))columns.append(k);columns.sort();QStringList cells;for(auto c:columns)cells.append(Protocol::csvCell(c));lines.append(cells.join(','));for(auto r:view){cells.clear();for(auto c:columns)cells.append(Protocol::csvCell(r.toMap()[c].toString()));lines.append(cells.join(','));}saveFile(path.toLocalFile(),QByteArray("\xEF\xBB\xBF")+lines.join("\r\n").toUtf8());message="تم تصدير CSV • CSV exported";}catch(const std::exception&e){message=e.what();}emit changed();}
void Business::receipt(QString id,bool sale,QUrl path,QString paper,bool arabic){try{guard("READ");auto b=scoped(sale?"sales":"invoices",id);auto html=[&](QString x){return x.toHtmlEscaped();};auto amount=[&](qint64 n){return QString::number(n/100)+"."+QString::number(std::abs(n%100)).rightJustified(2,'0')+" "+html(str(b,"currency"));};QString body="<html dir='"+QString(arabic?"rtl":"ltr")+"'><head><meta charset='utf-8'></head><body><h1 style='color:#087a4f'>FG MACHINES</h1><h2>"+QString(arabic?"فاتورة وإيصال":"Invoice & receipt")+"</h2><p>"+html(id)+"</p><h3>"+html(str(b,sale?"customer":"customer_name"))+"</h3>";if(sale){body+="<table width='100%'>";for(auto v:QJsonDocument::fromJson(str(b,"items_json").toUtf8()).array()){auto l=v.toObject();body+="<tr><td>"+html(str(l,"name"))+"</td><td>"+QString::number(l["quantity"].toInt())+"</td><td>"+amount(l["unitMinor"].toInteger())+"</td></tr>";}body+="</table>";}else body+="<p>"+html(str(b,"plan_name"))+"</p><p>"+QDate(1970,1,1).addDays(b["starts_day"].toInteger()).toString("yyyy-MM-dd")+" → "+QDate(1970,1,1).addDays(b["ends_day"].toInteger()).toString("yyyy-MM-dd")+"</p>";body+="<hr><p>"+QString(arabic?"الإجمالي: ":"Total: ")+amount(b["amount_minor"].toInteger())+"</p><p>"+QString(arabic?"المدفوع: ":"Paid: ")+amount(b["paid_minor"].toInteger())+"</p><p>"+QString(arabic?"المتبقي: ":"Remaining: ")+amount(b["amount_minor"].toInteger()-b["paid_minor"].toInteger())+"</p></body></html>";QPdfWriter pdf(path.toLocalFile());pdf.setPageSize(paper=="A4"?QPageSize(QPageSize::A4):QPageSize(QSizeF(paper=="58"?58:80,180),QPageSize::Millimeter));pdf.setPageMargins(QMarginsF(4,4,4,4));QTextDocument document;document.setHtml(body);document.print(&pdf);message="تم حفظ الإيصال PDF • Receipt PDF saved";}catch(const std::exception&e){message=e.what();}emit changed();}
void Business::exportBackup(QUrl path,QString password){try{guard("BRANCHES");QJsonObject data;auto all=tables();all.removeAll("payment_details");all.removeAll("audit");all.append("settings");all.append("payment_details");all.append("audit");all.append("network_results");all.append("audit_details");for(auto table:all){QJsonArray rows;auto q=sql("SELECT * FROM "+table+" ORDER BY rowid");while(q.next())rows.append(row(q));data[table]=rows;}auto clear=QJsonDocument(QJsonObject{{"format","FG-MTM-business"},{"schema",5},{"tables",data}}).toJson(QJsonDocument::Compact);auto cipher=Vault::encrypt(clear,password);clear.fill('\0');saveFile(path.toLocalFile(),cipher);message="تم حفظ نسخة الأعمال المشفرة • Encrypted business backup saved";}catch(const std::exception&e){message=e.what();}emit changed();}
void Business::restoreBackup(QUrl path,QString password){try{check(!enrolled(),"RESTORE_BEFORE_IDENTITY");for(auto table:{"subscribers","ledger","plans","invoices","expenses","audit","import_batches","team_members","reseller_entries"}){auto q=sql("SELECT COUNT(*) FROM "+QString(table));q.next();check(q.value(0).toInt()==0,"RESTORE_NEEDS_EMPTY_STORE");}QFile f(path.toLocalFile());check(f.open(QIODevice::ReadOnly)&&f.size()<=20*1024*1024+52,"FILE_READ_FAILED");auto clear=Vault::decrypt(f.readAll(),password);auto root=QJsonDocument::fromJson(clear).object();clear.fill('\0');check(root["format"]=="FG-MTM-business"&&root["schema"].toInt()==5,"INVALID_BACKUP");auto data=root["tables"].toObject();QStringList order{"organizations","branches","settings","subscribers","ledger","plans","invoices","invoice_voids","expenses","import_batches","audit","payment_details","router_bindings","network_jobs","network_results","sales","sale_voids","team_members","reseller_entries","audit_details"};auto keys=order;keys.sort();check(keys==data.keys(),"INVALID_BACKUP");check(db.transaction(),"TRANSACTION_FAILED");try{QMap<QString,QString> triggers;auto q=sql("SELECT name,sql FROM sqlite_master WHERE type='trigger'");while(q.next()){auto name=q.value(0).toString();if(name.startsWith("audit_")&&!name.startsWith("audit_details_")||QStringList{"reseller_member","reseller_nonnegative","reseller_commission_valid","sale_commission_guard"}.contains(name))triggers[name]=q.value(1).toString();}for(auto name:triggers.keys())sql("DROP TRIGGER "+name);sql("DELETE FROM settings");sql("DELETE FROM branches");sql("DELETE FROM organizations");for(auto table:order){auto rows=data[table].toArray();auto columns=sql("PRAGMA table_info("+table+")");QStringList expected;while(columns.next())expected.append(columns.value(1).toString());expected.sort();for(auto v:rows){check(v.isObject()&&v.toObject().keys()==expected,"INVALID_BACKUP");insert(table,v.toObject(),false);}}validateReplica();for(auto trigger:triggers)sql(trigger);sql("INSERT INTO network_results(job_id,state,created_at) SELECT id,'REVIEW',? FROM network_jobs",{QDateTime::currentMSecsSinceEpoch()});check(db.commit(),"TRANSACTION_FAILED");setScope();message="تم استعادة الأعمال • Business backup restored";}catch(...){db.rollback();throw;}}catch(const std::exception&e){message=e.what();}emit changed();}
