#include "NetworkBilling.hpp"
#include "Vouchers.hpp"
#include <QDateTime>
#include <QCryptographicHash>
#include <QRegularExpression>
#include <limits>
namespace {
void require(bool ok,const char *code){if(!ok)throw std::runtime_error(code);}
QString value(QJsonObject o,QString k){return o[k].toVariant().toString();}
QString menu(QJsonObject t){auto service=t["service"].toString();require(service=="HOTSPOT"||service=="PPPOE","UNSUPPORTED_SERVICE");return service=="HOTSPOT"?"ip/hotspot/user":"ppp/secret";}
bool disabled(QJsonObject r){return QStringList{"yes","true"}.contains(value(r,"disabled"));}
bool enabled(QJsonObject r){return QStringList{"no","false"}.contains(value(r,"disabled"));}
QStringList names(QJsonArray rows){QStringList result;for(auto v:rows)if(!v.toObject()["name"].toString().isEmpty())result.append(v.toObject()["name"].toString());return result;}
}
NetworkBilling::NetworkBilling(RouterClient*r,Business*b,QObject*p):QObject(p),router(r),business(b){connect(b,&Business::changed,this,&NetworkBilling::changed);}
NetworkBilling::~NetworkBilling(){lifetime.reset();}
QStringList NetworkBilling::hotspotProfiles()const{return names(catalog["hotspotProfiles"].toArray());}
QStringList NetworkBilling::pppProfiles()const{return names(catalog["pppProfiles"].toArray());}
RouterJob NetworkBilling::identity(){
 auto hw=co_await call("system/routerboard","print",{{".proplist","serial-number"}},false);QString stable;
 if(hw.ok()&&!hw.rows.isEmpty()&&!value(hw.rows[0].toObject(),"serial-number").isEmpty())stable="serial:"+value(hw.rows[0].toObject(),"serial-number");
 if(stable.isEmpty()){auto license=co_await call("system/license","print",{{".proplist","software-id,system-id"}});if(!license.rows.isEmpty()){auto row=license.rows[0].toObject();if(!value(row,"software-id").isEmpty())stable="software:"+value(row,"software-id");else if(!value(row,"system-id").isEmpty())stable="system:"+value(row,"system-id");}}
 require(!stable.isEmpty(),"ROUTER_ID_UNAVAILABLE");fingerprint=QString::fromLatin1(QCryptographicHash::hash(stable.toUtf8(),QCryptographicHash::Sha256).toHex());auto id=co_await call("system/identity","print",{{".proplist","name"}});label=id.rows.isEmpty()?QString{}:value(id.rows[0].toObject(),"name");
}
RouterJob NetworkBilling::account(QJsonObject t){co_await identity();require(fingerprint==value(t,"fingerprint"),"WRONG_ROUTER");auto users=co_await call(menu(t),"print",{{".proplist",".id,name,profile,disabled,service,limit-uptime,limit-bytes-total,bytes-in,bytes-out"}});int found=0;for(auto v:users.rows){auto r=v.toObject();if(value(r,".id")==value(t,"account_id")&&value(r,"name")==value(t,"account")&&(t["service"]=="HOTSPOT"||r["service"]=="pppoe")){found++;accountRow=r;}}require(found==1,"ACCOUNT_CHANGED");}
RouterJob NetworkBilling::validate(QJsonObject t){require(QRegularExpression("^[A-Za-z0-9-]{1,64}$").match(value(t,"binding")).hasMatch(),"INVALID_BINDING");auto username=value(t,"account");require(!username.trimmed().isEmpty(),"INVALID_TEXT");for(auto c:username)require(c.category()!=QChar::Other_Control,"INVALID_TEXT");require(t["end_day"].toInteger()>QDate(1970,1,1).daysTo(QDate::currentDate()),"SUBSCRIPTION_EXPIRED");auto profile=co_await call(t["service"]=="HOTSPOT"?"ip/hotspot/user/profile":"ppp/profile","print",{{".proplist","name"}});require(names(profile.rows).contains(value(t,"profile")),"PROFILE_NOT_FOUND");auto reply=co_await call("system/clock","print",{{".proplist","date,time"}});require(reply.rows.size()==1,"MODERN_CLOCK_REQUIRED");auto row=reply.rows[0].toObject();auto date=QDate::fromString(value(row,"date"),"yyyy-MM-dd");auto time=QTime::fromString(value(row,"time"),"HH:mm:ss");require(date.isValid()&&time.isValid(),"MODERN_CLOCK_REQUIRED");require(qAbs(QDateTime(date,time).secsTo(QDateTime::currentDateTime()))<=300,"ROUTER_CLOCK_MISMATCH");}
void NetworkBilling::loadCatalog(){if(working||router->busy())return;working=true;emit changed();job=catalogJob();job.start();}
void NetworkBilling::importSelected(QVariantList indexes,QString currency){if(working||router->busy())return;working=true;emit changed();job=catalogJob(indexes,currency);job.start();}
RouterJob NetworkBilling::catalogJob(QVariantList selection,QString currency){try{require(business->allowed("IMPORT")&&business->allowed("ROUTER"),"ACCESS_DENIED");auto previous=catalog;auto connection=router->identityKey();co_await identity();QJsonArray accounts;for(auto service:QStringList{"HOTSPOT","PPPOE"}){auto r=co_await call(service=="HOTSPOT"?"ip/hotspot/user":"ppp/secret","print",{{".proplist",".id,name,profile,disabled,service"}});for(auto v:r.rows){auto a=v.toObject();if(service=="PPPOE"&&a["service"]!="pppoe")continue;require(!value(a,".id").isEmpty()&&!value(a,"name").isEmpty(),"INVALID_ROUTER_ROW");accounts.append(QJsonObject{{"id",a[".id"]},{"name",a["name"]},{"service",service},{"profile",value(a,"profile")},{"disabled",disabled(a)}});}}require(accounts.size()<=5000,"IMPORT_LIMIT");auto hs=co_await call("ip/hotspot/user/profile","print",{{".proplist","name"}});auto ppp=co_await call("ppp/profile","print",{{".proplist","name"}});catalog={{"fingerprint",fingerprint},{"label",label},{"accounts",accounts},{"hotspotProfiles",hs.rows},{"pppProfiles",ppp.rows}};require(router->identityKey()==connection,"SESSION_CHANGED");if(!selection.isEmpty()){require(catalogConnection==connection&&previous["fingerprint"]==catalog["fingerprint"],"WRONG_ROUTER");QJsonArray chosen;for(auto index:selection){bool ok;int i=index.toString().toInt(&ok);require(ok&&i>=0&&i<previous["accounts"].toArray().size(),"INVALID_SELECTION");const QJsonValue a=previous.value("accounts").toArray().at(i);require(accounts.contains(a),"ACCOUNT_CHANGED");chosen.append(a);}business->importRouterAccounts(catalog,chosen,currency);message=business->status();}else message="اختر الحسابات المراد ربطها بالمشتركين • Select accounts to bind to subscribers";catalogConnection=connection;}catch(const std::exception&e){message=e.what();}working=false;emit changed();}
void NetworkBilling::prepare(QString invoice,QString profile,QString allowance){if(working||router->busy())return;working=true;proposed={};emit changed();job=prepareJob(invoice,profile,allowance);job.start();}
RouterJob NetworkBilling::prepareJob(QString invoice,QString profile,QString allowance){try{auto connection=router->identityKey();auto t=business->networkTarget(invoice);if(t.contains("job")){require(profile.isEmpty()||profile==value(t,"profile"),"IDEMPOTENCY_CONFLICT");}else{t["profile"]=profile;bool valid;auto mb=allowance.toLongLong(&valid);require(valid&&mb>=0&&mb<=std::numeric_limits<qint64>::max()/1048576,"INVALID_QUOTA");require(t["service"]=="HOTSPOT"||mb==0,"INVALID_QUOTA");co_await account(t);qint64 limit=0;if(mb){bool a,b;auto in=value(accountRow,"bytes-in").toLongLong(&a),out=value(accountRow,"bytes-out").toLongLong(&b);require(a&&b&&in>=0&&out>=0&&in<=std::numeric_limits<qint64>::max()-out,"COUNTERS_UNAVAILABLE");auto total=in+out;require(total<=std::numeric_limits<qint64>::max()-mb*1048576,"INVALID_QUOTA");limit=total+mb*1048576;}t["byte_limit"]=limit;}co_await account(t);if(!t.contains("job"))co_await validate(t);require(router->identityKey()==connection,"SESSION_CHANGED");proposed=t;preparedConnection=connection;message="راجع الحساب والباقة وتاريخ الانتهاء قبل التطبيق • Review account, profile and expiry before applying";}catch(const std::exception&e){message=e.what();}working=false;emit changed();}
QString NetworkBilling::expiryScript(QJsonObject t){auto date=QDate(1970,1,1).addDays(t["end_day"].toInteger()).toString("yyyyMMdd"),user=t["service"]=="HOTSPOT"?QString("/ip hotspot user"):QString("/ppp secret"),active=t["service"]=="HOTSPOT"?QString("/ip hotspot active"):QString("/ppp active"),field=t["service"]=="HOTSPOT"?QString("user"):QString("name");return ":local d [/system clock get date]; :if ([:len $d] != 10) do={:error \"ISO clock required\"}; :local n [:tonum ([:pick $d 0 4].[:pick $d 5 7].[:pick $d 8 10])]; :if ($n >= "+date+") do={ :if (["+user+" get "+Vouchers::quote(value(t,"account_id"))+" name] = "+Vouchers::quote(value(t,"account"))+") do={ "+user+" set "+Vouchers::quote(value(t,"account_id"))+" disabled=yes; "+active+" remove [find where "+field+"="+Vouchers::quote(value(t,"account"))+"]; }; }";}
RouterJob NetworkBilling::disconnectAccount(QJsonObject t){bool hs=t["service"]=="HOTSPOT";auto active=hs?QString("ip/hotspot/active"):QString("ppp/active"),field=hs?QString("user"):QString("name");auto r=co_await call(active,"print",{{".proplist",".id,"+field}});for(auto v:r.rows){auto row=v.toObject();if(row[field]==t["account"])co_await call(active,"remove",{{".id",row[".id"]}});}}
void NetworkBilling::apply(bool suspend){if(working||router->busy()||proposed.isEmpty())return;working=true;emit changed();job=applyJob(suspend);job.start();}
RouterJob NetworkBilling::applyJob(bool suspend){try{require(preparedConnection==router->identityKey(),"SESSION_CHANGED");auto t=proposed;co_await account(t);if(!suspend)co_await validate(t);auto saved=business->saveNetworkJob(value(t,"invoice"),t);t["job"]=saved["job"];business->networkResult(value(t,"invoice"),"REVIEW");const auto name="fg-bill-"+value(t,"binding"),owner="FG MTM billing:"+value(t,"binding");auto r=co_await call("system/scheduler","print",{{".proplist",".id,name,comment,on-event,disabled,interval"}});QJsonArray existing;for(auto v:r.rows)if(v.toObject()["name"]==name)existing.append(v);require(existing.size()<=1&&(existing.isEmpty()||existing[0].toObject()["comment"]==owner),"SCHEDULER_CONFLICT");if(suspend){co_await call(menu(t),"set",{{".id",t["account_id"]},{"disabled","yes"}});co_await disconnectAccount(t);if(!existing.isEmpty())co_await call("system/scheduler","set",{{".id",existing[0].toObject()[".id"]},{"disabled","yes"}});co_await account(t);require(disabled(accountRow),"VERIFY_FAILED");business->networkResult(value(t,"invoice"),"SUSPENDED");message="تم تعليق الحساب والتحقق منه • Account suspended and verified";}else{QJsonObject attrs{{"name",name},{"comment",owner},{"on-event",expiryScript(t)},{"interval","1m"},{"start-time","00:00:00"},{"policy","read,write,test"},{"disabled","no"}};if(!existing.isEmpty())attrs[".id"]=existing[0].toObject()[".id"];co_await call("system/scheduler",existing.isEmpty()?"add":"set",attrs);auto verify=co_await call("system/scheduler","print",{{".proplist","name,comment,on-event,disabled,interval"}});int found=0;for(auto v:verify.rows){auto row=v.toObject();if(row["name"]==name&&row["comment"]==owner&&row["on-event"]==attrs["on-event"]&&enabled(row)&&QStringList{"1m","00:01:00"}.contains(value(row,"interval")))found++;}require(found==1,"VERIFY_FAILED");QJsonObject update{{".id",t["account_id"]},{"profile",t["profile"]},{"disabled","no"}};if(t["service"]=="HOTSPOT"){update["limit-uptime"]="0s";update["limit-bytes-total"]=QString::number(t["byte_limit"].toInteger());}co_await account(t);co_await call(menu(t),"set",update);co_await disconnectAccount(t);co_await account(t);require(accountRow["profile"]==t["profile"]&&enabled(accountRow),"VERIFY_FAILED");if(t["service"]=="HOTSPOT"){bool ok;auto bytes=value(accountRow,"limit-bytes-total").toLongLong(&ok);require(ok&&bytes==t["byte_limit"].toInteger()&&QStringList{"0s","00:00:00","0"}.contains(value(accountRow,"limit-uptime")),"VERIFY_FAILED");}business->networkResult(value(t,"invoice"),"VERIFIED");message="تم تفعيل التجديد والتحقق من حماية الانتهاء • Renewal applied and expiry protection verified";}proposed=business->networkTarget(value(t,"invoice"));}catch(const std::exception&e){message=QString(e.what())+" • راجع النتيجة قبل إعادة التطبيق • Review outcome before applying again";}working=false;emit changed();}
