#include "RouterTools.hpp"
#include "Vouchers.hpp"
#include "Vault.hpp"
#include <QHostAddress>
#include <QCryptographicHash>
#include <QJsonDocument>
#include <QFile>
#include <QSaveFile>
#include <QDir>
#include <QStandardPaths>
#include <QDateTime>
#include <QTimeZone>
#include <QLocale>
#include <QUuid>
#include <QRegularExpression>
#include <algorithm>
#include <QDesktopServices>
#include <limits>
namespace {
void check(bool ok,QString why){if(!ok)throw std::runtime_error(why.toStdString());}
QString str(QJsonObject o,QString key,QString fallback={}){return o[key].toString(fallback);}
bool yes(QJsonObject o,QString key){return o[key]=="yes"||o[key]=="true"||o[key]==true;}
bool enabled(QJsonObject o){return !yes(o,"disabled");}
QList<QJsonObject> rows(QJsonObject tables,QString menu){QList<QJsonObject> out;for(auto value:tables[menu].toArray())out.append(value.toObject());return out;}
QJsonObject find(QJsonObject tables,QString menu,QString key,QString value){for(auto r:rows(tables,menu))if(r[key]==value)return r;return {};}
quint32 ip(QString value){QHostAddress a;check(a.setAddress(value)&&a.protocol()==QAbstractSocket::IPv4Protocol,"INVALID_IP");return a.toIPv4Address();}
quint32 mask(int n){return quint32(0xffffffffu<<(32-n));}
bool belongs(QString value,QString cidr){return (ip(value)&mask(cidr.section('/',1).toInt()))==ip(RouterTools::network(cidr).section('/',0,0));}
bool overlaps(QString a,QString b){return belongs(a.section('/',0,0),b)||belongs(b.section('/',0,0),a);}
QJsonObject change(QString menu,QString action,QJsonObject after,QJsonObject before={},QString label={}){return {{"menu",menu},{"action",action},{"attributes",after},{"undo",before},{"label",label}};}
QString normalized(QString v){if(v=="true")return "yes";if(v=="false")return "no";return v.remove(' ');}
bool valuesEqual(QJsonObject row,QJsonObject expected){for(auto it=expected.begin();it!=expected.end();++it)if(normalized(str(row,it.key()))!=normalized(it.value().toString()))return false;return true;}
QStringList inspectionMenus(){return {"system/resource","system/clock","interface","interface/bridge","interface/bridge/port","interface/vlan","ip/dhcp-client","interface/pppoe-client","interface/list/member","ip/address","ip/route","ip/firewall/nat","ip/firewall/filter","ip/dns","ip/dhcp-server","ip/dhcp-server/network","ip/pool","ip/hotspot","ip/hotspot/profile","ip/hotspot/user/profile","ip/service","user","system/scheduler","file","ip/hotspot/user","ip/hotspot/active"};}
QString wan(QJsonObject t){for(auto r:rows(t,"ip/route"))if(r["dst-address"]=="0.0.0.0/0"&&enabled(r)&&yes(r,"active")){auto g=str(r,"immediate-gw").section('%',1).section(',',0,0);if(!g.isEmpty())return g;auto gateway=str(r,"gateway");if(!find(t,"interface","name",gateway).isEmpty())return gateway;}for(auto r:rows(t,"interface/list/member"))if(str(r,"list").compare("WAN",Qt::CaseInsensitive)==0)return str(r,"interface");return {};}
bool natServes(QJsonObject r,QString cidr,QString internet){if(!enabled(r)||r["chain"]!="srcnat"||!QStringList{"masquerade","src-nat"}.contains(str(r,"action")))return false;auto output=str(r,"out-interface");if(!output.isEmpty()&&!internet.isEmpty()&&output!=internet)return false;auto source=str(r,"src-address");return source.isEmpty()||source=="0.0.0.0/0"||RouterTools::validCidr(source)&&belongs(cidr.section('/',0,0),source)&&source.section('/',1).toInt()<=cidr.section('/',1).toInt();}
}
RouterTools::RouterTools(RouterClient*c,QObject*p):QObject(p),client(c){}
RouterTools::~RouterTools(){lifetime.reset();}
bool RouterTools::validCidr(QString cidr){auto parts=cidr.split('/');QHostAddress a;return parts.size()==2&&a.setAddress(parts[0])&&a.protocol()==QAbstractSocket::IPv4Protocol&&QRegularExpression("^[0-9]+$").match(parts[1]).hasMatch()&&parts[1].toInt()>=1&&parts[1].toInt()<=30;}
QString RouterTools::network(QString cidr){check(validCidr(cidr),"INVALID_CIDR");auto p=cidr.section('/',1).toInt();return QHostAddress(ip(cidr.section('/',0,0))&mask(p)).toString()+"/"+QString::number(p);}
bool RouterTools::privateSubnet(QString cidr){if(!validCidr(cidr)||network(cidr)!=cidr)return false;auto a=ip(cidr.section('/',0,0));auto prefix=cidr.section('/',1).toInt();return (a>>24==10&&prefix>=8)||((a>>20)==0xac1&&prefix>=12)||((a>>16)==0xc0a8&&prefix>=16)||((a>>22)==0x191&&prefix>=10);}
QJsonObject RouterTools::hotspotPlan(QJsonObject t,QJsonObject r,QString management){auto iface=str(r,"interface"),gateway=str(r,"gateway"),net=str(r,"network"),pool=str(r,"pool"),dnsName=str(r,"dnsName","wifi.local");check(validCidr(gateway)&&validCidr(net)&&network(gateway)==network(net),"INVALID_CLIENT_SUBNET");auto range=pool.remove(' ').split('-');check(range.size()==2&&belongs(range[0],net)&&belongs(range[1],net)&&ip(range[0])<=ip(range[1]),"INVALID_POOL");auto base=ip(network(net).section('/',0,0)),broadcast=base+~mask(net.section('/',1).toInt());check(ip(range[0])>base&&ip(range[1])<broadcast&&!(ip(gateway.section('/',0,0))>=ip(range[0])&&ip(gateway.section('/',0,0))<=ip(range[1])),"POOL_MUST_EXCLUDE_GATEWAY_NETWORK_BROADCAST");check(QRegularExpression("^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$").match(dnsName).hasMatch(),"INVALID_DNS_NAME");auto selected=find(t,"interface","name",iface);check(!selected.isEmpty()&&enabled(selected),"SELECT_ENABLED_CLIENT_INTERFACE");auto internet=wan(t);check(iface!=internet||internet.isEmpty(),"WAN_CANNOT_BE_CLIENT");for(auto a:rows(t,"ip/address"))if(a["interface"]!=iface&&validCidr(str(a,"address")))check(!overlaps(str(a,"address"),net),"SUBNET_OVERLAP");QJsonArray changes;auto tag="fg-mtm-"+QUuid::createUuid().toString(QUuid::WithoutBraces).left(8);bool hasAddress=false;for(auto a:rows(t,"ip/address"))if(a["interface"]==iface&&enabled(a)){check(a["address"]==gateway,"PRESERVE_EXISTING_GATEWAY");hasAddress=true;}if(!hasAddress)changes.append(change("ip/address","add",{{"address",gateway},{"interface",iface},{"comment","FG MTM client gateway"}},{},"إضافة بوابة العملاء • Add client gateway"));
 auto dhcp=find(t,"ip/dhcp-server","interface",iface);auto poolName=str(dhcp,"address-pool");if(poolName.isEmpty()||find(t,"ip/pool","name",poolName).isEmpty())poolName=str(find(t,"ip/pool","ranges",pool),"name");if(poolName.isEmpty()){poolName=tag;changes.append(change("ip/pool","add",{{"name",poolName},{"ranges",pool}},{},"إنشاء مدى العناوين • Create address pool"));}
 auto dns=t["ip/dns"].toArray().isEmpty()?QJsonObject{}:t["ip/dns"].toArray().first().toObject();if(str(dns,"servers").isEmpty()&&str(dns,"dynamic-servers").isEmpty())changes.append(change("ip/dns","set",{{"servers","1.1.1.1,9.9.9.9"}},{{"servers",str(dns,"servers")}},"ضبط DNS • Configure DNS"));
 if(find(t,"ip/dhcp-server/network","address",net).isEmpty())changes.append(change("ip/dhcp-server/network","add",{{"address",net},{"gateway",gateway.section('/',0,0)},{"dns-server",yes(dns,"allow-remote-requests")?gateway.section('/',0,0):"1.1.1.1,9.9.9.9"}},{},"إعداد شبكة DHCP • Configure DHCP network"));
 if(dhcp.isEmpty())changes.append(change("ip/dhcp-server","add",{{"name",tag},{"interface",iface},{"address-pool",poolName},{"disabled","no"}},{},"إنشاء DHCP • Create DHCP server"));else {check(!yes(dhcp,"invalid"),"DHCP_INVALID");auto id=str(dhcp,".id");check(!id.isEmpty(),"TARGET_ID_REQUIRED");if(!enabled(dhcp))changes.append(change("ip/dhcp-server","set",{{".id",id},{"disabled","no"}},{{".id",id},{"disabled",str(dhcp,"disabled")}},"تفعيل DHCP • Enable DHCP"));if(str(dhcp,"address-pool")!=poolName)changes.append(change("ip/dhcp-server","set",{{".id",id},{"address-pool",poolName}},{{".id",id},{"address-pool",str(dhcp,"address-pool")}},"ربط المدى • Assign DHCP pool"));}
 bool nat=false;for(auto row:rows(t,"ip/firewall/nat"))if(natServes(row,net,internet))nat=true;if(!nat&&!internet.isEmpty())changes.append(change("ip/firewall/nat","add",{{"chain","srcnat"},{"action","masquerade"},{"src-address",net},{"out-interface",internet},{"comment","FG MTM client internet"}},{},"مشاركة الإنترنت للعملاء • Add client NAT"));
 auto server=find(t,"ip/hotspot","interface",iface),profile=find(t,"ip/hotspot/profile","name",str(server,"profile"));auto profileName=str(profile,"name",tag);if(profile.isEmpty())changes.append(change("ip/hotspot/profile","add",{{"name",profileName},{"hotspot-address",gateway.section('/',0,0)},{"dns-name",dnsName},{"login-by","http-chap"}},{},"إعداد HotSpot • Create HotSpot profile"));else if(!str(profile,"login-by").split(',').contains("http-chap")&&!str(profile,"login-by").split(',').contains("https"))changes.append(change("ip/hotspot/profile","set",{{".id",profile[".id"]},{"login-by",str(profile,"login-by").isEmpty()?"http-chap":str(profile,"login-by")+",http-chap"}},{{".id",profile[".id"]},{"login-by",profile["login-by"]}},"دخول CHAP • Enable CHAP login"));
 if(t["ip/hotspot/user/profile"].toArray().isEmpty())changes.append(change("ip/hotspot/user/profile","add",{{"name","fg-default"},{"shared-users","1"}},{},"باقة افتراضية • Default voucher profile"));if(server.isEmpty())changes.append(change("ip/hotspot","add",{{"name",tag},{"interface",iface},{"profile",profileName},{"address-pool",poolName},{"disabled","no"}},{},"إنشاء HotSpot • Create HotSpot server"));else{check(!yes(server,"invalid"),"HOTSPOT_INVALID");if(!enabled(server))changes.append(change("ip/hotspot","set",{{".id",server[".id"]},{"disabled","no"}},{{".id",server[".id"]},{"disabled",server["disabled"]}},"تفعيل HotSpot • Enable HotSpot"));}
 auto directory=str(profile,"html-directory-override");if(directory.isEmpty())directory=str(profile,"html-directory");bool hasPortal=true;for(auto file:{"login.html","status.html","md5.js"})if(find(t,"file","name",directory+"/"+file).isEmpty())hasPortal=false;
 return {{"kind","HOTSPOT"},{"request",r},{"changes",changes},{"profileName",profileName},{"installPortal",r["replacePortal"].toBool()||profile.isEmpty()||!hasPortal}};
}
QJsonObject RouterTools::portsPlan(QJsonObject t,QString selected,QString internet,QString management){check(!selected.isEmpty()&&!internet.isEmpty(),"WAN_CLIENT_REQUIRED");bool bridge=!find(t,"interface/bridge","name",selected).isEmpty();auto target=bridge?selected:"fg-clients";QSet<QString> occupied,protectedPorts;for(auto m:{"interface/bridge/port","interface/vlan","ip/dhcp-client","interface/pppoe-client"})for(auto r:rows(t,m)){occupied.insert(str(r,"interface"));protectedPorts.insert(str(r,"interface"));}protectedPorts.insert(internet);for(auto r:rows(t,"interface/list/member"))if(str(r,"list").compare("WAN",Qt::CaseInsensitive)==0)protectedPorts.insert(str(r,"interface"));for(auto m:{"ip/address","ip/dhcp-server","ip/hotspot"})for(auto r:rows(t,m))if(r["interface"]!=selected)occupied.insert(str(r,"interface"));for(auto r:rows(t,"ip/address"))if(r["interface"]==selected)check(!management.contains(str(r,"address").section('/',0,0)),"USE_WAN_SIDE_MANAGEMENT");if(!bridge){check(find(t,"interface","name",target).isEmpty()&&!protectedPorts.contains(selected)&&!occupied.contains(selected),"CLIENT_PORT_OCCUPIED");auto port=find(t,"interface","name",selected);check(port["type"]=="ether"||QRegularExpression("^ether[0-9]+$").match(selected).hasMatch(),"PHYSICAL_CLIENT_PORT_REQUIRED");for(auto m:{"ip/firewall/filter","ip/firewall/nat"})for(auto r:rows(t,m))check(r["in-interface"]!=selected&&r["out-interface"]!=selected,"INTERFACE_FIREWALL_REVIEW");}QJsonArray changes;if(!bridge){changes.append(change("interface/bridge","add",{{"name",target},{"comment","FG MTM customer network"}},{},"إنشاء جسر العملاء • Create client bridge"));for(auto m:{"ip/address","ip/dhcp-server","ip/hotspot","interface/list/member"})for(auto r:rows(t,m))if(r["interface"]==selected){check(!str(r,".id").isEmpty()&&!yes(r,"dynamic"),"DYNAMIC_CLIENT_SETTING");changes.append(change(m,"set",{{".id",r[".id"]},{"interface",target}},{{".id",r[".id"]},{"interface",selected}},"نقل الإعداد للجسر • Move client configuration"));}}
 QStringList ports;if(!bridge)ports.append(selected);for(auto r:rows(t,"interface")){auto n=str(r,"name");if(n!=selected&&!occupied.contains(n)&&!protectedPorts.contains(n)&&enabled(r)&&!yes(r,"running")&&(r["type"]=="ether"||QRegularExpression("^ether[0-9]+$").match(n).hasMatch()))ports.append(n);}for(auto port:ports)changes.append(change("interface/bridge/port","add",{{"bridge",target},{"interface",port}},{},"ضم المنفذ • Group port "+port));return {{"kind","PORTS"},{"changes",changes},{"bridge",target}};}
QJsonObject RouterTools::dnsPlan(QJsonObject t,QSet<QString> selected,QString mode){check(!selected.isEmpty()&&selected.size()<=32&&QStringList{"FAMILY","ADS_TRACKERS"}.contains(mode),"SELECT_CLIENT_NETWORK");auto servers=mode=="FAMILY"?"94.140.14.15,94.140.15.16":"94.140.14.14,94.140.15.15";QJsonArray changes;auto add=[&](QString menu,QJsonObject r,QJsonObject after){QJsonObject changed,before;for(auto it=after.begin();it!=after.end();++it)if(normalized(str(r,it.key()))!=normalized(it.value().toString())){changed[it.key()]=it.value();before[it.key()]=str(r,it.key());}if(!changed.isEmpty()){if(menu!="ip/dns"){changed[".id"]=r[".id"];before[".id"]=r[".id"];}changes.append(change(menu,"set",changed,before,str(r,"address",menu)));}};check(t["ip/dns"].toArray().size()==1,"DNS_READ_REQUIRED");auto dns=t["ip/dns"].toArray().first().toObject();QJsonObject settings{{"servers",servers}};if(dns.contains("use-doh-server"))settings["use-doh-server"]="";add("ip/dns",dns,settings);int count=0;for(auto r:rows(t,"ip/dhcp-server/network"))if(selected.contains(str(r,".id"))){check(privateSubnet(str(r,"address"))&&str(r,"dhcp-option").isEmpty()&&str(r,"dhcp-option-set").isEmpty(),"DHCP_OPTIONS_OR_PUBLIC_NETWORK_REVIEW");QJsonObject attrs{{"dns-server",servers}};if(r.contains("dns-none"))attrs["dns-none"]="no";add("ip/dhcp-server/network",r,attrs);count++;}check(count==selected.size(),"SELECT_CLIENT_NETWORK");for(auto menu:{"ip/dhcp-client","interface/pppoe-client"})for(auto r:rows(t,menu))if(enabled(r)&&yes(r,"use-peer-dns")){check(!str(r,".id").isEmpty(),"TARGET_ID_REQUIRED");add(menu,r,{{"use-peer-dns","no"}});}check(changes.size()<=128,"DNS_CHANGE_LIMIT");return {{"kind","DNS"},{"mode",mode},{"changes",changes},{"servers",servers}};}
QJsonObject RouterTools::renderPortal(QJsonObject design){auto color=str(design,"color","#159DFF");check(QRegularExpression("^#[a-fA-F0-9]{6}$").match(color).hasMatch(),"INVALID_COLOR");auto logo=str(design,"logoDataUri");if(!QRegularExpression("^data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$").match(logo).hasMatch())logo.clear();auto website=str(design,"website");if(!website.startsWith("https://"))website.clear();QJsonObject assets;QDir dir(":/resources/hotspot");for(auto name:dir.entryList(QDir::Files)){QFile f(dir.filePath(name));check(f.open(QIODevice::ReadOnly),"PORTAL_ASSET_MISSING");auto content=QString::fromUtf8(f.readAll());for(auto pair:QList<QPair<QString,QString>>{{"NETWORK",str(design,"networkName","FG Machines WiFi").toHtmlEscaped()},{"PHONE",str(design,"supportPhone").toHtmlEscaped()},{"WELCOME",str(design,"welcome").toHtmlEscaped()},{"COLOR",color},{"TERMS",str(design,"terms").toHtmlEscaped()},{"WEBSITE",website.toHtmlEscaped()},{"LOGO",logo}})content.replace("@@"+pair.first+"@@",pair.second);check(content.toUtf8().size()<60000,"PORTAL_FILE_LIMIT");assets[name]=content;}check(assets.contains("login.html")&&assets.contains("status.html")&&assets.contains("md5.js"),"PORTAL_ASSET_MISSING");return assets;}
QString RouterTools::signature()const{QJsonObject stable;QSet<QString> keys{".id","name","interface","address","ranges","profile","address-pool","disabled","servers","allow-remote-requests","chain","action","src-address","out-interface","dst-address","gateway","login-by","dns-name","html-directory","html-directory-override","group","network","lease-time","dns-server","netmask","port","certificate","hotspot-address","in-interface","out-interface-list","in-interface-list","protocol","dst-port","src-port","bridge","pvid","vlan-id","vlan-filtering","connection-state","to-addresses","to-ports","list","use-doh-server","use-peer-dns","dns-none","dhcp-option","dhcp-option-set"};for(auto menu:tables.keys()){if(QStringList{"system/resource","system/clock","system/scheduler","ip/hotspot/user","ip/hotspot/active"}.contains(menu))continue;QStringList values;for(auto r:rows(tables,menu)){if(yes(r,"dynamic"))continue;if(menu=="file"&&!QStringList{"login.html","status.html","md5.js"}.contains(str(r,"name").section('/',-1)))continue;QJsonObject kept;for(auto k:r.keys())if(keys.contains(k))kept[k]=r[k];values.append(QString::fromUtf8(QJsonDocument(kept).toJson(QJsonDocument::Compact)));}values.sort();QJsonArray list;for(auto v:values)list.append(v);stable[menu]=list;}return QString::fromLatin1(QCryptographicHash::hash(QJsonDocument(stable).toJson(QJsonDocument::Compact),QCryptographicHash::Sha256).toHex());}
QString RouterTools::fingerprint()const{QStringList macs;for(auto r:rows(tables,"interface"))if(r["type"]=="ether"&&!str(r,"mac-address").isEmpty())macs.append(str(r,"mac-address").toUpper());macs.removeDuplicates();macs.sort();check(!macs.isEmpty(),"ROUTER_IDENTITY_REQUIRED");return QString::fromLatin1(QCryptographicHash::hash(macs.join(',').toUtf8(),QCryptographicHash::Sha256).toHex());}
QString RouterTools::journalPath()const{auto dir=QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation)+"/router-journals";QDir().mkpath(dir);return dir+"/"+QString::fromLatin1(QCryptographicHash::hash(client->identityKey().toUtf8(),QCryptographicHash::Sha256).toHex())+".fgj";}
void RouterTools::persist(){auto clear=QJsonDocument(journal).toJson(QJsonDocument::Compact);auto cipher=Vault::protect(clear);clear.fill('\0');QSaveFile f(journalPath());check(f.open(QIODevice::WriteOnly)&&f.write(cipher)==cipher.size()&&f.commit(),"RECOVERY_JOURNAL_WRITE_FAILED");}
void RouterTools::loadJournal(){journal={};QFile f(journalPath());if(!f.exists())return;check(f.open(QIODevice::ReadOnly)&&f.size()<=20*1024*1024,"RECOVERY_JOURNAL_UNREADABLE");auto clear=Vault::unprotect(f.readAll());QJsonParseError error;journal=QJsonDocument::fromJson(clear,&error).object();clear.fill('\0');check(error.error==QJsonParseError::NoError,"RECOVERY_JOURNAL_INVALID");}
void RouterTools::evaluate(){report={};auto add=[&](QString key,QString menu,bool ready,QString detail){report.append(QJsonObject{{"check",key},{"state",unavailable.contains(menu)?"UNKNOWN":ready?"READY":"NEEDS_SETUP"},{"detail",detail}});};auto internet=wan(tables);bool route=false;for(auto r:rows(tables,"ip/route"))if(r["dst-address"]=="0.0.0.0/0"&&enabled(r)&&yes(r,"active"))route=true;add("Default route","ip/route",route,internet);auto iface=find(tables,"interface","name",internet);add("WAN","interface",!iface.isEmpty()&&enabled(iface)&&yes(iface,"running"),internet);auto dns=rows(tables,"ip/dns");add("DNS","ip/dns",!dns.isEmpty()&&(!str(dns.first(),"servers").isEmpty()||!str(dns.first(),"dynamic-servers").isEmpty()),dns.isEmpty()?"":str(dns.first(),"servers"));auto resources=rows(tables,"system/resource");auto resource=resources.isEmpty()?QJsonObject{}:resources.first();add("CPU","system/resource",str(resource,"cpu-load").toInt()<90&&!resource.isEmpty(),str(resource,"cpu-load")+"%");auto total=str(resource,"total-memory").toLongLong(),free=str(resource,"free-memory").toLongLong();add("RAM","system/resource",total>0&&free>total/10,QString::number(free)+" / "+QString::number(total));add("Storage","system/resource",str(resource,"free-hdd-space").toLongLong()>2000000,str(resource,"free-hdd-space"));for(auto m:{"interface/bridge","ip/dhcp-server","ip/dhcp-server/network","ip/pool","ip/hotspot","ip/hotspot/profile","ip/hotspot/user/profile","ip/service"}){bool ready=false;for(auto r:rows(tables,m))if(enabled(r)&&!yes(r,"invalid"))ready=true;add(m,m,ready,QString::number(rows(tables,m).size()));}for(auto profile:rows(tables,"ip/hotspot/profile")){auto directory=str(profile,"html-directory-override");if(directory.isEmpty())directory=str(profile,"html-directory");bool present=true;for(auto name:{"login.html","status.html","md5.js"})if(find(tables,"file","name",directory+"/"+name).isEmpty())present=false;add("Portal / "+str(profile,"name"),"file",present,directory);}for(auto error:unavailable)if(std::none_of(report.begin(),report.end(),[&](auto r){return r.toObject()["check"]==error;}))report.append(QJsonObject{{"check",error},{"state","UNKNOWN"},{"detail","تعذرت قراءة القسم • Could not read section"}});}
void RouterTools::launch(QString op,QJsonObject fields){if(working||client->busy())return;working=true;message="جارٍ العمل • Working";emit changed();job=run(op,fields);job.start();}
void RouterTools::inspect(){launch("inspect");}void RouterTools::planHotspot(QJsonObject r){launch("hotspot_plan",r);}void RouterTools::planPorts(QString client,QString internet){launch("ports_plan",{{"client",client},{"wan",internet}});}void RouterTools::planDns(QStringList networks,QString mode){QJsonArray ids;for(auto id:networks)ids.append(id);launch("dns_plan",{{"ids",ids},{"mode",mode}});}void RouterTools::apply(QString password){launch("apply",{{"password",password}});}void RouterTools::restoreDns(){launch("dns_restore");}void RouterTools::synchronizeClock(){launch("clock");}void RouterTools::backup(QString password){launch("backup",{{"password",password}});}void RouterTools::restoreBackup(QString file,QString password){launch("backup_restore",{{"file",file},{"password",password}});}void RouterTools::exportConfiguration(){launch("export");}void RouterTools::reboot(){launch("reboot");}void RouterTools::flushDns(){launch("flush_dns");}void RouterTools::subscriber(QString op,QString id,QJsonObject fields){fields["id"]=id;fields["action"]=op;launch("subscriber",fields);}void RouterTools::previewPortal(QJsonObject design){try{auto files=renderPortal(design);preview=str(files,"login.html");auto dir=QStandardPaths::writableLocation(QStandardPaths::CacheLocation)+"/portal-preview";QDir().mkpath(dir);for(auto name:files.keys()){QSaveFile f(dir+"/"+name);auto bytes=str(files,name).toUtf8();check(f.open(QIODevice::WriteOnly)&&f.write(bytes)==bytes.size()&&f.commit(),"PORTAL_PREVIEW_WRITE_FAILED");}QDesktopServices::openUrl(QUrl::fromLocalFile(dir+"/login.html"));message="فُتحت معاينة صفحة الدخول • Portal preview opened";}catch(const std::exception&e){message=e.what();}emit changed();}void RouterTools::installPortal(QString profile,QJsonObject design){launch("portal_install",{{"profile",profile},{"design",design}});}void RouterTools::restorePortal(){launch("portal_restore");}
RouterJob RouterTools::run(QString operation,QJsonObject fields){bool nested=fields["_nested"].toBool();QString failure;QJsonArray recovery;QJsonObject plan;
 try{
  loadJournal();bool collect=QStringList{"inspect","hotspot_plan","ports_plan","dns_plan","apply","dns_restore"}.contains(operation);
  if(collect){tables={};unavailable.clear();for(auto menu:inspectionMenus()){auto result=co_await call(menu,"print",{},false);tables[menu]=result.rows;if(!result.ok())unavailable.insert(menu);}evaluate();emit changed();}
  if(operation=="inspect"){auto probe=co_await call("ping","",{{"address","1.1.1.1"},{"count","3"},{"interval","300ms"}},false);int received=0;for(auto r:probe.rows)if(!str(r.toObject(),"time").isEmpty()&&str(r.toObject(),"status").isEmpty())received++;report.append(QJsonObject{{"check","Internet probe"},{"state",probe.ok()&&received>0?"READY":"UNKNOWN"},{"detail",QString::number(received)+" responses"}});message="اكتمل فحص الراوتر • Router inspection complete";}
  else if(operation.endsWith("_plan")){QStringList required=operation=="dns_plan"?QStringList{"ip/dns","ip/dhcp-server/network","ip/dhcp-client","interface/pppoe-client","interface"}:QStringList{"interface","interface/bridge","interface/bridge/port","interface/vlan","interface/list/member","ip/address","ip/route","ip/pool","ip/dns","ip/dhcp-server","ip/dhcp-server/network","ip/hotspot","ip/hotspot/profile","file","ip/firewall/nat","ip/firewall/filter"};for(auto menu:required)check(!unavailable.contains(menu),"CONFIGURATION_READ_REQUIRED: "+menu);if(operation=="hotspot_plan")pending=hotspotPlan(tables,fields,client->identityKey());else if(operation=="ports_plan")pending=portsPlan(tables,str(fields,"client"),str(fields,"wan"),client->identityKey());else{QSet<QString> ids;for(auto id:fields["ids"].toArray())ids.insert(id.toString());pending=dnsPlan(tables,ids,str(fields,"mode"));}pending["signature"]=signature();pending["fingerprint"]=fingerprint();pending["connection"]=client->identityKey();message="الخطة جاهزة للمراجعة • Plan ready for review";}
  else if(operation=="backup"||operation=="apply"){
   auto password=str(fields,"password");check(password.size()>=12,"BACKUP_PASSWORD_SHORT");if(operation=="apply"){check(!pending.isEmpty()&&pending["signature"]==signature()&&pending["fingerprint"]==fingerprint()&&pending["connection"]==client->identityKey(),"CONFIGURATION_CHANGED_REVIEW_NEW_PLAN");plan=pending;}
   auto name="fg-mtm-"+QString::number(QDateTime::currentMSecsSinceEpoch())+"-"+QUuid::createUuid().toString(QUuid::WithoutBraces).left(4);co_await call("system/backup","save",{{"name",name},{"password",password},{"encryption","aes-sha256"}});auto files=co_await call("file");bool exists=false;for(auto r:files.rows)if(r.toObject()["name"]==name+".backup")exists=true;check(exists,"BACKUP_NOT_VERIFIED");auto passwords=journal["backups"].toObject();passwords[name+".backup"]=password;journal["backups"]=passwords;persist();message="نسخة الراوتر: "+name+".backup • Router backup: "+name+".backup";
   if(operation=="apply"){
    plan["backup"]=name+".backup";plan["state"]="APPLYING";journal["recovery"]=plan;persist();
    for(auto value:plan["changes"].toArray()){
     auto step=value.toObject();QString menu=str(step,"menu"),action=str(step,"action");auto attrs=step["attributes"].toObject();auto before=step["undo"].toObject();auto id=str(attrs,".id");if(action=="set"){auto read=co_await call(menu);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",id);check(!current.isEmpty()&&valuesEqual(current,before),"CONFIGURATION_CHANGED_DURING_APPLY");}
     recovery.append(step);journal["attempted"]=recovery;persist();auto reply=co_await call(menu,action,attrs,false);if(!reply.ok())throw std::runtime_error((reply.error+(reply.uncertain?"; CHANGE_OUTCOME_UNKNOWN":"")).toStdString());
     if(action=="add"){id=reply.rows.isEmpty()?QString{}:str(reply.rows.first().toObject(),".id");auto read=co_await call(menu);if(id.isEmpty()){int matches=0;for(auto r:read.rows)if(valuesEqual(r.toObject(),attrs)){id=str(r.toObject(),".id");matches++;}check(matches==1&&!id.isEmpty(),"CREATED_ITEM_NOT_VERIFIED");}step["created_id"]=id;recovery[recovery.size()-1]=step;check(valuesEqual(find(QJsonObject{{menu,read.rows}},menu,".id",id),attrs),"CREATE_VERIFY_FAILED");}
     else{auto read=co_await call(menu);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",id);check(valuesEqual(current,attrs),"SET_VERIFY_FAILED");}
     journal["attempted"]=recovery;persist();
    }
    if(plan["kind"]=="HOTSPOT"){
     if(plan["request"].toObject()["synchronizeTime"].toBool(true))co_await run("clock",{{"_nested",true}});
     if(plan["installPortal"].toBool()){auto profiles=co_await call("ip/hotspot/profile");auto profile=find(QJsonObject{{"profiles",profiles.rows}},"profiles","name",str(plan,"profileName"));check(!str(profile,".id").isEmpty(),"HOTSPOT_PROFILE_VERIFY_FAILED");co_await run("portal_install",{{"_nested",true},{"profile",profile[".id"]},{"design",plan["request"].toObject()["design"]}});}
    }
    plan["state"]="ACTIVE";plan["changes"]=recovery;if(plan["kind"]=="DNS"){auto dns=co_await call("ip/dns");auto dynamic=dns.rows.isEmpty()?QString{}:str(dns.rows.first().toObject(),"dynamic-servers");for(auto server:dynamic.split(',',Qt::SkipEmptyParts))check(str(plan,"servers").split(',').contains(server.trimmed()),"DYNAMIC_DNS_REVIEW");co_await call("ip/dns/cache","flush");journal["dns"]=plan;}journal["recovery"]=plan;persist();pending={};message="تم تطبيق الخطة والتحقق منها • Plan applied and verified";
   }
  }
  else if(operation=="dns_restore"){
   auto receipt=journal["dns"].toObject();check(!receipt.isEmpty()&&receipt["fingerprint"]==fingerprint()&&receipt["connection"]==client->identityKey(),"DNS_RECEIPT_OR_ROUTER_MISMATCH");auto changes=receipt["changes"].toArray();for(int i=changes.size()-1;i>=0;i--){auto step=changes[i].toObject();auto menu=str(step,"menu");auto after=step["attributes"].toObject(),before=step["undo"].toObject();auto read=co_await call(menu);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",str(after,".id"));for(auto k:after.keys())check(normalized(str(current,k))==normalized(str(after,k))||normalized(str(current,k))==normalized(str(before,k)),"DNS_RESTORE_CONFLICT");co_await call(menu,"set",before);auto verified=co_await call(menu);auto row=menu=="ip/dns"?(verified.rows.isEmpty()?QJsonObject{}:verified.rows.first().toObject()):find(QJsonObject{{menu,verified.rows}},menu,".id",str(before,".id"));check(valuesEqual(row,before),"DNS_RESTORE_VERIFY_FAILED");}co_await call("ip/dns/cache","flush");journal.remove("dns");persist();message="تمت استعادة إعدادات DNS السابقة • Previous DNS settings restored";
  }
  else if(operation=="clock"){
   auto previous=co_await call("system/clock");check(previous.rows.size()==1,"CLOCK_READ_REQUIRED");auto ntp=co_await call("system/ntp/client");check(!ntp.rows.isEmpty(),"NTP_READ_REQUIRED");auto servers=co_await call("system/ntp/client/servers");auto now=QDateTime::currentDateTime();auto zone=QString::fromUtf8(QTimeZone::systemTimeZoneId());co_await call("system/clock","set",{{"time-zone-autodetect","no"},{"time-zone-name",zone}});auto date=str(previous.rows.first().toObject(),"date").contains('-')?now.date().toString("yyyy-MM-dd"):QLocale(QLocale::English).toString(now.date(),"MMM/dd/yyyy").toLower();co_await call("system/clock","set",{{"date",date}});co_await call("system/clock","set",{{"time",now.time().toString("HH:mm:ss")}});bool active=false;for(auto r:servers.rows)if(!str(r.toObject(),"address").isEmpty()&&!QStringList{"no","false"}.contains(str(r.toObject(),"enabled")))active=true;if(!active)for(auto address:{"time.cloudflare.com","time.google.com"}){auto old=find(QJsonObject{{"servers",servers.rows}},"servers","address",address);if(old.isEmpty())co_await call("system/ntp/client/servers","add",{{"address",address}});else{check(!str(old,".id").isEmpty(),"TARGET_ID_REQUIRED");co_await call("system/ntp/client/servers","set",{{".id",old[".id"]},{"enabled","yes"}});}}if(!yes(ntp.rows.first().toObject(),"enabled"))co_await call("system/ntp/client","set",{{"enabled","yes"}});auto verified=co_await call("system/clock");auto clock=verified.rows.first().toObject();auto d=QDate::fromString(str(clock,"date"),"yyyy-MM-dd");if(!d.isValid())d=QLocale(QLocale::English).toDate(str(clock,"date"),"MMM/dd/yyyy");auto time=QTime::fromString(str(clock,"time").left(8),"HH:mm:ss");QDateTime local(d,time,QTimeZone::systemTimeZone());check(d.isValid()&&time.isValid()&&std::abs(local.secsTo(now))<120,"CLOCK_VERIFY_FAILED");auto enabledNtp=co_await call("system/ntp/client");check(!enabledNtp.rows.isEmpty()&&yes(enabledNtp.rows.first().toObject(),"enabled"),"NTP_VERIFY_FAILED");message="تم ضبط الساعة وتفعيل NTP • Clock verified and NTP enabled";
  }
  else if(operation=="subscriber"){
   auto id=str(fields,"id"),action=str(fields,"action");check(!id.isEmpty(),"SELECT_SUBSCRIBER");auto response=co_await call("ip/hotspot/user");auto user=find(QJsonObject{{"users",response.rows}},"users",".id",id);check(!user.isEmpty(),"SUBSCRIBER_NOT_FOUND");auto username=str(user,"name");if(action=="enable"||action=="disable")co_await call("ip/hotspot/user",action,{{".id",id}});if(action=="disconnect"||action=="disable"||action=="delete"){auto active=co_await call("ip/hotspot/active");for(auto value:active.rows){auto row=value.toObject();if(row["user"]==username){check(!str(row,".id").isEmpty(),"TARGET_ID_REQUIRED");co_await call("ip/hotspot/active","remove",{{".id",row[".id"]}});}}}if(action=="delete"){co_await call("ip/hotspot/user","remove",{{".id",id}});auto schedulers=co_await call("system/scheduler");for(auto value:schedulers.rows){auto r=value.toObject();if(r["comment"]=="FG MTM voucher expiry for "+username)co_await call("system/scheduler","remove",{{".id",r[".id"]}});}}
   else if(action=="update"){auto attrs=fields["attributes"].toObject();for(auto key:attrs.keys())check(QStringList{"profile","server","comment","limit-uptime","limit-bytes-total","password"}.contains(key),"INVALID_USER_FIELD");attrs[".id"]=id;co_await call("ip/hotspot/user","set",attrs);}
   else if(action=="add_time"){auto seconds=str(fields,"seconds").toLongLong();check(seconds>=60&&seconds<=31536000,"INVALID_DURATION");auto value=str(user,"limit-uptime");qint64 current=0;auto matches=QRegularExpression("([0-9]+)(w|d|h|m|s)").globalMatch(value);QString consumed;while(matches.hasNext()){auto m=matches.next();consumed+=m.captured();auto n=m.captured(1).toLongLong();auto unit=m.captured(2);auto factor=unit=="w"?604800:unit=="d"?86400:unit=="h"?3600:unit=="m"?60:1;check(n<=(std::numeric_limits<qint64>::max()-current)/factor,"DURATION_OVERFLOW");current+=n*factor;}if(QRegularExpression("^[0-9]+:[0-9]{2}:[0-9]{2}$").match(value).hasMatch()){auto parts=value.split(':');current=parts[0].toLongLong()*3600+parts[1].toInt()*60+parts[2].toInt();}else check(consumed==value,"UNKNOWN_ROUTER_DURATION");check(current>0&&current<=std::numeric_limits<qint64>::max()-seconds,"UNLIMITED_OR_INVALID_DURATION");co_await call("ip/hotspot/user","set",{{".id",id},{"limit-uptime",QString::number(current+seconds)+"s"}});}
   auto users=co_await call("ip/hotspot/user");tables["ip/hotspot/user"]=users.rows;message="تم تحديث المشترك • Subscriber updated";
  }
  else if(operation=="portal_install"){
   auto response=co_await call("ip/hotspot/profile");auto profile=find(QJsonObject{{"profiles",response.rows}},"profiles",".id",str(fields,"profile"));check(!profile.isEmpty(),"PROFILE_NOT_FOUND");auto files=renderPortal(fields["design"].toObject());auto existing=co_await call("file");bool flash=!find(QJsonObject{{"files",existing.rows}},"files","name","flash").isEmpty();auto directory=QString(flash?"flash/":"")+"fg-mtm-"+QString::number(QDateTime::currentMSecsSinceEpoch());co_await call("file","add",{{"name",directory},{"type","directory"}});for(auto name:files.keys()){auto path=directory+"/"+name;co_await call("file","add",{{"name",path},{"type","file"}});auto read=co_await call("file");auto file=find(QJsonObject{{"files",read.rows}},"files","name",path);check(!str(file,".id").isEmpty(),"PORTAL_FILE_CREATE_FAILED");co_await call("file","set",{{".id",file[".id"]},{"contents",files[name]}});auto verified=co_await call("file");check(find(QJsonObject{{"files",verified.rows}},"files",".id",str(file,".id"))["contents"]==files[name],"PORTAL_UPLOAD_VERIFY_FAILED");}
   QJsonObject receipt{{"profile",profile[".id"]},{"name",profile["name"]},{"before",QJsonObject{{"html-directory",str(profile,"html-directory")},{"html-directory-override",str(profile,"html-directory-override")}}},{"directory",directory},{"connection",client->identityKey()},{"state","APPLYING"}};journal["portal"]=receipt;persist();auto pointer=directory+"/rollback.txt";co_await call("file","add",{{"name",pointer},{"type","file"}});auto list=co_await call("file");auto pointerFile=find(QJsonObject{{"files",list.rows}},"files","name",pointer);check(!str(pointerFile,".id").isEmpty(),"ROLLBACK_POINTER_FAILED");co_await call("file","set",{{".id",pointerFile[".id"]},{"contents","profile="+str(profile,"name")+"\nhtml-directory="+str(profile,"html-directory")+"\nhtml-directory-override="+str(profile,"html-directory-override")}});co_await call("ip/hotspot/profile","set",{{".id",profile[".id"]},{"html-directory",directory},{"html-directory-override",""}});auto verify=co_await call("ip/hotspot/profile");auto current=find(QJsonObject{{"profiles",verify.rows}},"profiles",".id",str(profile,".id"));check(current["html-directory"]==directory&&str(current,"html-directory-override").isEmpty(),"PORTAL_BINDING_VERIFY_FAILED");receipt["state"]="ACTIVE";journal["portal"]=receipt;persist();message="تم تثبيت صفحة الدخول والتحقق منها • Portal installed and verified";
  }
  else if(operation=="portal_restore"){
   auto receipt=journal["portal"].toObject();check(!receipt.isEmpty()&&receipt["connection"]==client->identityKey(),"PORTAL_RECOVERY_MISSING");auto response=co_await call("ip/hotspot/profile");auto profile=find(QJsonObject{{"profiles",response.rows}},"profiles",".id",str(receipt,"profile"));check(profile["name"]==receipt["name"]&&profile["html-directory"]==receipt["directory"],"PORTAL_RESTORE_CONFLICT");auto attrs=receipt["before"].toObject();attrs[".id"]=receipt["profile"];co_await call("ip/hotspot/profile","set",attrs);auto verify=co_await call("ip/hotspot/profile");check(valuesEqual(find(QJsonObject{{"profiles",verify.rows}},"profiles",".id",str(receipt,"profile")),attrs),"PORTAL_RESTORE_VERIFY_FAILED");journal.remove("portal");persist();message="استعيدت صفحة الدخول السابقة • Previous portal restored";
  }
  else if(operation=="backup_restore"){auto files=co_await call("file");auto file=str(fields,"file");check(file.endsWith(".backup")&&!find(QJsonObject{{"files",files.rows}},"files","name",file).isEmpty(),"SELECT_EXISTING_BACKUP");co_await call("system/backup","load",{{"name",file},{"password",fields["password"]}});message="أُرسل طلب الاستعادة • Restore request sent";}
  else if(operation=="export"){auto resource=co_await call("system/resource");auto name="fg-mtm-export-"+QString::number(QDateTime::currentMSecsSinceEpoch());QJsonObject attrs{{"file",name}};if(!resource.rows.isEmpty()&&str(resource.rows.first().toObject(),"version").startsWith("6."))attrs["hide-sensitive"]="yes";co_await call("export","",attrs);auto files=co_await call("file");check(!find(QJsonObject{{"files",files.rows}},"files","name",name+".rsc").isEmpty(),"EXPORT_VERIFY_FAILED");message="تم تصدير إعدادات الراوتر: "+name+".rsc • Router configuration exported: "+name+".rsc";}
  else if(operation=="reboot"){co_await call("system","reboot");message="أُرسل طلب إعادة التشغيل • Reboot request sent";}
  else if(operation=="flush_dns"){co_await call("ip/dns/cache","flush");message="مُسحت ذاكرة DNS • DNS cache flushed";}
 }catch(const std::exception&e){failure=QString::fromUtf8(e.what());}
 if(!failure.isEmpty()){
  QStringList failed;
  for(int i=recovery.size()-1;i>=0;i--){auto step=recovery[i].toObject();auto menu=str(step,"menu"),action=str(step,"action");auto attrs=step["attributes"].toObject();RouterReply result;try{if(action=="add"){auto id=str(step,"created_id");if(id.isEmpty()){auto read=co_await call(menu,"print",{},false);int count=0;for(auto r:read.rows)if(valuesEqual(r.toObject(),attrs)){id=str(r.toObject(),".id");count++;}if(!read.ok()||count!=1||id.isEmpty()){failed.append(menu);continue;}}result=co_await call(menu,"remove",{{".id",id}},false);}else{auto read=co_await call(menu,"print",{},false);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",str(attrs,".id"));auto before=step["undo"].toObject();bool owned=!current.isEmpty();for(auto k:attrs.keys())if(normalized(str(current,k))!=normalized(str(attrs,k))&&normalized(str(current,k))!=normalized(str(before,k)))owned=false;if(!read.ok()||!owned){failed.append(menu);continue;}result=co_await call(menu,"set",before,false);}if(!result.ok())failed.append(menu);}catch(...){failed.append(menu);}}
  if(!recovery.isEmpty()){auto r=journal["recovery"].toObject();r["state"]=failed.isEmpty()?"ROLLED_BACK":"REVIEW";journal["recovery"]=r;try{persist();}catch(...){failed.append("journal");}}
  if(operation=="portal_install"&&journal["portal"].isObject()){auto receipt=journal["portal"].toObject();auto before=receipt["before"].toObject();before[".id"]=receipt["profile"];auto rollback=co_await call("ip/hotspot/profile","set",before,false);if(!rollback.ok())failed.append("portal");}
  message=failure+(failed.isEmpty()?QString{}:" — تحتاج مراجعة: "+failed.join(',')+" • Recovery needs review: "+failed.join(','));
 }
 if(nested){if(!failure.isEmpty())throw std::runtime_error(message.toStdString());co_return;}working=false;emit changed();co_return;
}
