#include <optional>
#include <QImageReader>
#include <QImage>
#include <QBuffer>
#include <QSettings>
#include "RouterTools.hpp"
#include "Vouchers.hpp"
#include "Vault.hpp"
#include <QHostAddress>
#include <QCryptographicHash>
#include <QJsonDocument>
#include <QFile>
#include <QSaveFile>
#include <QDir>
#include <QStandardPaths>
#include <QDateTime>
#include <QTimeZone>
#include <QLocale>
#include <QUuid>
#include <QRegularExpression>
#include <algorithm>
#include <QDesktopServices>
#include <limits>
namespace {
void check(bool ok,QString why){if(!ok)throw std::runtime_error(why.toStdString());}
QString str(QJsonObject o,QString key,QString fallback={}){auto value=o.value(key);if(value.isString())return value.toString();if(value.isBool())return value.toBool()?"true":"false";if(value.isDouble())return Protocol::jsonText(value);return fallback;}
bool yes(QJsonObject o,QString key){return o[key]=="yes"||o[key]=="true"||o[key]==true;}
bool enabled(QJsonObject o){return !yes(o,"disabled");}
QList<QJsonObject> rows(QJsonObject tables,QString menu){QList<QJsonObject> out;for(auto value:tables[menu].toArray())out.append(value.toObject());return out;}
QJsonObject find(QJsonObject tables,QString menu,QString key,QString value){for(auto r:rows(tables,menu))if(r[key]==value)return r;return {};}
quint32 ip(QString value){QHostAddress a;check(a.setAddress(value)&&a.protocol()==QAbstractSocket::IPv4Protocol,"INVALID_IP");return a.toIPv4Address();}
quint32 mask(int n){return quint32(0xffffffffu<<(32-n));}
bool belongs(QString value,QString cidr){return (ip(value)&mask(cidr.section('/',1).toInt()))==ip(RouterTools::network(cidr).section('/',0,0));}
bool overlaps(QString a,QString b){return belongs(a.section('/',0,0),b)||belongs(b.section('/',0,0),a);}
QJsonObject change(QString menu,QString action,QJsonObject after,QJsonObject before={},QString label={}){return {{"menu",menu},{"action",action},{"attributes",after},{"undo",before},{"label",label}};}
QString normalized(QString v){if(v=="true")return "yes";if(v=="false")return "no";return v.remove(' ');}
bool valuesEqual(QJsonObject row,QJsonObject expected){for(auto it=expected.begin();it!=expected.end();++it)if(normalized(str(row,it.key()))!=normalized(it.value().toString()))return false;return true;}
QStringList inspectionMenus(){return {"system/resource","system/clock","interface","interface/bridge","interface/bridge/port","interface/vlan","ip/dhcp-client","interface/pppoe-client","interface/list/member","ip/address","ip/route","ip/firewall/nat","ip/firewall/filter","ip/dns","ip/dhcp-server","ip/dhcp-server/network","ip/pool","ip/hotspot","ip/hotspot/profile","ip/hotspot/user/profile","ip/service","user","system/scheduler","file","ip/hotspot/user","ip/hotspot/active"};}
QJsonObject detectWanEvidence(QJsonObject t){
 struct Candidate{QString name,source,table;int score=-1;int distance=std::numeric_limits<int>::max();};
 Candidate best;
 auto interfaceRow=[&](QString name){return find(t,"interface","name",name);};
 auto consider=[&](QString name,QString source,int score,int distance=std::numeric_limits<int>::max(),QString table={}){
  name=name.trimmed();auto iface=interfaceRow(name);if(name.isEmpty()||iface.isEmpty()||!enabled(iface))return;
  if(score>best.score||(score==best.score&&distance<best.distance))best={name,source,table,score,distance};
 };
 for(auto r:rows(t,"ip/route"))if(str(r,"dst-address")=="0.0.0.0/0"&&enabled(r)&&yes(r,"active")){
  bool ok=false;int distance=str(r,"distance","1").toInt(&ok);if(!ok||distance<0)distance=1;
  auto table=str(r,"routing-table");auto immediate=str(r,"immediate-gw").section(',',0,0).trimmed();QString name;
  if(immediate.contains('%'))name=immediate.section('%',1).trimmed();else if(!interfaceRow(immediate).isEmpty())name=immediate;
  if(name.isEmpty()){auto gateway=str(r,"gateway").section(',',0,0).trimmed();if(gateway.contains('%'))name=gateway.section('%',1).trimmed();else if(!interfaceRow(gateway).isEmpty())name=gateway;}
  consider(name,"Active default route",1000-std::min(distance,100)-((!table.isEmpty()&&table.compare("main",Qt::CaseInsensitive)!=0)?50:0),distance,table);
 }
 for(auto r:rows(t,"ip/dhcp-client"))if(enabled(r)&&str(r,"status").compare("bound",Qt::CaseInsensitive)==0)consider(str(r,"interface"),"Bound DHCP client",850);
 for(auto r:rows(t,"interface/pppoe-client"))if(enabled(r)&&(yes(r,"running")||str(r,"status").compare("connected",Qt::CaseInsensitive)==0||str(r,"status").compare("bound",Qt::CaseInsensitive)==0))consider(str(r,"interface"),"Connected PPPoE client",830);
 for(auto r:rows(t,"interface/list/member"))if(str(r,"list").compare("WAN",Qt::CaseInsensitive)==0)consider(str(r,"interface"),"RouterOS WAN interface list",760);
 for(auto r:rows(t,"interface"))if(enabled(r)&&yes(r,"running")&&(str(r,"type").compare("lte",Qt::CaseInsensitive)==0||str(r,"name").startsWith("lte",Qt::CaseInsensitive)))consider(str(r,"name"),"Running LTE interface",650);
 if(best.name.isEmpty())return {};
 QJsonObject result{{"name",best.name},{"source",best.source},{"confidence",best.score>=800?"high":"medium"}};
 if(best.distance!=std::numeric_limits<int>::max())result["distance"]=best.distance;if(!best.table.isEmpty())result["routingTable"]=best.table;return result;
}
QString wan(QJsonObject t){return str(detectWanEvidence(t),"name");}
bool natServes(QJsonObject r,QString cidr,QString internet){if(!enabled(r)||r["chain"]!="srcnat"||!QStringList{"masquerade","src-nat"}.contains(str(r,"action")))return false;auto output=str(r,"out-interface");if(!output.isEmpty()&&!internet.isEmpty()&&output!=internet)return false;auto source=str(r,"src-address");return source.isEmpty()||source=="0.0.0.0/0"||RouterTools::validCidr(source)&&belongs(cidr.section('/',0,0),source)&&source.section('/',1).toInt()<=cidr.section('/',1).toInt();}
}
RouterTools::RouterTools(RouterClient*c,QObject*p):QObject(p),client(c){connect(client,&RouterClient::changed,this,[this]{if(!client->connected()){tables.remove("ip/hotspot/user");tables.remove("ip/hotspot/active");}emit changed();});}
RouterTools::~RouterTools(){lifetime.reset();}
QJsonObject RouterTools::detectWan(QJsonObject t){return detectWanEvidence(t);}
QVariantMap RouterTools::wanDetection()const{return detectWanEvidence(tables).toVariantMap();}
QVariantList RouterTools::clientInterfaces()const{QVariantList result;auto internet=wan(tables);for(auto value:tables["interface"].toArray()){auto row=value.toObject();if(str(row,"name")==internet||!enabled(row))continue;result.append(row.toVariantMap());}return result;}
namespace {
qint64 usageNumber(QJsonValue value){bool ok=false;auto n=Protocol::jsonText(value).toLongLong(&ok);return ok&&n>=0?n:-1;}
qint64 usageDuration(QString value){
 if(value.isEmpty())return -1;
 if(QRegularExpression("^[0-9]+$").match(value).hasMatch())return usageNumber(value);
 qint64 total=0;auto add=[&](QString n,qint64 factor){auto v=usageNumber(n);if(v<0||v>(std::numeric_limits<qint64>::max()-total)/factor)return false;total+=v*factor;return true;};
 auto clock=QRegularExpression("^(?:([0-9]+)w)?(?:([0-9]+)d)?([0-9]+):([0-9]{2}):([0-9]{2})$").match(value);
 if(clock.hasMatch()){if(clock.captured(4).toInt()>59||clock.captured(5).toInt()>59)return -1;for(int i=1;i<=5;i++)if(!clock.captured(i).isEmpty()&&!add(clock.captured(i),i==1?604800:i==2?86400:i==3?3600:i==4?60:1))return -1;return total;}
 auto matches=QRegularExpression("([0-9]+)(w|d|h|m|s)").globalMatch(value);QString consumed;
 while(matches.hasNext()){auto m=matches.next();consumed+=m.captured();auto u=m.captured(2);if(!add(m.captured(1),u=="w"?604800:u=="d"?86400:u=="h"?3600:u=="m"?60:1))return -1;}return consumed==value?total:-1;
}
qint64 usageSum(qint64 a,qint64 b){return a<0||b<0||b>std::numeric_limits<qint64>::max()-a?-1:a+b;}
}
QJsonObject RouterTools::subscriberUsage(QJsonObject user,QJsonArray sessions,bool known){
 auto result=user;auto name=str(user,"name");qint64 used=usageDuration(str(user,"uptime")),up=usageNumber(user["bytes-in"]),down=usageNumber(user["bytes-out"]);int count=0;
 for(auto value:sessions){auto session=value.toObject();if(session["user"]!=name)continue;count++;used=usageSum(used,usageDuration(str(session,"uptime")));up=usageSum(up,usageNumber(session["bytes-in"]));down=usageSum(down,usageNumber(session["bytes-out"]));}
 auto timeLimit=usageDuration(str(user,"limit-uptime")),dataLimit=usageNumber(user["limit-bytes-total"]),bytes=usageSum(up,down);
 auto metric=[&](QString key,qint64 value){result[key]=known&&value>=0?QJsonValue(QString::number(value)):QJsonValue(QJsonValue::Null);};
 result["sessionsKnown"]=known;result["sessionCount"]=known?QJsonValue(count):QJsonValue(QJsonValue::Null);
 metric("usedSeconds",used);metric("uploadBytes",up);metric("downloadBytes",down);metric("usedBytes",bytes);
 metric("remainingSeconds",timeLimit>0&&used>=0?std::max(qint64(0),timeLimit-used):-1);
 metric("remainingBytes",dataLimit>0&&bytes>=0?std::max(qint64(0),dataLimit-bytes):-1);
 result["usageState"]=known&&((timeLimit>0&&used>=timeLimit)||(dataLimit>0&&bytes>=dataLimit))?"EXPIRED":!enabled(user)?"DISABLED":!known?"UNKNOWN":count>0?"ACTIVE":"OFFLINE";
 return Protocol::redact(result).toObject();
}
QVariantList RouterTools::users()const{QVariantList result;if(!client->authorized()||!client->connected())return result;for(auto value:tables["ip/hotspot/user"].toArray())result.append(subscriberUsage(value.toObject(),tables["ip/hotspot/active"].toArray(),sessionsKnown()).toVariantMap());return result;}
bool RouterTools::validCidr(QString cidr){auto parts=cidr.split('/');QHostAddress a;return parts.size()==2&&a.setAddress(parts[0])&&a.protocol()==QAbstractSocket::IPv4Protocol&&QRegularExpression("^[0-9]+$").match(parts[1]).hasMatch()&&parts[1].toInt()>=1&&parts[1].toInt()<=30;}
QString RouterTools::network(QString cidr){check(validCidr(cidr),"INVALID_CIDR");auto p=cidr.section('/',1).toInt();return QHostAddress(ip(cidr.section('/',0,0))&mask(p)).toString()+"/"+QString::number(p);}
bool RouterTools::privateSubnet(QString cidr){if(!validCidr(cidr)||network(cidr)!=cidr)return false;auto a=ip(cidr.section('/',0,0));auto prefix=cidr.section('/',1).toInt();return (a>>24==10&&prefix>=8)||((a>>20)==0xac1&&prefix>=12)||((a>>16)==0xc0a8&&prefix>=16)||((a>>22)==0x191&&prefix>=10);}
QJsonObject RouterTools::hotspotPlan(QJsonObject t,QJsonObject r,QString management){auto iface=str(r,"interface"),gateway=str(r,"gateway"),net=str(r,"network"),pool=str(r,"pool"),dnsName=str(r,"dnsName","wifi.local");check(validCidr(gateway)&&validCidr(net)&&network(gateway)==network(net),"INVALID_CLIENT_SUBNET");auto range=pool.remove(' ').split('-');check(range.size()==2&&belongs(range[0],net)&&belongs(range[1],net)&&ip(range[0])<=ip(range[1]),"INVALID_POOL");auto base=ip(network(net).section('/',0,0)),broadcast=base+~mask(net.section('/',1).toInt());check(ip(range[0])>base&&ip(range[1])<broadcast&&!(ip(gateway.section('/',0,0))>=ip(range[0])&&ip(gateway.section('/',0,0))<=ip(range[1])),"POOL_MUST_EXCLUDE_GATEWAY_NETWORK_BROADCAST");check(QRegularExpression("^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$").match(dnsName).hasMatch(),"INVALID_DNS_NAME");auto selected=find(t,"interface","name",iface);check(!selected.isEmpty()&&enabled(selected),"SELECT_ENABLED_CLIENT_INTERFACE");auto detected=detectWanEvidence(t);auto manual=str(r,"wan");auto internet=manual.isEmpty()?str(detected,"name"):manual;auto internetRow=find(t,"interface","name",internet);check(!internet.isEmpty(),"SELECT_WAN_INTERFACE");check(!internetRow.isEmpty()&&enabled(internetRow),"SELECT_ENABLED_WAN_INTERFACE");check(iface!=internet,"WAN_CANNOT_BE_CLIENT");for(auto a:rows(t,"ip/address"))if(a["interface"]!=iface&&validCidr(str(a,"address")))check(!overlaps(str(a,"address"),net),"SUBNET_OVERLAP");QJsonArray changes;auto tag="fg-mtm-"+QUuid::createUuid().toString(QUuid::WithoutBraces).left(8);bool hasAddress=false;for(auto a:rows(t,"ip/address"))if(a["interface"]==iface&&enabled(a)){check(a["address"]==gateway,"PRESERVE_EXISTING_GATEWAY");hasAddress=true;}if(!hasAddress)changes.append(change("ip/address","add",{{"address",gateway},{"interface",iface},{"comment","FG MTM client gateway"}},{},"إضافة بوابة العملاء • Add client gateway"));
 auto dhcp=find(t,"ip/dhcp-server","interface",iface);auto poolName=str(dhcp,"address-pool");if(poolName.isEmpty()||find(t,"ip/pool","name",poolName).isEmpty())poolName=str(find(t,"ip/pool","ranges",pool),"name");if(poolName.isEmpty()){poolName=tag;changes.append(change("ip/pool","add",{{"name",poolName},{"ranges",pool}},{},"إنشاء مدى العناوين • Create address pool"));}
 auto dns=t["ip/dns"].toArray().isEmpty()?QJsonObject{}:t["ip/dns"].toArray().first().toObject();if(str(dns,"servers").isEmpty()&&str(dns,"dynamic-servers").isEmpty())changes.append(change("ip/dns","set",{{"servers","1.1.1.1,9.9.9.9"}},{{"servers",str(dns,"servers")}},"ضبط DNS • Configure DNS"));
 if(find(t,"ip/dhcp-server/network","address",net).isEmpty())changes.append(change("ip/dhcp-server/network","add",{{"address",net},{"gateway",gateway.section('/',0,0)},{"dns-server",yes(dns,"allow-remote-requests")?gateway.section('/',0,0):"1.1.1.1,9.9.9.9"}},{},"إعداد شبكة DHCP • Configure DHCP network"));
 if(dhcp.isEmpty())changes.append(change("ip/dhcp-server","add",{{"name",tag},{"interface",iface},{"address-pool",poolName},{"disabled","no"}},{},"إنشاء DHCP • Create DHCP server"));else {check(!yes(dhcp,"invalid"),"DHCP_INVALID");auto id=str(dhcp,".id");check(!id.isEmpty(),"TARGET_ID_REQUIRED");if(!enabled(dhcp))changes.append(change("ip/dhcp-server","set",{{".id",id},{"disabled","no"}},{{".id",id},{"disabled",str(dhcp,"disabled")}},"تفعيل DHCP • Enable DHCP"));if(str(dhcp,"address-pool")!=poolName)changes.append(change("ip/dhcp-server","set",{{".id",id},{"address-pool",poolName}},{{".id",id},{"address-pool",str(dhcp,"address-pool")}},"ربط المدى • Assign DHCP pool"));}
 bool nat=false;for(auto row:rows(t,"ip/firewall/nat"))if(natServes(row,net,internet))nat=true;if(!nat&&!internet.isEmpty())changes.append(change("ip/firewall/nat","add",{{"chain","srcnat"},{"action","masquerade"},{"src-address",net},{"out-interface",internet},{"comment","FG MTM client internet"}},{},"مشاركة الإنترنت للعملاء • Add client NAT"));
 auto server=find(t,"ip/hotspot","interface",iface),profile=find(t,"ip/hotspot/profile","name",str(server,"profile"));auto profileName=str(profile,"name",tag);if(profile.isEmpty())changes.append(change("ip/hotspot/profile","add",{{"name",profileName},{"hotspot-address",gateway.section('/',0,0)},{"dns-name",dnsName},{"login-by","http-chap"}},{},"إعداد HotSpot • Create HotSpot profile"));else if(!str(profile,"login-by").split(',').contains("http-chap")&&!str(profile,"login-by").split(',').contains("https"))changes.append(change("ip/hotspot/profile","set",{{".id",profile[".id"]},{"login-by",str(profile,"login-by").isEmpty()?"http-chap":str(profile,"login-by")+",http-chap"}},{{".id",profile[".id"]},{"login-by",profile["login-by"]}},"دخول CHAP • Enable CHAP login"));
 if(t["ip/hotspot/user/profile"].toArray().isEmpty())changes.append(change("ip/hotspot/user/profile","add",{{"name","fg-default"},{"shared-users","1"}},{},"باقة افتراضية • Default voucher profile"));if(server.isEmpty())changes.append(change("ip/hotspot","add",{{"name",tag},{"interface",iface},{"profile",profileName},{"address-pool",poolName},{"disabled","no"}},{},"إنشاء HotSpot • Create HotSpot server"));else{check(!yes(server,"invalid"),"HOTSPOT_INVALID");if(!enabled(server))changes.append(change("ip/hotspot","set",{{".id",server[".id"]},{"disabled","no"}},{{".id",server[".id"]},{"disabled",server["disabled"]}},"تفعيل HotSpot • Enable HotSpot"));}
 auto directory=str(profile,"html-directory-override");if(directory.isEmpty())directory=str(profile,"html-directory");bool hasPortal=true;for(auto file:{"login.html","status.html","md5.js"})if(find(t,"file","name",directory+"/"+file).isEmpty())hasPortal=false;
 return {{"kind","HOTSPOT"},{"request",r},{"changes",changes},{"profileName",profileName},{"installPortal",r["replacePortal"].toBool()||profile.isEmpty()||!hasPortal},{"wan",internet},{"wanSource",manual.isEmpty()?str(detected,"source"):QString("Manual selection")}};
}
QJsonObject RouterTools::portsPlan(QJsonObject t,QString selected,QString internet,QString management){if(internet.isEmpty())internet=wan(t);check(!selected.isEmpty()&&!internet.isEmpty(),"WAN_CLIENT_REQUIRED");bool bridge=!find(t,"interface/bridge","name",selected).isEmpty();auto target=bridge?selected:"fg-clients";QSet<QString> occupied,protectedPorts;for(auto m:{"interface/bridge/port","interface/vlan","ip/dhcp-client","interface/pppoe-client"})for(auto r:rows(t,m)){occupied.insert(str(r,"interface"));protectedPorts.insert(str(r,"interface"));}protectedPorts.insert(internet);for(auto r:rows(t,"interface/list/member"))if(str(r,"list").compare("WAN",Qt::CaseInsensitive)==0)protectedPorts.insert(str(r,"interface"));for(auto m:{"ip/address","ip/dhcp-server","ip/hotspot"})for(auto r:rows(t,m))if(r["interface"]!=selected)occupied.insert(str(r,"interface"));for(auto r:rows(t,"ip/address"))if(r["interface"]==selected)check(!management.contains(str(r,"address").section('/',0,0)),"USE_WAN_SIDE_MANAGEMENT");if(!bridge){check(find(t,"interface","name",target).isEmpty()&&!protectedPorts.contains(selected)&&!occupied.contains(selected),"CLIENT_PORT_OCCUPIED");auto port=find(t,"interface","name",selected);check(port["type"]=="ether"||QRegularExpression("^ether[0-9]+$").match(selected).hasMatch(),"PHYSICAL_CLIENT_PORT_REQUIRED");for(auto m:{"ip/firewall/filter","ip/firewall/nat"})for(auto r:rows(t,m))check(r["in-interface"]!=selected&&r["out-interface"]!=selected,"INTERFACE_FIREWALL_REVIEW");}QJsonArray changes;if(!bridge){changes.append(change("interface/bridge","add",{{"name",target},{"comment","FG MTM customer network"}},{},"إنشاء جسر العملاء • Create client bridge"));for(auto m:{"ip/address","ip/dhcp-server","ip/hotspot","interface/list/member"})for(auto r:rows(t,m))if(r["interface"]==selected){check(!str(r,".id").isEmpty()&&!yes(r,"dynamic"),"DYNAMIC_CLIENT_SETTING");changes.append(change(m,"set",{{".id",r[".id"]},{"interface",target}},{{".id",r[".id"]},{"interface",selected}},"نقل الإعداد للجسر • Move client configuration"));}}
 QStringList ports;if(!bridge)ports.append(selected);for(auto r:rows(t,"interface")){auto n=str(r,"name");if(n!=selected&&!occupied.contains(n)&&!protectedPorts.contains(n)&&enabled(r)&&!yes(r,"running")&&(r["type"]=="ether"||QRegularExpression("^ether[0-9]+$").match(n).hasMatch()))ports.append(n);}for(auto port:ports)changes.append(change("interface/bridge/port","add",{{"bridge",target},{"interface",port}},{},"ضم المنفذ • Group port "+port));return {{"kind","PORTS"},{"changes",changes},{"bridge",target}};}
QJsonObject RouterTools::dnsPlan(QJsonObject t,QSet<QString> selected,QString mode){check(!selected.isEmpty()&&selected.size()<=32&&QStringList{"FAMILY","ADS_TRACKERS"}.contains(mode),"SELECT_CLIENT_NETWORK");auto servers=mode=="FAMILY"?"94.140.14.15,94.140.15.16":"94.140.14.14,94.140.15.15";QJsonArray changes;auto add=[&](QString menu,QJsonObject r,QJsonObject after){QJsonObject changed,before;for(auto it=after.begin();it!=after.end();++it)if(normalized(str(r,it.key()))!=normalized(it.value().toString())){changed[it.key()]=it.value();before[it.key()]=str(r,it.key());}if(!changed.isEmpty()){if(menu!="ip/dns"){changed[".id"]=r[".id"];before[".id"]=r[".id"];}auto step=change(menu,"set",changed,before,str(r,"address",menu));step["targetAddress"]=str(r,"address");step["targetInterface"]=str(r,"interface");changes.append(step);}};check(t["ip/dns"].toArray().size()==1,"DNS_READ_REQUIRED");auto dns=t["ip/dns"].toArray().first().toObject();QJsonObject settings{{"servers",servers}};if(dns.contains("use-doh-server"))settings["use-doh-server"]="";add("ip/dns",dns,settings);int count=0;for(auto r:rows(t,"ip/dhcp-server/network"))if(selected.contains(str(r,".id"))){check(privateSubnet(str(r,"address"))&&str(r,"dhcp-option").isEmpty()&&str(r,"dhcp-option-set").isEmpty(),"DHCP_OPTIONS_OR_PUBLIC_NETWORK_REVIEW");QJsonObject attrs{{"dns-server",servers}};if(r.contains("dns-none"))attrs["dns-none"]="no";add("ip/dhcp-server/network",r,attrs);count++;}check(count==selected.size(),"SELECT_CLIENT_NETWORK");for(auto menu:{"ip/dhcp-client","interface/pppoe-client"})for(auto r:rows(t,menu))if(enabled(r)&&yes(r,"use-peer-dns")){check(!str(r,".id").isEmpty(),"TARGET_ID_REQUIRED");add(menu,r,{{"use-peer-dns","no"}});}check(changes.size()<=128,"DNS_CHANGE_LIMIT");return {{"kind","DNS"},{"mode",mode},{"changes",changes},{"servers",servers}};}
QJsonObject RouterTools::renderPortal(QJsonObject design){auto color=str(design,"color","#159DFF");check(QRegularExpression("^#[a-fA-F0-9]{6}$").match(color).hasMatch(),"INVALID_COLOR");auto logo=str(design,"logoDataUri");if(!QRegularExpression("^data:image/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$").match(logo).hasMatch())logo.clear();auto website=str(design,"website");if(!website.startsWith("https://"))website.clear();QJsonObject assets;QDir dir(":/resources/hotspot");for(auto name:dir.entryList(QDir::Files)){QFile f(dir.filePath(name));check(f.open(QIODevice::ReadOnly),"PORTAL_ASSET_MISSING");auto content=QString::fromUtf8(f.readAll());for(auto pair:QList<QPair<QString,QString>>{{"NETWORK",str(design,"networkName","FG Machines WiFi").toHtmlEscaped()},{"PHONE",str(design,"supportPhone").toHtmlEscaped()},{"WELCOME",str(design,"welcome").toHtmlEscaped()},{"COLOR",color},{"TERMS",str(design,"terms").toHtmlEscaped()},{"WEBSITE",website.toHtmlEscaped()},{"LOGO",logo}})content.replace("@@"+pair.first+"@@",pair.second);check(content.toUtf8().size()<60000,"PORTAL_FILE_LIMIT");assets[name]=content;}check(assets.contains("login.html")&&assets.contains("status.html")&&assets.contains("md5.js"),"PORTAL_ASSET_MISSING");return assets;}
QString RouterTools::signature()const{QJsonObject stable;QSet<QString> keys{".id","name","interface","address","ranges","profile","address-pool","disabled","servers","allow-remote-requests","chain","action","src-address","out-interface","dst-address","gateway","login-by","dns-name","html-directory","html-directory-override","group","network","lease-time","dns-server","netmask","port","certificate","hotspot-address","in-interface","out-interface-list","in-interface-list","protocol","dst-port","src-port","bridge","pvid","vlan-id","vlan-filtering","connection-state","to-addresses","to-ports","list","use-doh-server","use-peer-dns","dns-none","dhcp-option","dhcp-option-set"};for(auto menu:tables.keys()){if(QStringList{"system/resource","system/clock","system/scheduler","ip/hotspot/user","ip/hotspot/active"}.contains(menu))continue;QStringList values;for(auto r:rows(tables,menu)){if(yes(r,"dynamic"))continue;if(menu=="file"&&!QStringList{"login.html","status.html","md5.js"}.contains(str(r,"name").section('/',-1)))continue;QJsonObject kept;for(auto k:r.keys())if(keys.contains(k))kept[k]=r[k];values.append(QString::fromUtf8(QJsonDocument(kept).toJson(QJsonDocument::Compact)));}values.sort();QJsonArray list;for(auto v:values)list.append(v);stable[menu]=list;}return QString::fromLatin1(QCryptographicHash::hash(QJsonDocument(stable).toJson(QJsonDocument::Compact),QCryptographicHash::Sha256).toHex());}
QString RouterTools::fingerprint()const{QStringList macs;for(auto r:rows(tables,"interface"))if(r["type"]=="ether"&&!str(r,"mac-address").isEmpty())macs.append(str(r,"mac-address").toUpper());macs.removeDuplicates();macs.sort();check(!macs.isEmpty(),"ROUTER_IDENTITY_REQUIRED");return QString::fromLatin1(QCryptographicHash::hash(macs.join(',').toUtf8(),QCryptographicHash::Sha256).toHex());}
QString RouterTools::journalPath()const{auto dir=QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation)+"/router-journals";QDir().mkpath(dir);return dir+"/"+QString::fromLatin1(QCryptographicHash::hash(client->identityKey().toUtf8(),QCryptographicHash::Sha256).toHex())+".fgj";}
void RouterTools::persist(){auto clear=QJsonDocument(journal).toJson(QJsonDocument::Compact);auto cipher=Vault::protect(clear);clear.fill('\0');QSaveFile f(journalPath());check(f.open(QIODevice::WriteOnly)&&f.write(cipher)==cipher.size()&&f.commit(),"RECOVERY_JOURNAL_WRITE_FAILED");}
void RouterTools::loadJournal(){journal={};QFile f(journalPath());if(!f.exists())return;check(f.open(QIODevice::ReadOnly)&&f.size()<=20*1024*1024,"RECOVERY_JOURNAL_UNREADABLE");auto clear=Vault::unprotect(f.readAll());QJsonParseError error;journal=QJsonDocument::fromJson(clear,&error).object();clear.fill('\0');check(error.error==QJsonParseError::NoError,"RECOVERY_JOURNAL_INVALID");}
QJsonArray RouterTools::readinessChecks(QJsonObject t,QSet<QString> missing,QString selected){
 QJsonArray result;auto detected=detectWanEvidence(t);auto internet=str(detected,"name");
 if(find(t,"interface","name",selected).isEmpty())selected.clear();
 if(selected.isEmpty()){for(auto r:rows(t,"ip/hotspot"))if(!str(r,"interface").isEmpty()){selected=str(r,"interface");break;}}
 if(selected.isEmpty()){for(auto r:rows(t,"interface/bridge"))if(r["name"]!=internet){selected=str(r,"name");break;}}
 if(selected.isEmpty()){for(auto r:rows(t,"ip/address"))if(r["interface"]!=internet&&!yes(r,"dynamic")){selected=str(r,"interface");break;}}
 if(selected.isEmpty()){for(auto r:rows(t,"interface")){auto name=str(r,"name");if(name!=internet&&enabled(r)&&(r["type"]=="ether"||name.startsWith("ether"))&&find(t,"interface/bridge/port","interface",name).isEmpty()&&find(t,"ip/dhcp-client","interface",name).isEmpty()&&find(t,"interface/pppoe-client","interface",name).isEmpty()){selected=name;break;}}}
 auto onClient=[&](QString menu){for(auto r:rows(t,menu))if(r["interface"]==selected&&enabled(r)&&!yes(r,"invalid"))return r;return QJsonObject{};};
 auto address=onClient("ip/address"),dhcp=onClient("ip/dhcp-server"),hotspot=onClient("ip/hotspot"),profile=find(t,"ip/hotspot/profile","name",str(hotspot,"profile"));
 auto add=[&](QString key,QString ar,QString en,QStringList dependencies,bool ready,QString detail={}){bool unknown=false;for(auto menu:dependencies)if(missing.contains(menu)||!t.contains(menu))unknown=true;result.append(QJsonObject{{"key",key},{"ar",ar},{"en",en},{"check",en},{"state",unknown?"UNKNOWN":ready?"READY":"NEEDS_SETUP"},{"detail",unknown?QString::fromUtf8("تعذرت القراءة؛ الإعداد غير مؤكد • Read unavailable; configuration unverified"):detail}});};
 bool route=false;for(auto r:rows(t,"ip/route"))if(r["dst-address"]=="0.0.0.0/0"&&enabled(r)&&yes(r,"active"))route=true;
 add("route","مسار الإنترنت","Default internet route",{"ip/route"},route,internet);
 auto iface=find(t,"interface","name",internet);add("wan","شبكة الإنترنت","WAN",{"interface","ip/route"},!iface.isEmpty()&&enabled(iface)&&yes(iface,"running"),internet+(internet.isEmpty()?"":" • "+str(detected,"source")));
 bool nat=false;for(auto r:rows(t,"ip/firewall/nat"))if(validCidr(str(address,"address"))&&natServes(r,network(str(address,"address")),internet))nat=true;
 add("nat","مشاركة اتصال الإنترنت","Internet sharing",{"ip/firewall/nat","ip/address","ip/route"},nat);
 auto dns=rows(t,"ip/dns");auto resolver=dns.isEmpty()?QJsonObject{}:dns.first();add("dns","أسماء المواقع","DNS",{"ip/dns"},!str(resolver,"servers").isEmpty()||!str(resolver,"dynamic-servers").isEmpty(),str(resolver,"servers")+" "+str(resolver,"dynamic-servers"));
 bool bridge=false;for(auto r:rows(t,"interface/bridge"))if(enabled(r))bridge=true;add("bridge","ربط منافذ العملاء","Client bridge",{"interface/bridge"},bridge);
 auto client=find(t,"interface","name",selected);add("client","شبكة العملاء","Client network",{"interface"},!client.isEmpty()&&enabled(client),selected);
 add("ip","عنوان شبكة العملاء","Client gateway address",{"ip/address","interface"},!address.isEmpty(),str(address,"address"));
 add("dhcp","توزيع عناوين العملاء","Client address distribution",{"ip/dhcp-server","interface"},!dhcp.isEmpty(),str(dhcp,"name"));
 auto cidr=str(address,"address");auto subnet=validCidr(cidr)?network(cidr):QString{};auto networkRow=find(t,"ip/dhcp-server/network","address",subnet);
 add("dhcp-network","بوابة العملاء وأسماء المواقع","Client gateway/DNS assignment",{"ip/dhcp-server/network","ip/address"},!networkRow.isEmpty()&&!str(networkRow,"gateway").isEmpty()&&!str(networkRow,"dns-server").isEmpty(),subnet);
 auto pool=find(t,"ip/pool","name",str(dhcp,"address-pool"));add("pool","مدى عناوين العملاء","Client address pool",{"ip/pool","ip/dhcp-server"},!pool.isEmpty()&&!str(pool,"ranges").isEmpty(),str(pool,"ranges"));
 add("hotspot","دخول العملاء بالكروت","HotSpot",{"ip/hotspot","interface"},!hotspot.isEmpty(),str(hotspot,"name"));
 bool login=false;for(auto method:str(profile,"login-by").split(','))if(method=="http-chap"||method=="https")login=true;
 add("profile","إعداد دخول العملاء","HotSpot profile",{"ip/hotspot/profile","ip/hotspot/user/profile","ip/hotspot"},!profile.isEmpty()&&!rows(t,"ip/hotspot/user/profile").isEmpty()&&login,str(profile,"name"));
 auto directory=str(profile,"html-directory-override");if(directory.isEmpty())directory=str(profile,"html-directory");bool files=!profile.isEmpty();for(auto name:{"login.html","status.html","md5.js"})if(find(t,"file","name",directory+"/"+name).isEmpty())files=false;
 add("files","صفحة دخول العملاء","Customer login page",{"file","ip/hotspot/profile","ip/hotspot"},files,directory);
 bool api=false;for(auto r:rows(t,"ip/service"))if(enabled(r)&&QStringList{"api","api-ssl","www","www-ssl"}.contains(str(r,"name")))api=true;add("api","اتصال إدارة الراوتر","RouterOS API",{"ip/service"},api);
 bool admin=false;for(auto r:rows(t,"user"))if(enabled(r)&&r["group"]=="full")admin=true;add("admins","مديرو الراوتر","Router administrators",{"user"},admin);
 auto clocks=rows(t,"system/clock");auto clock=clocks.isEmpty()?QJsonObject{}:clocks.first();auto date=QDate::fromString(str(clock,"date"),"yyyy-MM-dd");if(!date.isValid())date=QLocale(QLocale::English).toDate(str(clock,"date"),"MMM/dd/yyyy");auto time=QTime::fromString(str(clock,"time").left(8),"HH:mm:ss");QTimeZone zone(str(clock,"time-zone-name").toUtf8());if(!zone.isValid())zone=QTimeZone::systemTimeZone();auto stamp=QDateTime(date,time,zone);
 add("clock","الساعة والتاريخ","Clock",{"system/clock"},stamp.isValid()&&std::abs(stamp.secsTo(QDateTime::currentDateTimeUtc()))<300,str(clock,"date")+" "+str(clock,"time"));
 add("scheduler","جدولة انتهاء الكروت","Scheduler",{"system/scheduler"},!missing.contains("system/scheduler"));
 auto resources=rows(t,"system/resource");auto resource=resources.isEmpty()?QJsonObject{}:resources.first();auto cpu=usageNumber(resource["cpu-load"]),total=usageNumber(resource["total-memory"]),free=usageNumber(resource["free-memory"]);
 add("storage","المساحة المتاحة","Free storage",{"system/resource"},usageNumber(resource["free-hdd-space"])>2000000,str(resource,"free-hdd-space")+" B");
 add("cpu","المعالج","CPU",{"system/resource"},cpu>=0&&cpu<90,str(resource,"cpu-load")+"%");
 add("memory","الذاكرة","RAM",{"system/resource"},total>0&&free>=0&&free>total/10,str(resource,"free-memory")+" / "+str(resource,"total-memory"));
 int drops=0;for(auto r:rows(t,"ip/firewall/filter"))if(enabled(r)&&r["chain"]=="forward"&&QStringList{"drop","reject"}.contains(str(r,"action")))drops++;
 add("firewall","قواعد حماية الشبكة","Firewall review",{"ip/firewall/filter"},drops==0,QString::number(drops)+" • "+QString::fromUtf8("وجود قواعد حجب يحتاج مراجعة ترتيبها • Review the order of drop rules"));
 return result;
}
void RouterTools::evaluate(QString selected){report=readinessChecks(tables,unavailable,selected);}
void RouterTools::launch(QString op,QJsonObject fields){if(working||client->busy())return;working=true;message="جارٍ العمل • Working";emit changed();job=run(op,fields);job.start();}
void RouterTools::inspect(QString selected){launch("inspect",{{"client",selected}});}void RouterTools::refreshSubscribers(){launch("subscribers");}void RouterTools::planHotspot(QJsonObject r){launch("hotspot_plan",r);}void RouterTools::planPorts(QString client,QString internet){launch("ports_plan",{{"client",client},{"wan",internet}});}void RouterTools::planDns(QStringList networks,QString mode){QJsonArray ids;for(auto id:networks)ids.append(id);launch("dns_plan",{{"ids",ids},{"mode",mode}});}void RouterTools::apply(QString password){launch("apply",{{"password",password}});}void RouterTools::restoreDns(){launch("dns_restore");}void RouterTools::synchronizeClock(){launch("clock");}void RouterTools::backup(QString password){launch("backup",{{"password",password}});}void RouterTools::restoreBackup(QString file,QString password){launch("backup_restore",{{"file",file},{"password",password}});}void RouterTools::exportConfiguration(){launch("export");}void RouterTools::reboot(){launch("reboot");}void RouterTools::flushDns(){launch("flush_dns");}void RouterTools::subscriber(QString op,QString id,QJsonObject fields){fields["id"]=id;fields["action"]=op;launch("subscriber",fields);}void RouterTools::previewPortal(QJsonObject design,QString page){try{check(page=="login.html"||page=="status.html","INVALID_PORTAL_PAGE");auto files=renderPortal(design);preview=str(files,"login.html");auto dir=QStandardPaths::writableLocation(QStandardPaths::CacheLocation)+"/portal-preview";QDir().mkpath(dir);for(auto name:files.keys()){QSaveFile f(dir+"/"+name);auto bytes=str(files,name).toUtf8();check(f.open(QIODevice::WriteOnly)&&f.write(bytes)==bytes.size()&&f.commit(),"PORTAL_PREVIEW_WRITE_FAILED");}QDesktopServices::openUrl(QUrl::fromLocalFile(dir+"/"+page));message="فُتحت معاينة صفحة الدخول • Portal preview opened";}catch(const std::exception&e){message=e.what();}emit changed();}void RouterTools::installPortal(QString profile,QJsonObject design){launch("portal_install",{{"profile",profile},{"design",design}});}void RouterTools::restorePortal(){launch("portal_restore");}
RouterJob RouterTools::run(QString operation,QJsonObject fields){bool nested=fields["_nested"].toBool();QString failure;QJsonArray recovery;QJsonObject plan;
 try{
  loadJournal();if(!nested&&QStringList{"clock","reboot","backup_restore","repair_dns","portal_install"}.contains(operation)){auto secret=QUuid::createUuid().toString(QUuid::WithoutBraces).remove('-');co_await run("backup",{{"password",secret},{"_nested",true}});secret.fill(QChar(0));if(operation=="portal_install")co_await run("clock",{{"_nested",true}});}if(operation=="portal_install"||operation=="portal_restore"){auto identity=co_await call("interface");tables["interface"]=identity.rows;}bool collect=QStringList{"inspect","hotspot_plan","ports_plan","dns_plan","apply","dns_restore"}.contains(operation);
  if(collect){tables={};unavailable.clear();for(auto menu:inspectionMenus()){auto result=co_await call(menu,"print",{},false);tables[menu]=result.rows;if(!result.ok())unavailable.insert(menu);}evaluate(str(fields,operation=="inspect"?"client":"interface"));emit changed();}
  if(operation=="subscribers"){
   tables.remove("ip/hotspot/user");tables.remove("ip/hotspot/active");unavailable.remove("ip/hotspot/active");
   auto users=co_await call("ip/hotspot/user");tables["ip/hotspot/user"]=users.rows;
   auto active=co_await call("ip/hotspot/active","print",{},false);tables["ip/hotspot/active"]=active.rows;if(!active.ok())unavailable.insert("ip/hotspot/active");
   message=active.ok()?"تم تحديث المشتركين والمتصلين • Subscribers and sessions refreshed":"تم تحديث المشتركين؛ تعذرت قراءة الجلسات • Subscribers refreshed; sessions unavailable";
  }
  else if(operation=="inspect"){auto probe=co_await call("ping","",{{"address","1.1.1.1"},{"count","3"},{"interval","300ms"}},false);auto evidence=pingEvidence(probe.rows);auto received=evidence["received"].toInt();auto detail=QString("%1 / %2 • Loss: %3% • %4 ms").arg(received).arg(evidence["sent"].toInt()).arg(evidence["loss_percent"].isNull()?"—":QString::number(evidence["loss_percent"].toDouble(),'f',1)).arg(evidence["latency_ms"].isNull()?"—":QString::number(evidence["latency_ms"].toDouble(),'f',2));report.append(QJsonObject{{"check","Internet probe"},{"state",!probe.ok()?"UNKNOWN":received>0?"READY":"PROBLEM"},{"detail",detail}});auto dnsProbe=co_await call("ping","",{{"address","example.com"},{"count","3"},{"interval","300ms"}},false);auto dnsEvidence=pingEvidence(dnsProbe.rows);report.append(QJsonObject{{"key","dns-probe"},{"ar","اختبار أسماء المواقع"},{"en","DNS reachability probe"},{"check","DNS reachability probe"},{"state",!dnsProbe.ok()?"UNKNOWN":dnsEvidence["received"].toInt()>0?"READY":"PROBLEM"},{"detail",QString::number(dnsEvidence["received"].toInt())+" / "+QString::number(dnsEvidence["sent"].toInt())}});message="اكتمل فحص الراوتر • Router inspection complete";}
  else if(operation.endsWith("_plan")){QStringList required=operation=="dns_plan"?QStringList{"ip/dns","ip/dhcp-server/network","ip/dhcp-client","interface/pppoe-client","interface"}:QStringList{"interface","interface/bridge","interface/bridge/port","interface/vlan","interface/list/member","ip/address","ip/route","ip/pool","ip/dns","ip/dhcp-server","ip/dhcp-server/network","ip/hotspot","ip/hotspot/profile","file","ip/firewall/nat","ip/firewall/filter"};for(auto menu:required)check(!unavailable.contains(menu),"CONFIGURATION_READ_REQUIRED: "+menu);if(operation=="hotspot_plan")pending=hotspotPlan(tables,fields,client->identityKey());else if(operation=="ports_plan")pending=portsPlan(tables,str(fields,"client"),str(fields,"wan"),client->identityKey());else{QSet<QString> ids;for(auto id:fields["ids"].toArray())ids.insert(id.toString());pending=dnsPlan(tables,ids,str(fields,"mode"));}pending["signature"]=signature();pending["fingerprint"]=fingerprint();pending["connection"]=client->identityKey();message="الخطة جاهزة للمراجعة • Plan ready for review";}
  else if(operation=="backup"||operation=="apply"){
   auto password=str(fields,"password");check(password.size()>=12,"BACKUP_PASSWORD_SHORT");if(operation=="apply"){check(!pending.isEmpty()&&pending["signature"]==signature()&&pending["fingerprint"]==fingerprint()&&pending["connection"]==client->identityKey(),"CONFIGURATION_CHANGED_REVIEW_NEW_PLAN");plan=pending;}
   auto name="fg-mtm-"+QString::number(QDateTime::currentMSecsSinceEpoch())+"-"+QUuid::createUuid().toString(QUuid::WithoutBraces).left(4);co_await call("system/backup","save",{{"name",name},{"password",password},{"encryption","aes-sha256"}});bool exists=false;for(int attempt=0;attempt<5&&!exists;attempt++){if(attempt)co_await RouterDelay{this,lifetime,200};auto files=co_await call("file");for(auto r:files.rows)if(r.toObject()["name"]==name+".backup")exists=true;}check(exists,"BACKUP_NOT_VERIFIED");auto passwords=journal["backups"].toObject();passwords[name+".backup"]=password;journal["backups"]=passwords;persist();message="نسخة الراوتر: "+name+".backup • Router backup: "+name+".backup";
   if(operation=="apply"){
    plan["backup"]=name+".backup";plan["state"]="APPLYING";journal["recovery"]=plan;persist();
    for(auto value:plan["changes"].toArray()){
     auto step=value.toObject();QString menu=str(step,"menu"),action=str(step,"action");auto attrs=step["attributes"].toObject();auto before=step["undo"].toObject();auto id=str(attrs,".id");if(action=="set"){auto read=co_await call(menu);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",id);check(!current.isEmpty()&&valuesEqual(current,before),"CONFIGURATION_CHANGED_DURING_APPLY");}
     recovery.append(step);journal["attempted"]=recovery;persist();auto reply=co_await call(menu,action,attrs,false);if(!reply.ok())throw std::runtime_error((reply.error+(reply.uncertain?"; CHANGE_OUTCOME_UNKNOWN":"")).toStdString());
     if(action=="add"){id=reply.rows.isEmpty()?QString{}:str(reply.rows.first().toObject(),".id");auto read=co_await call(menu);if(id.isEmpty()){int matches=0;for(auto r:read.rows)if(valuesEqual(r.toObject(),attrs)){id=str(r.toObject(),".id");matches++;}check(matches==1&&!id.isEmpty(),"CREATED_ITEM_NOT_VERIFIED");}step["created_id"]=id;recovery[recovery.size()-1]=step;check(valuesEqual(find(QJsonObject{{menu,read.rows}},menu,".id",id),attrs),"CREATE_VERIFY_FAILED");}
     else{auto read=co_await call(menu);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",id);check(valuesEqual(current,attrs),"SET_VERIFY_FAILED");}
     journal["attempted"]=recovery;persist();
    }
    if(plan["kind"]=="HOTSPOT"){
     if(plan["request"].toObject()["synchronizeTime"].toBool(true))co_await run("clock",{{"_nested",true}});
     if(plan["installPortal"].toBool()){auto profiles=co_await call("ip/hotspot/profile");auto profile=find(QJsonObject{{"profiles",profiles.rows}},"profiles","name",str(plan,"profileName"));check(!str(profile,".id").isEmpty(),"HOTSPOT_PROFILE_VERIFY_FAILED");co_await run("portal_install",{{"_nested",true},{"profile",profile[".id"]},{"design",plan["request"].toObject()["design"]}});}
    }
    plan["state"]="ACTIVE";plan["changes"]=recovery;if(plan["kind"]=="DNS"){auto dns=co_await call("ip/dns");auto dynamic=dns.rows.isEmpty()?QString{}:str(dns.rows.first().toObject(),"dynamic-servers");for(auto server:dynamic.split(',',Qt::SkipEmptyParts))check(str(plan,"servers").split(',').contains(server.trimmed()),"DYNAMIC_DNS_REVIEW");co_await call("ip/dns/cache","flush");journal["dns"]=plan;}journal["recovery"]=plan;persist();pending={};message="تم تطبيق الخطة والتحقق منها • Plan applied and verified";
   }
  }
  else if(operation=="dns_restore"){
   auto receipt=journal["dns"].toObject();check(!receipt.isEmpty()&&receipt["fingerprint"]==fingerprint()&&receipt["connection"]==client->identityKey(),"DNS_RECEIPT_OR_ROUTER_MISMATCH");auto changes=receipt["changes"].toArray();for(int i=changes.size()-1;i>=0;i--){auto step=changes[i].toObject();auto menu=str(step,"menu");auto after=step["attributes"].toObject(),before=step["undo"].toObject();auto read=co_await call(menu);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",str(after,".id"));check(str(current,"address")==str(step,"targetAddress")&&str(current,"interface")==str(step,"targetInterface"),"DNS_TARGET_CHANGED");for(auto k:after.keys())check(normalized(str(current,k))==normalized(str(after,k))||normalized(str(current,k))==normalized(str(before,k)),"DNS_RESTORE_CONFLICT");co_await call(menu,"set",before);auto verified=co_await call(menu);auto row=menu=="ip/dns"?(verified.rows.isEmpty()?QJsonObject{}:verified.rows.first().toObject()):find(QJsonObject{{menu,verified.rows}},menu,".id",str(before,".id"));check(valuesEqual(row,before),"DNS_RESTORE_VERIFY_FAILED");}co_await call("ip/dns/cache","flush");journal.remove("dns");persist();message="تمت استعادة إعدادات DNS السابقة • Previous DNS settings restored";
  }
  else if(operation=="backup_list"){auto files=co_await call("file","print",{{".proplist","name,size,creation-time"}});tables["file"]=files.rows;message="حُدّثت قائمة نسخ الراوتر • Router backup list refreshed";}
  else if(operation=="repair_dns"){auto read=co_await call("ip/dns");check(read.rows.size()==1,"DNS_READ_REQUIRED");auto before=read.rows.first().toObject();check(str(before,"servers").isEmpty()&&str(before,"dynamic-servers").isEmpty(),"DNS_ALREADY_CONFIGURED");co_await call("ip/dns","set",{{"servers","1.1.1.1,9.9.9.9"}});auto verify=co_await call("ip/dns");check(!verify.rows.isEmpty()&&str(verify.rows.first().toObject(),"servers")=="1.1.1.1,9.9.9.9","DNS_REPAIR_VERIFY_FAILED");message="أُصلح DNS بعد حفظ نسخة مشفرة • DNS repaired after encrypted backup";}
  else if(operation=="clock"){
   auto previous=co_await call("system/clock");check(previous.rows.size()==1,"CLOCK_READ_REQUIRED");auto ntp=co_await call("system/ntp/client");check(!ntp.rows.isEmpty(),"NTP_READ_REQUIRED");auto servers=co_await call("system/ntp/client/servers");auto now=QDateTime::currentDateTime();auto zone=QString::fromUtf8(QTimeZone::systemTimeZoneId());co_await call("system/clock","set",{{"time-zone-autodetect","no"},{"time-zone-name",zone}});auto date=str(previous.rows.first().toObject(),"date").contains('-')?now.date().toString("yyyy-MM-dd"):QLocale(QLocale::English).toString(now.date(),"MMM/dd/yyyy").toLower();co_await call("system/clock","set",{{"date",date}});co_await call("system/clock","set",{{"time",now.time().toString("HH:mm:ss")}});bool active=false;for(auto r:servers.rows)if(!str(r.toObject(),"address").isEmpty()&&!QStringList{"no","false"}.contains(str(r.toObject(),"enabled")))active=true;if(!active)for(auto address:{"time.cloudflare.com","time.google.com"}){auto old=find(QJsonObject{{"servers",servers.rows}},"servers","address",address);if(old.isEmpty())co_await call("system/ntp/client/servers","add",{{"address",address}});else{check(!str(old,".id").isEmpty(),"TARGET_ID_REQUIRED");co_await call("system/ntp/client/servers","set",{{".id",old[".id"]},{"enabled","yes"}});}}if(!yes(ntp.rows.first().toObject(),"enabled"))co_await call("system/ntp/client","set",{{"enabled","yes"}});auto verified=co_await call("system/clock");auto clock=verified.rows.first().toObject();auto d=QDate::fromString(str(clock,"date"),"yyyy-MM-dd");if(!d.isValid())d=QLocale(QLocale::English).toDate(str(clock,"date"),"MMM/dd/yyyy");auto time=QTime::fromString(str(clock,"time").left(8),"HH:mm:ss");QDateTime local(d,time,QTimeZone::systemTimeZone());check(d.isValid()&&time.isValid()&&std::abs(local.secsTo(now))<120,"CLOCK_VERIFY_FAILED");auto enabledNtp=co_await call("system/ntp/client");check(!enabledNtp.rows.isEmpty()&&yes(enabledNtp.rows.first().toObject(),"enabled"),"NTP_VERIFY_FAILED");message="تم ضبط الساعة وتفعيل NTP • Clock verified and NTP enabled";
  }
  else if(operation=="subscriber"){
   auto id=str(fields,"id"),action=str(fields,"action");check(QStringList{"enable","disable","disconnect","delete","update","add_time"}.contains(action),"INVALID_SUBSCRIBER_ACTION");check(!id.isEmpty(),"SELECT_SUBSCRIBER");auto response=co_await call("ip/hotspot/user");auto user=find(QJsonObject{{"users",response.rows}},"users",".id",id);check(!user.isEmpty(),"SUBSCRIBER_NOT_FOUND");auto username=str(user,"name");if(action=="enable"||action=="disable")co_await call("ip/hotspot/user",action,{{".id",id}});if(action=="disconnect"||action=="disable"||action=="delete"){auto active=co_await call("ip/hotspot/active");for(auto value:active.rows){auto row=value.toObject();if(row["user"]==username){check(!str(row,".id").isEmpty(),"TARGET_ID_REQUIRED");co_await call("ip/hotspot/active","remove",{{".id",row[".id"]}});}}}if(action=="delete"){co_await call("ip/hotspot/user","remove",{{".id",id}});auto schedulers=co_await call("system/scheduler");for(auto value:schedulers.rows){auto r=value.toObject();if(r["comment"]=="FG MTM voucher expiry for "+username)co_await call("system/scheduler","remove",{{".id",r[".id"]}});}}
   else if(action=="update"){auto attrs=fields["attributes"].toObject();for(auto key:attrs.keys())check(QStringList{"profile","server","comment","limit-uptime","limit-bytes-total","password"}.contains(key),"INVALID_USER_FIELD");attrs[".id"]=id;co_await call("ip/hotspot/user","set",attrs);}
   else if(action=="add_time"){auto seconds=str(fields,"seconds").toLongLong();check(seconds>=60&&seconds<=31536000,"INVALID_DURATION");auto value=str(user,"limit-uptime");qint64 current=0;auto matches=QRegularExpression("([0-9]+)(w|d|h|m|s)").globalMatch(value);QString consumed;while(matches.hasNext()){auto m=matches.next();consumed+=m.captured();auto n=m.captured(1).toLongLong();auto unit=m.captured(2);auto factor=unit=="w"?604800:unit=="d"?86400:unit=="h"?3600:unit=="m"?60:1;check(n<=(std::numeric_limits<qint64>::max()-current)/factor,"DURATION_OVERFLOW");current+=n*factor;}if(QRegularExpression("^[0-9]+:[0-9]{2}:[0-9]{2}$").match(value).hasMatch()){auto parts=value.split(':');bool ok;auto hours=parts[0].toLongLong(&ok);check(ok&&hours>=0&&hours<=(std::numeric_limits<qint64>::max()-3600)/3600&&parts[1].toInt()<60&&parts[2].toInt()<60,"DURATION_OVERFLOW");current=hours*3600+parts[1].toInt()*60+parts[2].toInt();}else check(consumed==value,"UNKNOWN_ROUTER_DURATION");check(current>0&&current<=std::numeric_limits<qint64>::max()-seconds,"UNLIMITED_OR_INVALID_DURATION");co_await call("ip/hotspot/user","set",{{".id",id},{"limit-uptime",QString::number(current+seconds)+"s"}});}
   auto users=co_await call("ip/hotspot/user");tables["ip/hotspot/user"]=users.rows;auto active=co_await call("ip/hotspot/active","print",{},false);tables["ip/hotspot/active"]=active.rows;unavailable.remove("ip/hotspot/active");if(!active.ok())unavailable.insert("ip/hotspot/active");message="تم تحديث المشترك • Subscriber updated";
  }
  else if(operation=="portal_install"){
   auto response=co_await call("ip/hotspot/profile");auto profile=find(QJsonObject{{"profiles",response.rows}},"profiles",".id",str(fields,"profile"));check(!profile.isEmpty(),"PROFILE_NOT_FOUND");auto files=renderPortal(fields["design"].toObject());auto existing=co_await call("file");bool flash=!find(QJsonObject{{"files",existing.rows}},"files","name","flash").isEmpty();auto directory=QString(flash?"flash/":"")+"fg-mtm-"+QString::number(QDateTime::currentMSecsSinceEpoch());co_await call("file","add",{{"name",directory},{"type","directory"}});for(auto name:files.keys()){auto path=directory+"/"+name;co_await call("file","add",{{"name",path},{"type","file"}});auto read=co_await call("file");auto file=find(QJsonObject{{"files",read.rows}},"files","name",path);check(!str(file,".id").isEmpty(),"PORTAL_FILE_CREATE_FAILED");co_await call("file","set",{{".id",file[".id"]},{"contents",files[name]}});auto verified=co_await call("file");check(find(QJsonObject{{"files",verified.rows}},"files",".id",str(file,".id"))["contents"]==files[name],"PORTAL_UPLOAD_VERIFY_FAILED");}
   QJsonObject receipt{{"profile",profile[".id"]},{"name",profile["name"]},{"before",QJsonObject{{"html-directory",str(profile,"html-directory")},{"html-directory-override",str(profile,"html-directory-override")}}},{"directory",directory},{"connection",client->identityKey()},{"fingerprint",fingerprint()},{"state","APPLYING"}};journal["portal"]=receipt;persist();auto pointer=directory+"/rollback.txt";co_await call("file","add",{{"name",pointer},{"type","file"}});auto list=co_await call("file");auto pointerFile=find(QJsonObject{{"files",list.rows}},"files","name",pointer);check(!str(pointerFile,".id").isEmpty(),"ROLLBACK_POINTER_FAILED");co_await call("file","set",{{".id",pointerFile[".id"]},{"contents","profile="+str(profile,"name")+"\nhtml-directory="+str(profile,"html-directory")+"\nhtml-directory-override="+str(profile,"html-directory-override")}});co_await call("ip/hotspot/profile","set",{{".id",profile[".id"]},{"html-directory",directory},{"html-directory-override",""}});auto verify=co_await call("ip/hotspot/profile");auto current=find(QJsonObject{{"profiles",verify.rows}},"profiles",".id",str(profile,".id"));check(current["html-directory"]==directory&&str(current,"html-directory-override").isEmpty(),"PORTAL_BINDING_VERIFY_FAILED");receipt["state"]="ACTIVE";journal["portal"]=receipt;persist();message="تم تثبيت صفحة الدخول والتحقق منها • Portal installed and verified";
  }
  else if(operation=="portal_restore"){
   auto receipt=journal["portal"].toObject();check(!receipt.isEmpty()&&receipt["connection"]==client->identityKey()&&receipt["fingerprint"]==fingerprint(),"PORTAL_RECOVERY_MISSING");auto response=co_await call("ip/hotspot/profile");auto profile=find(QJsonObject{{"profiles",response.rows}},"profiles",".id",str(receipt,"profile"));check(profile["name"]==receipt["name"]&&profile["html-directory"]==receipt["directory"],"PORTAL_RESTORE_CONFLICT");auto attrs=receipt["before"].toObject();attrs[".id"]=receipt["profile"];co_await call("ip/hotspot/profile","set",attrs);auto verify=co_await call("ip/hotspot/profile");check(valuesEqual(find(QJsonObject{{"profiles",verify.rows}},"profiles",".id",str(receipt,"profile")),attrs),"PORTAL_RESTORE_VERIFY_FAILED");journal.remove("portal");persist();message="استعيدت صفحة الدخول السابقة • Previous portal restored";
  }
  else if(operation=="backup_restore"){auto files=co_await call("file");auto file=str(fields,"file");check(file.endsWith(".backup")&&!find(QJsonObject{{"files",files.rows}},"files","name",file).isEmpty(),"SELECT_EXISTING_BACKUP");co_await call("system/backup","load",{{"name",file},{"password",fields["password"]}});message="أُرسل طلب الاستعادة • Restore request sent";}
  else if(operation=="export"){auto resource=co_await call("system/resource");auto name="fg-mtm-export-"+QString::number(QDateTime::currentMSecsSinceEpoch());QJsonObject attrs{{"file",name}};if(!resource.rows.isEmpty()&&str(resource.rows.first().toObject(),"version").startsWith("6."))attrs["hide-sensitive"]="yes";co_await call("export","",attrs);bool exists=false;for(int attempt=0;attempt<5&&!exists;attempt++){if(attempt)co_await RouterDelay{this,lifetime,200};auto files=co_await call("file");exists=!find(QJsonObject{{"files",files.rows}},"files","name",name+".rsc").isEmpty();}check(exists,"EXPORT_VERIFY_FAILED");message="تم تصدير إعدادات الراوتر: "+name+".rsc • Router configuration exported: "+name+".rsc";}
  else if(operation=="reboot"){co_await call("system","reboot");message="أُرسل طلب إعادة التشغيل • Reboot request sent";}
  else if(operation=="flush_dns"){co_await call("ip/dns/cache","flush");message="مُسحت ذاكرة DNS • DNS cache flushed";}
 }catch(const std::exception&e){failure=QString::fromUtf8(e.what());}
 if(!failure.isEmpty()){
  QStringList failed;
  for(int i=recovery.size()-1;i>=0;i--){auto step=recovery[i].toObject();auto menu=str(step,"menu"),action=str(step,"action");auto attrs=step["attributes"].toObject();RouterReply result;try{if(action=="add"){auto id=str(step,"created_id");auto owned=co_await call(menu,"print",{},false);if(!owned.ok()){failed.append(menu);continue;}if(!id.isEmpty()&&!valuesEqual(find(QJsonObject{{menu,owned.rows}},menu,".id",id),attrs)){failed.append(menu);continue;}if(id.isEmpty()){auto read=owned;int count=0;for(auto r:read.rows)if(valuesEqual(r.toObject(),attrs)){id=str(r.toObject(),".id");count++;}if(!read.ok()||count!=1||id.isEmpty()){failed.append(menu);continue;}}result=co_await call(menu,"remove",{{".id",id}},false);}else{auto read=co_await call(menu,"print",{},false);auto current=menu=="ip/dns"?(read.rows.isEmpty()?QJsonObject{}:read.rows.first().toObject()):find(QJsonObject{{menu,read.rows}},menu,".id",str(attrs,".id"));auto before=step["undo"].toObject();bool owned=!current.isEmpty();for(auto k:attrs.keys())if(normalized(str(current,k))!=normalized(str(attrs,k))&&normalized(str(current,k))!=normalized(str(before,k)))owned=false;if(!read.ok()||!owned){failed.append(menu);continue;}result=co_await call(menu,"set",before,false);}if(!result.ok())failed.append(menu);else{auto verify=co_await call(menu,"print",{},false);if(!verify.ok())failed.append(menu);else if(action=="add"){auto id=str(step,"created_id");for(auto row:verify.rows)if((!id.isEmpty()&&str(row.toObject(),".id")==id)||valuesEqual(row.toObject(),attrs)){failed.append(menu);break;}}else{auto before=step["undo"].toObject();auto row=menu=="ip/dns"?(verify.rows.isEmpty()?QJsonObject{}:verify.rows.first().toObject()):find(QJsonObject{{menu,verify.rows}},menu,".id",str(before,".id"));if(!valuesEqual(row,before))failed.append(menu);}}}catch(...){failed.append(menu);}}
  if(!recovery.isEmpty()){auto r=journal["recovery"].toObject();r["state"]=failed.isEmpty()?"ROLLED_BACK":"REVIEW";journal["recovery"]=r;try{persist();}catch(...){failed.append("journal");}}
  if(operation=="portal_install"&&journal["portal"].isObject()){auto receipt=journal["portal"].toObject();auto before=receipt["before"].toObject();auto read=co_await call("ip/hotspot/profile","print",{},false);auto current=find(QJsonObject{{"profiles",read.rows}},"profiles",".id",str(receipt,"profile"));bool owned=read.ok()&&current["name"]==receipt["name"]&&(valuesEqual(current,before)||current["html-directory"]==receipt["directory"]&&str(current,"html-directory-override").isEmpty());if(!owned)failed.append("portal conflict");else{before[".id"]=receipt["profile"];auto rollback=co_await call("ip/hotspot/profile","set",before,false);auto verify=co_await call("ip/hotspot/profile","print",{},false);if(!rollback.ok()||!verify.ok()||!valuesEqual(find(QJsonObject{{"profiles",verify.rows}},"profiles",".id",str(receipt,"profile")),before))failed.append("portal");}}
  message=failure+(failed.isEmpty()?QString{}:" — تحتاج مراجعة: "+failed.join(',')+" • Recovery needs review: "+failed.join(','));
 }
 if(nested){if(!failure.isEmpty())throw std::runtime_error(message.toStdString());co_return;}working=false;emit changed();co_return;
}

QVariantMap RouterTools::portalDesign()const{QSettings settings;return settings.value("portal/design").toMap();}
void RouterTools::savePortalDesign(QJsonObject design){try{renderPortal(design);QSettings settings;settings.setValue("portal/design",design.toVariantMap());settings.sync();check(settings.status()==QSettings::NoError,"DESIGN_SAVE_FAILED");message="حُفظ تصميم الصفحة • Portal design saved";}catch(const std::exception&e){message=e.what();}emit changed();}
QString RouterTools::portalLogo(QUrl path){try{QFile file(path.toLocalFile());check(file.exists()&&file.size()<=8*1024*1024,"LOGO_FILE_LIMIT");QImageReader reader(path.toLocalFile());auto size=reader.size();check(size.isValid()&&size.width()<=4096&&size.height()<=4096,"LOGO_IMAGE_LIMIT");reader.setAutoTransform(true);auto image=reader.read();check(!image.isNull(),"INVALID_LOGO_IMAGE");image=image.scaled(256,256,Qt::KeepAspectRatio,Qt::SmoothTransformation);QByteArray bytes;QBuffer buffer(&bytes);buffer.open(QIODevice::WriteOnly);check(image.save(&buffer,"PNG")&&bytes.size()<=35000,"LOGO_TOO_LARGE");return "data:image/png;base64,"+QString::fromLatin1(bytes.toBase64());}catch(const std::exception&e){message=e.what();emit changed();return {};}}

QVariantList RouterTools::backups()const{QVariantList list;if(!client->authorized())return list;for(auto row:tables["file"].toArray()){auto item=row.toObject();auto name=str(item,"name");if(name.endsWith(".backup")||name.endsWith(".rsc"))list.append(QVariantMap{{"name",name},{"size",str(item,"size")},{"date",str(item,"creation-time")}});}return list;}
void RouterTools::loadBackups(){launch("backup_list");}
void RouterTools::repairDns(){launch("repair_dns");}
QString RouterTools::backupPassword(QString file){try{check(client->authorized(),"ACCESS_DENIED");loadJournal();auto password=str(journal["backups"].toObject(),file);check(!password.isEmpty(),"BACKUP_PASSWORD_NOT_SAVED");return password;}catch(const std::exception&e){message=e.what();emit changed();return {};}}

QJsonObject RouterTools::pingEvidence(QJsonArray data){int sent=data.size(),received=0,samples=0;double sum=0;auto ms=[](QString text)->std::optional<double>{auto matches=QRegularExpression("([0-9.]+)(ms|us)").globalMatch(text);double value=0;bool found=false;while(matches.hasNext()){auto match=matches.next();bool valid;auto n=match.captured(1).toDouble(&valid);if(!valid)return {};value+=n/(match.captured(2)=="us"?1000:1);found=true;}if(found)return value;bool valid;value=text.toDouble(&valid);return valid?std::optional<double>(value):std::nullopt;};std::optional<double> latency;for(auto value:data){auto row=value.toObject();if(row.contains("sent")){sent=str(row,"sent").toInt();received=str(row,"received").toInt();latency=ms(str(row,"avg-rtt"));break;}if(!str(row,"time").isEmpty()&&str(row,"status").isEmpty()){received++;if(auto duration=ms(str(row,"time"))){sum+=*duration;samples++;}}}if(!latency&&samples)latency=sum/samples;return {{"sent",sent},{"received",received},{"loss_percent",sent>0?QJsonValue(100.0*(sent-received)/sent):QJsonValue::Null},{"latency_ms",latency?QJsonValue(*latency):QJsonValue::Null}};}
