#include "Vouchers.hpp"
#include "Vault.hpp"
#include "Protocol.hpp"
#include "../vendor/qrcodegen.hpp"
#include <QRandomGenerator>
#include <QUuid>
#include <QSet>
#include <QJsonDocument>
#include <QStandardPaths>
#include <QDir>
#include <QFile>
#include <QSaveFile>
#include <QPainter>
#include <QPdfWriter>
#include <QPrinter>
#include <QPrintDialog>
#include <QDateTime>
#include <QRegularExpression>
#include <QTimeZone>
#include <QPagedPaintDevice>
#include <QLocale>
#include <QUrlQuery>
#include <QPageSize>
#include <QPageLayout>
#include <stdexcept>
namespace {
void check(bool test,const char *text){if(!test)throw std::runtime_error(text);}
QString text(QJsonObject o,QString k,QString fallback={}){return o[k].toString(fallback);}
QByteArray readBounded(QString path){QFile f(path);check(f.open(QIODevice::ReadOnly)&&f.size()<=20*1024*1024+52,"FILE_READ_FAILED");return f.readAll();}
void writeAtomic(QString path,QByteArray data){QSaveFile f(path);check(f.open(QIODevice::WriteOnly)&&f.write(data)==data.size()&&f.commit(),"FILE_WRITE_FAILED");}
}
Vouchers::Vouchers(RouterClient*r,QObject*p):QObject(p),router(r){directory=QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation)+"/vouchers";QDir().mkpath(directory);}
QJsonObject Vouchers::generateBatch(QJsonObject req){int qty=req["quantity"].toInt(1),length=req["usernameLength"].toInt(8),pwlen=req["passwordLength"].toInt(6),duration=req["durationValue"].toInt(60);auto mode=text(req,"mode","HOTSPOT"),unit=text(req,"durationUnit","MINUTES");
 check(qty>=1&&qty<=5000&&length>=4&&length<=16&&pwlen>=4&&pwlen<=16&&duration>=1&&duration<=100000,"INVALID_VOUCHER_FORMAT");check(QStringList{"HOTSPOT","PPPOE","USER_MANAGER","OFFLINE"}.contains(mode)&&QStringList{"MINUTES","HOURS","DAYS"}.contains(unit),"INVALID_MODE");check(mode=="OFFLINE"||!text(req,"profile").trimmed().isEmpty(),"PROFILE_REQUIRED");check(!text(req,"server","all").trimmed().isEmpty(),"SERVER_REQUIRED");
 auto bytes=req["limitBytesTotal"];if(!bytes.isNull()&&!bytes.isUndefined()){bool ok;auto n=bytes.toVariant().toLongLong(&ok);check(ok&&n>0,"INVALID_BYTES_LIMIT");req["limitBytesTotal"]=n;}
 auto expiry=req["absoluteExpiryEpochMs"];if(!expiry.isNull()&&!expiry.isUndefined()){bool ok;auto n=expiry.toVariant().toLongLong(&ok);check(ok&&n>QDateTime::currentMSecsSinceEpoch(),"EXPIRY_IN_PAST");req["absoluteExpiryEpochMs"]=n;}
 req["quantity"]=qty;req["mode"]=mode;req["usernameLength"]=length;req["passwordLength"]=pwlen;req["durationValue"]=duration;req["durationUnit"]=unit;req["server"]=text(req,"server","all");
 QString alphabet=text(req,"characterSet","NUMERIC")=="NUMERIC"?"0123456789":"23456789ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz";
 auto random=[&](int n){QString s;for(int i=0;i<n;i++)s+=alphabet[QRandomGenerator::system()->bounded(int(alphabet.size()))];return s;};QSet<QString> used;QJsonArray cards;auto comment="FG-MTM batch="+QUuid::createUuid().toString(QUuid::WithoutBraces);if(!text(req,"comment").isEmpty())comment+=" • "+text(req,"comment");
 for(int attempts=0;cards.size()<qty;attempts++){check(attempts<qty*50,"UNIQUE_GENERATION_EXHAUSTED");auto user=text(req,"prefix")+random(length)+text(req,"suffix");check(user.size()<=128,"USERNAME_TOO_LONG");if(used.contains(user))continue;used.insert(user);auto card=req;card.remove("quantity");card["username"]=user;card["password"]=text(req,"passwordMode")=="RANDOM"?random(pwlen):user;card["comment"]=comment;card["limitUptime"]=text(req,"limitUptime");if(text(card,"limitUptime").isEmpty())card["limitUptime"]=QString::number(duration)+(unit=="DAYS"?"d":unit=="HOURS"?"h":"m");card["provisionState"]=mode=="OFFLINE"?"OFFLINE":"DRAFT";cards.append(card);}
 return {{"request",req},{"vouchers",cards}};
}
QString Vouchers::quote(QString v){return "\""+v.replace("\\","\\\\").replace("\"","\\\"").replace("$","\\$").replace("\n","\\n").replace("\r","\\r")+"\"";}
QString Vouchers::script(const QJsonObject &b){QString out;for(auto value:b["vouchers"].toArray()){auto v=value.toObject();auto mode=text(v,"mode");if(mode=="OFFLINE")continue;auto line=mode=="HOTSPOT"?"/ip hotspot user add":mode=="PPPOE"?"/ppp secret add":"/user-manager user add";QString s=line;s+=" name="+quote(text(v,"username"))+" password="+quote(text(v,"password"));if(mode=="HOTSPOT"||mode=="PPPOE")s+=" profile="+quote(text(v,"profile"));if(mode=="PPPOE")s+=" service=\"pppoe\"";if(mode=="HOTSPOT"){s+=" server="+quote(text(v,"server"))+" limit-uptime="+quote(text(v,"limitUptime"));if(v.contains("limitBytesTotal")&&!v["limitBytesTotal"].isNull())s+=" limit-bytes-total="+Protocol::jsonText(v["limitBytesTotal"]);}s+=" comment="+quote(text(v,"comment"));out+=s+"\n";if(mode=="USER_MANAGER"&&!text(v,"profile").isEmpty()&&text(v,"profile").compare("No Profile",Qt::CaseInsensitive)!=0)out+="/user-manager user-profile add user="+quote(text(v,"username"))+" profile="+quote(text(v,"profile"))+"\n";}return out;}
QString Vouchers::qrPayload(const QJsonObject &v){auto branding=v["branding"].toObject();auto mode=text(v,"mode");QUrl url(text(branding,"portalLoginUrl"));if(mode=="HOTSPOT"&&url.isValid()&&(url.scheme()=="http"||url.scheme()=="https")&&!url.host().isEmpty()){QUrlQuery q(url);q.removeAllQueryItems("username");q.removeAllQueryItems("password");q.addQueryItem("username",text(v,"username"));q.addQueryItem("password",text(v,"password"));url.setQuery(q);return url.toString(QUrl::FullyEncoded);}return (mode=="OFFLINE"?"Offline voucher — NOT activated on a router\n":mode=="PPPOE"?"PPPoE setup card\n":"FG MTM Voucher\n")+QString("Network: %1\nUsername: %2\nPassword: %3\nDuration: %4 %5\nProfile: %6\nSupport: %7").arg(text(branding,"networkName"),text(v,"username"),text(v,"password"),QString::number(v["durationValue"].toInt()),text(v,"durationUnit"),text(v,"profile"),text(branding,"supportPhone"));}
QImage Vouchers::qr(const QString &payload,int size){auto data=payload.toUtf8();auto code=qrcodegen::QrCode::encodeText(data.constData(),qrcodegen::QrCode::Ecc::MEDIUM);int n=code.getSize(),scale=std::max(1,size/(n+8));QImage img((n+8)*scale,(n+8)*scale,QImage::Format_RGB32);img.fill(Qt::white);QPainter p(&img);for(int y=0;y<n;y++)for(int x=0;x<n;x++)if(code.getModule(x,y))p.fillRect((x+4)*scale,(y+4)*scale,scale,scale,Qt::black);return img;}
void Vouchers::save(){auto clear=QJsonDocument(batch).toJson(QJsonDocument::Compact);auto cipher=Vault::protect(clear);clear.fill('\0');writeAtomic(directory+"/"+batchId+".fgv",cipher);}
void Vouchers::generate(QJsonObject request){if(working)return;try{check(authorization(),"ACCESS_DENIED");auto next=generateBatch(request);batch=next;batchId=QString::number(QDateTime::currentMSecsSinceEpoch())+"-"+QUuid::createUuid().toString(QUuid::WithoutBraces);save();message="تم إنشاء الكروت وحفظها مشفرة • Vouchers generated and encrypted";}catch(const std::exception&e){message=QString::fromUtf8(e.what());}emit changed();}
QVariantList Vouchers::archive()const{QVariantList rows;if(!authorization())return rows;auto files=QDir(directory).entryList({"*.fgv"},QDir::Files,QDir::Name|QDir::Reversed);for(auto file:files)rows.append(QVariantMap{{"id",file.chopped(4)},{"date",QDateTime::fromMSecsSinceEpoch(file.section('-',0,0).toLongLong()).toString("yyyy-MM-dd HH:mm")}});return rows;}
void Vouchers::openBatch(QString id){if(!authorization()||working||!QRegularExpression("^[0-9]{1,19}-[a-fA-F0-9-]{36}$").match(id).hasMatch())return;try{auto bytes=Vault::unprotect(readBounded(directory+"/"+id+".fgv"));auto doc=QJsonDocument::fromJson(bytes);bytes.fill('\0');check(doc.isObject()&&doc.object()["vouchers"].isArray(),"ARCHIVE_INVALID");batch=doc.object();batchId=id;message="تم فتح الدفعة • Batch opened";}catch(const std::exception&e){message=e.what();}emit changed();}
void Vouchers::activate(){if(working||batch.isEmpty()||!router->connected()||!authorization())return;auto mode=text(batch["request"].toObject(),"mode");if(mode=="OFFLINE"){message="دفعة محلية غير مفعلة • Offline batch";emit changed();return;}working=true;QString menu=mode=="HOTSPOT"?"ip/hotspot/user":mode=="PPPOE"?"ppp/secret":"user-manager/user";
 router->read(menu,[this,menu](RouterReply r){if(!r.ok()){working=false;message=r.error;emit changed();return;}QSet<QString> existing;for(auto v:r.rows)existing.insert(text(v.toObject(),"name"));provision(0,menu,existing);});emit changed();}
void Vouchers::provision(int index,QString menu,QSet<QString> existing){if(!authorization()){working=false;message="ACCESS_DENIED";emit changed();return;}auto cards=batch["vouchers"].toArray();if(index>=cards.size()){working=false;message="اكتملت معالجة الدفعة؛ راجع حالة كل كارت • Batch processed; review each voucher state";emit changed();return;}auto card=cards[index].toObject();auto state=text(card,"provisionState");if(state!="DRAFT"){provision(index+1,menu,existing);return;}
 if(existing.contains(text(card,"username"))){card["provisionState"]="DUPLICATE";cards[index]=card;batch["vouchers"]=cards;try{save();}catch(const std::exception&e){working=false;message=e.what();emit changed();return;}provision(index+1,menu,existing);return;}
 card["provisionState"]="REVIEW";cards[index]=card;batch["vouchers"]=cards;try{save();}catch(const std::exception&e){working=false;message=e.what();emit changed();return;}
 auto mode=text(card,"mode");QJsonObject attrs{{"name",card["username"]},{"password",card["password"]},{"comment",card["comment"]}};if(mode=="HOTSPOT"){attrs["profile"]=card["profile"];attrs["server"]=card["server"];attrs["limit-uptime"]=card["limitUptime"];if(card.contains("limitBytesTotal")&&!card["limitBytesTotal"].isNull())attrs["limit-bytes-total"]=Protocol::jsonText(card["limitBytesTotal"]);}else if(mode=="PPPOE"){attrs["service"]="pppoe";attrs["profile"]=card["profile"];}
 router->execute(menu,"add",attrs,[this,index,menu,existing,card,mode](RouterReply result)mutable{
  auto complete=[this,index,menu,existing,card](RouterReply r)mutable{auto cards=batch["vouchers"].toArray();auto v=card;v["provisionState"]=r.ok()?"CREATED":r.uncertain?"REVIEW":"FAILED";v["provisionMessage"]=r.error;cards[index]=v;batch["vouchers"]=cards;try{save();}catch(const std::exception&e){working=false;message=e.what();emit changed();return;}emit changed();if(r.uncertain){working=false;message="تحقق من حالة الكارت على الراوتر قبل المتابعة • Reconcile router outcome before continuing";emit changed();return;}existing.insert(text(card,"username"));provision(index+1,menu,existing);};
  if(!result.ok()){complete(result);return;}auto id=result.rows.isEmpty()?QString{}:text(result.rows.first().toObject(),".id");auto schedule=[this,card,id,complete](RouterReply r)mutable{if(!r.ok()){complete(r);return;}if(card.contains("absoluteExpiryEpochMs")&&!card["absoluteExpiryEpochMs"].isNull())expire(card,id,complete);else complete(r);};
  if(mode=="USER_MANAGER"&&!text(card,"profile").isEmpty()&&text(card,"profile").compare("No Profile",Qt::CaseInsensitive)!=0)router->execute("user-manager/user-profile","add",{{"user",card["username"]},{"profile",card["profile"]}},schedule);else schedule(result);
 });}
void Vouchers::expire(QJsonObject card,QString id,std::function<void(RouterReply)> done){router->read("system/clock",[this,card,id,done](RouterReply r){auto clock=r.rows.isEmpty()?QJsonObject{}:r.rows.first().toObject();auto date=text(clock,"date");auto d=QDate::fromString(date,"yyyy-MM-dd");if(!d.isValid())d=QLocale(QLocale::English).toDate(date,"MMM/dd/yyyy");auto t=QTime::fromString(text(clock,"time").left(8),"HH:mm:ss");auto delay=card["absoluteExpiryEpochMs"].toVariant().toLongLong()-QDateTime::currentMSecsSinceEpoch();auto mode=text(card,"mode");QString menu=mode=="HOTSPOT"?"ip/hotspot/user":mode=="PPPOE"?"ppp/secret":"user-manager/user";
 auto fail=[this,menu,id,done](QString error){if(id.isEmpty()){done({{},error,true});return;}router->execute(menu,"disable",{{".id",id}},[done,error](RouterReply disabled){done({{},error+(disabled.ok()?"; account disabled":"; disable needs review"),!disabled.ok()});});};
 if(!r.ok()||!d.isValid()||!t.isValid()||delay<=0){fail("EXPIRY_CLOCK_UNAVAILABLE");return;}QDateTime target(d,t,QTimeZone::UTC);target=target.addSecs(delay/1000);auto name="fg-exp-"+text(card,"username");name.replace(QRegularExpression("[^A-Za-z0-9_-]"),"_");name=name.left(48);auto user=quote(text(card,"username"));auto script="/"+menu.replace('/', ' ')+" disable [find where name="+user+"]";if(mode=="HOTSPOT")script+="; /ip hotspot active remove [find where user="+user+"]";script+="; /system scheduler remove [find where name="+quote(name)+"]";
 router->execute("system/scheduler","add",{{"name",name},{"start-date",date.contains('-')?target.date().toString("yyyy-MM-dd"):QLocale(QLocale::English).toString(target.date(),"MMM/dd/yyyy").toLower()},{"start-time",target.time().toString("HH:mm:ss")},{"interval","0s"},{"on-event",script},{"comment","FG MTM voucher expiry for "+text(card,"username")}},[done,fail](RouterReply added){if(added.ok())done(added);else fail("EXPIRY_SCHEDULER_FAILED");});});}
void Vouchers::paintCard(QPainter&p,QRectF r,QJsonObject v){auto b=v["branding"].toObject();p.save();p.setPen(QPen(QColor("#416074"),2));p.setBrush(Qt::white);p.drawRoundedRect(r,14,14);auto x=r.x()+20,y=r.y()+15,w=r.width()-40;QFont font("Segoe UI",13);font.setBold(true);p.setFont(font);p.setPen(QColor("#087a4f"));p.drawText(QRectF(x,y,w,36),Qt::AlignRight,text(b,"networkName","FG Machines WiFi"));p.setPen(Qt::black);p.drawText(QRectF(x,y+42,w,28),Qt::AlignLeft,text(v,"username"));font.setPointSize(10);font.setBold(false);p.setFont(font);p.drawText(QRectF(x,y+76,w,25),Qt::AlignLeft,"Password: "+text(v,"password"));p.drawText(QRectF(x,y+107,w-120,75),Qt::AlignLeft|Qt::TextWordWrap,"Duration: "+QString::number(v["durationValue"].toInt())+" "+text(v,"durationUnit")+"\nProfile: "+text(v,"profile")+"\n"+text(b,"priceText"));p.drawImage(QRectF(r.right()-130,y+105,110,110),qr(qrPayload(v)));p.drawText(QRectF(x,r.bottom()-60,w,42),Qt::AlignLeft|Qt::TextWordWrap,text(b,"supportPhone")+" • "+text(v,"provisionState"));p.restore();}
void Vouchers::render(QPagedPaintDevice &device,QString paper){QPainter p(&device);check(p.isActive(),"PRINT_DEVICE_FAILED");auto cards=batch["vouchers"].toArray();bool a4=paper=="A4";auto size=device.pageLayout().paintRectPixels(device.logicalDpiX()).size();int cols=a4?2:1,rows=a4?4:1,per=cols*rows;double w=double(size.width())/cols,h=double(size.height())/rows;for(int i=0;i<cards.size();i++){if(i&&i%per==0)check(device.newPage(),"PRINT_PAGE_FAILED");p.save();auto cell=QRectF((i%cols)*w,(i%per/cols)*h,w,h);p.translate(cell.topLeft());p.scale((w-10)/420.0,(h-10)/280.0);paintCard(p,{0,0,420,280},cards[i].toObject());p.restore();}p.end();}
void Vouchers::exportFile(QUrl path,QString format,QString paper){try{check(authorization(),"ACCESS_DENIED");check(!batch.isEmpty(),"NO_BATCH");if(format=="PDF"){QPdfWriter pdf(path.toLocalFile());pdf.setResolution(144);pdf.setPageSize(paper=="A4"?QPageSize(QPageSize::A4):QPageSize(QSizeF(paper=="58"?58:80,65),QPageSize::Millimeter));pdf.setPageMargins(QMarginsF(3,3,3,3));render(pdf,paper);}else if(format=="PNG"){QImage image(840,560,QImage::Format_RGB32);image.fill(Qt::white);QPainter p(&image);p.scale(2,2);paintCard(p,{0,0,420,280},batch["vouchers"].toArray().first().toObject());p.end();check(image.save(path.toLocalFile()),"PNG_SAVE_FAILED");}else if(format=="RSC")writeAtomic(path.toLocalFile(),script(batch).toUtf8());else if(format=="CSV"){QStringList cols{"username","password","profile","mode","durationValue","durationUnit","limitBytesTotal","provisionState"},lines,cells;lines.append(cols.join(','));for(auto v:batch["vouchers"].toArray()){cells.clear();for(auto c:cols)cells.append(Protocol::csvCell(Protocol::jsonText(v.toObject()[c])));lines.append(cells.join(','));}writeAtomic(path.toLocalFile(),QByteArray("\xEF\xBB\xBF")+lines.join("\r\n").toUtf8());}else throw std::runtime_error("INVALID_FORMAT");message="تم تصدير الكروت • Vouchers exported";}catch(const std::exception&e){message=e.what();}emit changed();}
void Vouchers::print(QString paper){try{check(authorization(),"ACCESS_DENIED");QPrinter printer(QPrinter::HighResolution);printer.setPageSize(paper=="A4"?QPageSize(QPageSize::A4):QPageSize(QSizeF(paper=="58"?58:80,65),QPageSize::Millimeter));QPrintDialog dialog(&printer);if(dialog.exec()==QDialog::Accepted)render(printer,paper);}catch(const std::exception&e){message=e.what();}emit changed();}
void Vouchers::exportArchive(QUrl path,QString password){try{check(authorization(),"ACCESS_DENIED");QJsonArray batches;for(auto value:archive()){auto id=value.toMap()["id"].toString();auto clear=Vault::unprotect(readBounded(directory+"/"+id+".fgv"));check(QJsonDocument::fromJson(clear).isObject(),"ARCHIVE_UNREADABLE");batches.append(QJsonObject{{"id",id},{"batch",QString::fromUtf8(clear)}});clear.fill('\0');}auto clear=QJsonDocument(QJsonObject{{"format","FG-MTM-vouchers"},{"schema",1},{"batches",batches}}).toJson(QJsonDocument::Compact);auto encrypted=Vault::encrypt(clear,password);clear.fill('\0');writeAtomic(path.toLocalFile(),encrypted);message="تم تصدير الأرشيف المشفر • Encrypted archive exported";}catch(const std::exception&e){message=e.what();}emit changed();}
void Vouchers::importArchive(QUrl path,QString password){try{check(authorization(),"ACCESS_DENIED");auto clear=Vault::decrypt(readBounded(path.toLocalFile()),password);auto root=QJsonDocument::fromJson(clear).object();clear.fill('\0');check(root["format"]=="FG-MTM-vouchers"&&root["schema"].toInt()==1&&root["batches"].isArray(),"INVALID_BACKUP");auto rows=root["batches"].toArray();check(rows.size()<=10000,"ARCHIVE_LIMIT");QSet<QString> ids;QList<QPair<QString,QByteArray>> validated;for(auto value:rows){auto row=value.toObject();auto id=text(row,"id");check(QRegularExpression("^[0-9]{1,19}(-[a-fA-F0-9-]{36})?$").match(id).hasMatch()&&!ids.contains(id),"INVALID_BATCH_ID");ids.insert(id);auto doc=QJsonDocument::fromJson(text(row,"batch").toUtf8());check(doc.isObject(),"INVALID_BATCH");auto b=doc.object();auto cards=b["vouchers"].toArray();check(cards.size()==b["request"].toObject()["quantity"].toInt()&&cards.size()>=1&&cards.size()<=5000,"INVALID_BATCH");QSet<QString> names;for(auto v:cards){auto c=v.toObject();auto name=text(c,"username");check(!name.isEmpty()&&name.size()<=128&&text(c,"password").size()<=256&&!names.contains(name),"INVALID_VOUCHER");names.insert(name);}auto plain=doc.toJson(QJsonDocument::Compact);auto file=directory+"/"+id+".fgv";if(QFile::exists(file)){auto existing=QJsonDocument::fromJson(Vault::unprotect(readBounded(file)));check(existing.object()==b,"ARCHIVE_CONFLICT");}else validated.append({file,Vault::protect(plain)});plain.fill('\0');}for(auto row:validated)writeAtomic(row.first,row.second);message="تم استيراد الأرشيف • Archive imported";}catch(const std::exception&e){message=e.what();}emit changed();}
