function toggleLanguage(){var en=document.documentElement.lang!=='en';document.documentElement.lang=en?'en':'ar';document.documentElement.dir=en?'ltr':'rtl';document.querySelectorAll('[data-ar]').forEach(function(e){e.textContent=e.getAttribute(en?'data-en':'data-ar')});var welcome=document.querySelector('.welcome');if(welcome){var original=welcome.dataset.originalWelcome||welcome.textContent;welcome.dataset.originalWelcome=original;if(original==='أهلاً بك — اتصل بالواي فاي ثم أدخل كود الكارت')welcome.textContent=en?'Welcome. Enter your voucher code to connect.':original}document.querySelectorAll('[data-placeholder-ar]').forEach(function(e){e.placeholder=e.getAttribute(en?'data-placeholder-en':'data-placeholder-ar')});try{localStorage.setItem('fgLang',en?'en':'ar')}catch(e){}if(typeof fgStatus==='function')fgStatus()}
(function(){try{if(localStorage.getItem('fgLang')==='en')toggleLanguage()}catch(e){}var link=document.getElementById('website');if(link&&!link.getAttribute('href'))link.hidden=true;var phone=document.querySelector('.support-phone'),support=document.querySelector('.support-label');if(support&&phone&&!phone.textContent.trim())support.hidden=true;var error=document.getElementById('error');if(error){var raw=decodeURIComponent((error.dataset.error||'').replace(/\+/g,' '));if(/invalid username|invalid password/i.test(raw))error.textContent='الكود أو كلمة المرور غير صحيحة. / Invalid code or password';else if(/limit|expired/i.test(raw))error.textContent='انتهت مدة الكارت أو البيانات. تواصل مع الدعم. / Voucher limit reached';else if(/already|simultaneous/i.test(raw))error.textContent='الكارت مستخدم على جهاز آخر. / Voucher is in use';}})();

// Values come from the HotSpot servlet. Voucher metadata never replaces router quota counters.
function fgNumber(raw){return /^\d+$/.test(String(raw).trim())?Number(raw):null}
function fgBytes(raw,en){var n=fgNumber(raw);if(n===null)return !String(raw).trim()||String(raw).trim()==='---'?(en?'No total data limit':'بدون حد إجمالي للبيانات'):(en?'Allowance unavailable':'المتبقي غير متاح');var units=['B','KB','MB','GB','TB'],i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return (i?n.toFixed(2).replace(/\.00$/,''):String(n))+' '+units[i]}
function fgDuration(raw,en){raw=String(raw).trim();if(!raw||raw==='---')return en?'No time limit':'بدون حد زمني';var m=raw.match(/^(?:(\d+)w)?(?:(\d+)d)?(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$/);if(!m||!m.slice(1).some(Boolean))return raw;var labels=en?['week','day','h','min','s']:['أسبوع','يوم','ساعة','دقيقة','ثانية'];return m.slice(1).map(function(v,i){return v&&Number(v)>0?Number(v)+' '+labels[i]:''}).filter(Boolean).join(' ')||(en?'0 s':'0 ثانية')}
function fgRow(el,show){el.hidden=!show;if(el.previousElementSibling)el.previousElementSibling.hidden=!show}
function fgStatus(){var en=document.documentElement.lang==='en';document.querySelectorAll('.bytes,.duration').forEach(function(el){if(el.dataset.raw===undefined)el.dataset.raw=el.textContent.trim();var raw=el.dataset.raw,n=fgNumber(raw);if(el.classList.contains('optional-quota')){fgRow(el,n!==null);if(n===null)return}if(el.classList.contains('bytes')){el.textContent=el.classList.contains('quota')||el.classList.contains('optional-quota')?fgBytes(raw,en):(n===null?(en?'Counter unavailable':'العداد غير متاح'):fgBytes(raw,en))}else el.textContent=fgDuration(raw,en)});var user=document.getElementById('username');if(!user)return;try{var v=JSON.parse(sessionStorage.getItem('fgVoucher')||'null');if(!v||v.u!==user.textContent.trim())return;var p=document.getElementById('profile'),e=document.getElementById('expiry');if(p&&v.profile){p.textContent=v.profile;fgRow(p,true)}if(e&&v.expiry&&Number.isFinite(Number(v.expiry))&&Number(v.expiry)>0){var d=new Date(Number(v.expiry));if(!isNaN(d.getTime())){e.textContent=d.toLocaleString(en?'en-GB':'ar-EG');fgRow(e,true)}}}catch(e){}}
fgStatus();
