<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Include="../FG.MTM.Desktop/Server/*.cs" Link="Server/%(Filename)%(Extension)" /><Compile Include="../FG.MTM.Desktop/Router/*.cs" Link="Router/%(Filename)%(Extension)" /></ItemGroup></Project>
