package com.fgmachines.mikrotikmanager.voucher

object WcgExporter {

    fun export(
        settings: WcgCardSettings,
        batch: VoucherBatch
    ): VoucherExportBundle =
        VoucherExportBundle(
            rsc = toRsc(settings, batch),
            csv = toCsv(batch),
            html = toHtml(settings, batch)
        )

    fun toRsc(
        settings: WcgCardSettings,
        batch: VoucherBatch
    ): String = buildString {
        appendLine("# Generated by FG MikroTik Manager")
        appendLine("# Mode: ${settings.accessMode}")
        appendLine("# Network: ${settings.networkName}")
        appendLine("# Count: ${batch.vouchers.size}")
        appendLine()

        batch.vouchers.forEach { voucher ->
            when (settings.accessMode) {
                VoucherAccessMode.HOTSPOT -> appendLine(hotspotLine(voucher))
                VoucherAccessMode.USER_MANAGER -> {
                    appendLine(userManagerLine(voucher))
                    if (voucher.profile.isNotBlank()) {
                        appendLine(
                            "/user-manager user-profile add user=" +
                                quote(voucher.username) +
                                " profile=" +
                                quote(voucher.profile)
                        )
                    }
                }
                VoucherAccessMode.PPPOE -> appendLine(pppoeLine(voucher))
            }
        }
    }

    fun toCsv(batch: VoucherBatch): String = buildString {
        appendLine("username,password,profile,server,limit_uptime,limit_bytes_total,comment")
        batch.vouchers.forEach { voucher ->
            append(csv(voucher.username)).append(',')
            append(csv(voucher.password)).append(',')
            append(csv(voucher.profile)).append(',')
            append(csv(voucher.server)).append(',')
            append(csv(voucher.limitUptime.orEmpty())).append(',')
            append(csv(voucher.limitBytesTotal?.toString().orEmpty())).append(',')
            append(csv(voucher.comment))
            appendLine()
        }
    }

    fun toHtml(
        settings: WcgCardSettings,
        batch: VoucherBatch
    ): String = buildString {
        appendLine("<!doctype html>")
        appendLine("<html lang=\"ar\" dir=\"rtl\"><head><meta charset=\"utf-8\">")
        appendLine("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">")
        appendLine("<title>WiFi Cards - ${escape(settings.networkName)}</title>")
        appendLine("<style>")
        appendLine("@page{size:A4;margin:8mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;margin:0;color:#111}")
        appendLine(".grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7mm}.card{border:1px solid #222;border-radius:12px;padding:12px;break-inside:avoid;text-align:center}")
        appendLine(".network{font-size:18px;font-weight:700}.code{font:700 22px monospace;letter-spacing:1px}.meta{font-size:12px;margin-top:6px}.qr{font-size:10px;overflow-wrap:anywhere;border:1px dashed #999;padding:5px;margin-top:8px}")
        appendLine("@media print{body{print-color-adjust:exact}.card{page-break-inside:avoid}}")
        appendLine("</style></head><body><div class=\"grid\">")

        batch.vouchers.forEachIndexed { index, voucher ->
            val qrPayload = hotspotQrPayload(settings.hotspotLoginUrl, voucher)
            appendLine("<section class=\"card\">")
            appendLine("<div class=\"network\">${escape(settings.networkName.ifBlank { "WiFi" })}</div>")
            appendLine("<div class=\"meta\">كارت رقم ${index + 1}</div>")
            appendLine("<div class=\"meta\">اسم المستخدم</div>")
            appendLine("<div class=\"code\">${escape(voucher.username)}</div>")
            if (voucher.password != voucher.username) {
                appendLine("<div class=\"meta\">كلمة المرور</div>")
                appendLine("<div class=\"code\">${escape(voucher.password)}</div>")
            }
            if (settings.priceText.isNotBlank()) {
                appendLine("<div class=\"meta\">السعر: ${escape(settings.priceText)}</div>")
            }
            voucher.limitUptime?.takeIf { it.isNotBlank() }?.let {
                appendLine("<div class=\"meta\">المدة: ${escape(it)}</div>")
            }
            settings.supportPhone.takeIf { it.isNotBlank() }?.let {
                appendLine("<div class=\"meta\">الدعم: ${escape(it)}</div>")
            }
            if (qrPayload.isNotBlank()) {
                appendLine("<div class=\"qr\">QR DATA: ${escape(qrPayload)}</div>")
            }
            appendLine("</section>")
        }

        appendLine("</div></body></html>")
    }

    fun hotspotQrPayload(
        loginUrl: String,
        voucher: VoucherDraft
    ): String {
        if (loginUrl.isBlank()) return ""
        val separator = if ('?' in loginUrl) '&' else '?'
        return loginUrl.trim() +
            separator +
            "username=" + urlEncode(voucher.username) +
            "&password=" + urlEncode(voucher.password)
    }

    private fun hotspotLine(voucher: VoucherDraft): String =
        buildString {
            append("/ip hotspot user add")
            append(" name=").append(quote(voucher.username))
            voucher.password.takeIf { it.isNotBlank() }?.let {
                append(" password=").append(quote(it))
            }
            append(" profile=").append(quote(voucher.profile))
            append(" server=").append(quote(voucher.server))
            voucher.limitUptime?.takeIf { it.isNotBlank() }?.let {
                append(" limit-uptime=").append(quote(it))
            }
            voucher.limitBytesTotal?.let {
                append(" limit-bytes-total=").append(it)
            }
            voucher.comment.takeIf { it.isNotBlank() }?.let {
                append(" comment=").append(quote(it))
            }
        }

    private fun userManagerLine(voucher: VoucherDraft): String =
        buildString {
            append("/user-manager user add")
            append(" name=").append(quote(voucher.username))
            voucher.password.takeIf { it.isNotBlank() }?.let {
                append(" password=").append(quote(it))
            }
            voucher.comment.takeIf { it.isNotBlank() }?.let {
                append(" comment=").append(quote(it))
            }
        }

    private fun pppoeLine(voucher: VoucherDraft): String =
        buildString {
            append("/ppp secret add")
            append(" name=").append(quote(voucher.username))
            voucher.password.takeIf { it.isNotBlank() }?.let {
                append(" password=").append(quote(it))
            }
            append(" service=pppoe")
            append(" profile=").append(quote(voucher.profile))
            voucher.limitBytesTotal?.let {
                append(" limit-bytes-out=").append(it)
            }
            voucher.comment.takeIf { it.isNotBlank() }?.let {
                append(" comment=").append(quote(it))
            }
        }

    private fun quote(value: String): String =
        "\"" + value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"") + "\""

    private fun csv(value: String): String =
        "\"" + value.replace("\"", "\"\"") + "\""

    private fun escape(value: String): String =
        value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;")

    private fun urlEncode(value: String): String =
        java.net.URLEncoder.encode(value, Charsets.UTF_8.name())
}
